### ISSUE TITLE
Ubisoft connect now showing black screen

### ISSUE THREAD

**Issue by puppet-head** [moraroy/NonSteamLaunchers-On-Steam-Deck#103]
This was working yesterday but an update seems to have killed it, I’ve tried a few different proton versions without any luck.

Did a reinstall but it seems to pull the same broken version.

**Comment by moraroy** [comment]
@puppet-head does uplay install?

**Comment by puppet-head** [comment]
Yes, appears to install okay and does an update, then fails to launch.  On gaming mode its a black screen, on desktop just a box outline.

looking at the launch logs for ubisoft I can see an error  in cefclienthandler.cpp.  CEF render process crashed, which loops continually.  

I’m guessing this will actually need a proton fix?
