### ISSUE TITLE
Pressing Ok at custom url screen results in cancel

### ISSUE THREAD

**Issue by Jellman01** [moraroy/NonSteamLaunchers-On-Steam-Deck#112]
Hi there.

It seems like in the latest script when leaving the custom url blank as instructed and clicking on ok (with launchers selected) the ok button acts like the cancel button, or at least you cannot continue if the field is left blank.

```
The cancel button was clicked or no custom websites were entered
+ exit 1
```

Please see attached log. 

Thanks for the great script!
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12306033/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@Jellman01 oops. That was due to my new code last night my fault. I'll get a hot fix in asap. Nice catch btw!

**Comment by moraroy** [comment]
@Jellman01 should be fixed i think.. let me know? i updated the .sh file

**Comment by Jellman01** [comment]
Hi there Roy, All working now. Thanks again for the script! Scott
