### ISSUE TITLE
itch.io windows size bug

### ISSUE THREAD

**Issue by kepiz** [moraroy/NonSteamLaunchers-On-Steam-Deck#113]
Minimized itch.io launcher windows size unintentionally, now it's a line, and it's impossible to restore.
Any solution?

**Comment by kepiz** [comment]
Ok solved it, but going to desktop mode opening itch.Io, and the clicking full screen from the task bar

**Comment by Vova228337** [comment]
I also faced this problem. 
My decision:
1. Switch to Desktop Mode.
2. Open Itch.Io from Steam Library.
The window will be, as before, 1 pixel wide and pressed to the right side of the screen. It's okay.
3. RMB on the application icon in the taskbar.
4. Select three points there.
5. Resize.
6. Here it is at your discretion: either change its resolution to whatever you want, or expand it to full screen (I did the latter)
