### ISSUE TITLE
Not downloading items properly.

### ISSUE THREAD

**Issue by RetroRedux99** [moraroy/NonSteamLaunchers-On-Steam-Deck#117]
OK so I downloaded the newest version (2.99) and It isn't downloading anything. When I have items set to download it finishes the download bar, closes steam, closes itself, Steam comes back a few seconds later but the konsole doesn't. When I look in the compatdata folder it shows folders for the items i downloaded but they're all empty. and there was nothing added to steam except of chrome shortcuts.

**Comment by moraroy** [comment]
@RetroRedux99 can you show me the log? It's in the download folder

**Comment by RetroRedux99** [comment]
Sure
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12340503/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@RetroRedux99 + /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-11/proton run MsiExec.exe /i /home/deck/Downloads/NonSteamLaunchersInstallation/EpicGamesLauncherInstaller.msi /qn
/home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh: line 164: /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-11/proton: No such file or directory

for some reason the proton file is missing in your Proton folder. I would try deleeting the Proton GE 8-11 in the compatbility tools.d folder and then try installing Proton 8 GE 11 using Proton UpQT and then see if that correctly installs proton perhaps my script is skipping that file for some reason

**Comment by RetroRedux99** [comment]
That worked, Thanks man.
