### ISSUE TITLE
GeForce now not starting

### ISSUE THREAD

**Issue by mryshakow** [moraroy/NonSteamLaunchers-On-Steam-Deck#119]
Hey Hey Guys,

first of all: Great work. I love it...

OK, and now the problem:

I have installed via script GeForce Now. And this is how:

I have... 

1. started the script following the instructions
2. selected "GeForce Now" in the menu and clicked on continue
3. did not add any links and clicked on continue
4. and waited a bit until
5. Steam has restarted

GeForce Now now also appears in Steam. If I want to start it, it loads briefly and then aborts again. :(

What step did I forget? Do I need to set something specific? Hope you guys can help me.

btw: I already have installed BattleNet and Diablo IV successfully... works like a charm.

**Comment by moraroy** [comment]
@mryshakow you need Google Chrome from the discovery store

**Comment by mryshakow** [comment]
Thank you for the super quick reply!
