### ISSUE TITLE
EA app crashes

### ISSUE THREAD

**Issue by sedoLevi609** [moraroy/NonSteamLaunchers-On-Steam-Deck#12]
EA app crashes on startup

**Comment by moraroy** [comment]
Did you force compatability??

**Comment by sedoLevi609** [comment]
@moraroy yes, forced compatibility, it crashes with proton 8,but no better results with the latest proton-ge

**Comment by sedoLevi609** [comment]
Could it be a problem if I installed it through epic games(the game I wanted to install need to go to EA app)?

**Comment by moraroy** [comment]
Yikes... ok.. thanks for letting me know. GE Proton seemed to work at 8-2 now its on 8-3 I may have to see what I can do about that.

**Comment by moraroy** [comment]
I'm not sure what you mean @sedoLevi609  but I do know you may be able to switch installers like that if you change the compatdsta command in the launch options?

**Comment by sedoLevi609** [comment]
I mean epic games wants to open EA app if I want to install EA app that I have on epic games. sorry if it's not understandable, but it may be not important anyway

**Comment by moraroy** [comment]
@sedoLevi609 I see what youre saying... ok here's what you do.    As long as Epic Games Launcher and The EA App are installed in the same prefix (NonSteamLaunchers) in the compatdata folder. Then they can communicate with each other. The EA App will open up the correct Epic games for you if you're signed in and vice versa.

**Comment by sedoLevi609** [comment]
Thanks, I get it.

**Comment by sedoLevi609** [comment]
@moraroy EA app no longer crashes, but still not launches(proton ge 8-3)

**Comment by sedoLevi609** [comment]
@moraroy Not important last comment, got it working
