### ISSUE TITLE
Steam library non-steam launchers not showing.

### ISSUE THREAD

**Issue by winterfrost999** [moraroy/NonSteamLaunchers-On-Steam-Deck#124]
Hi,

Same issue for me as with the others. The installer works and restarts Steam after installing the launchers but the launchers don't show up in the Steam library. I can't seem to find the installed launchers folder either.

The v2.99 zip that I downloaded from the "releases" portion shows nohup when I execute the script. The v2.99 from the "download" button in the "how to install section" shows the proper logs when I execute the script, but still no launchers at the end.

I only have one account logged onto Steam.

This is my log file.
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12471162/NonSteamLaunchers-install.log)

I've checked home>deck>local>share>steam>steamapps>compatdata>nonsteamlaunchers, and it's empty

Thanks in advance for investigating this!

**Comment by moraroy** [comment]
@winterfrost999 ive replied in another thread regarding your problem. im going to close this one.

**Comment by GitToby** [comment]
Can you link to the relevant issue? I'm getting the same issue and looking for the right thread.
