### ISSUE TITLE
Script won’t work anymore

### ISSUE THREAD

**Issue by zozoros** [moraroy/NonSteamLaunchers-On-Steam-Deck#126]
While installing multiple launchers, the script froze after I logged into battle.net. Something told me to log in later but I didn’t. After around 15 minutes I cancelled the script and now it won’t open anymore. I tried deleting all associated files and rebooting my steamdeck but still, nothing happens.

**Comment by moraroy** [comment]
@zozoros can u send the log?

**Comment by zozoros** [comment]
Hi, it’s working now. I guess updating and shutting down and leaving it alone for a while fixed things.
