### ISSUE TITLE
Battle.net Launcher no longer launching after fresh install

### ISSUE THREAD

**Issue by Greybaine** [moraroy/NonSteamLaunchers-On-Steam-Deck#128]
Looks like battle.net is no longer launching out of the box. Initially, I thought it was my steamdeck as I had installed bnet previously. I ran through the following steps:

1. completely reset my steamdeck to factory settings
2. installed nonsteam launchers for steam deck
3. Selected battle.net
4. installed battle.net 
5. At this stage, it asked me to log into my battle.net account (so far so good)
6. Battle.net closed along with non-steam launchers (paused for a moment as I expected _something_ to happen)
7. Navigated to battle.net in my steam games
8. Clicked  "play" 
9. Nothing happens.

Compatibility = `GE-proton8.14`
target = `"/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe"`
start in = `"/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/Battle.net"`
launch options = `STEAM_COMPAT_DATA_PATH="/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/" %command%`

**Comment by moraroy** [comment]
@Greybaine can you send the log?

**Comment by jbdotmpeg** [comment]
same issue

**Comment by mrmldeboy** [comment]
same

**Comment by cazeaux** [comment]
Same issue here on a brand new deck (only installed Proton GE). Where are the logs ?

**Comment by cazeaux** [comment]
After a steam deck reboot, it finally launched and could play Diablo 4. So maybe a reboot is required.

**Comment by VioletteVanadium** [comment]
I also had to reboot the steam deck, but then it launched just fine.
