### ISSUE TITLE
NonSteamLaunchers script does not work on SteamOS 3.5

### ISSUE THREAD

**Issue by AlbertoSPJ** [moraroy/NonSteamLaunchers-On-Steam-Deck#129]
I have recently update SteamOS to reach 3.5. I suffered the classic EA app problem of requiring updating and stuck in the loop of requiring resetting the app. To fix that, I decided to clean al the launchers that I have installed via NonSteamLaunchers script (as I always did, because once I uninstall manually the EA app the script is not able to manage a reinstallation if I don’t wipe completely all the launchers). I downloaded the las version of the script and after running any launcher work and also are not appearing in the Steam client. When I open the script, the paths are not showed following the launcher section (looks like nothing was installed).

I will try reverting to 3.4 and trying again. However, considering the 3.5 coming soon this should be taken into account.

Thanks in advance!

**Comment by moraroy** [comment]
@AlbertoSPJ can you send me the log?

**Comment by tomtompipsia** [comment]
just in case, if you're having problems with autoupdating loop on EA app, instead of reinstalling launchers you can do this. Download up-to-date ea installer and using proton tricks point this installation to ea app id, then you can select repair and after "repair" everything works fine.

**Comment by MrArdillo** [comment]
i have the same issue, the script creates the folders but they are empty

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12838165/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@MrArdillo @AlbertoSPJ i just updated the script please let me know how it goes now

**Comment by color-space** [comment]
@moraroy remember about the symlink thing i suggested you to test? I think they have the same problem that i had. 

They probably installed on local drive first, then selected move to sdcard, or opposite order. The symlink in roughly /home/.share/steam/steamapps/compatdata/NonSteamLaunchers points to the sd card/NonSteamLaunchers, but this is unfortunately a symlink aswell and the symlink in the sd card, points back to /home/.share/steam/steamapps/compatdata/NonSteamLaunchers

**Comment by moraroy** [comment]
@color-space oh I see, so it's like a symlink loop? Ok.. thanks for letting me know I'm going to look into the "move to SD card" function next

**Comment by color-space** [comment]
Tough, if its about the EA App, i have the same problem nie and i didnt touch the NonSteamLauncher Script since it was working, probably just an ea app autopupdating issue, registry stuff missing or something

**Comment by moraroy** [comment]
@color-space did you try just reinstalling the EA App over the old one? you can just run it again and it should "repair"

**Comment by color-space** [comment]
That would probably work, i haven't tried fixing it yet

**Comment by moraroy** [comment]
@color-space yeah try it with the new 3.0 script and see if that fixes it.. soemtimes EA is broken by itself lol...but im going to be looking at the symlinks like you were saying i probably have to update them now for 3.5

**Comment by moraroy** [comment]
@color-space I believe this has been fixed so I will now close.
