### ISSUE TITLE
The script can't install launchers on SD card and can't move games

### ISSUE THREAD

**Issue by Raisanyo10008** [moraroy/NonSteamLaunchers-On-Steam-Deck#131]
How description said _"The script will install launchers and games to your SD card"_
How it works for me: launchers need to install on SSD and after move to SD card via launcher.

And second problem with games: in Itch Io I can use only path to SSD. I can't use SD card for installing games. And games not moving after use "Move to SD card" button in launcher.

**Comment by AbdullinAlex** [comment]
I have same problem and It hasn't been fixed yet.
someone pls help
