### ISSUE TITLE
Ubisoft connect 

### ISSUE THREAD

**Issue by Pakstyle** [moraroy/NonSteamLaunchers-On-Steam-Deck#134]
When I download the file and start the install Ubisoft connect is not an option in the menu where you can highlight what you want to install. Am I doing something wrong or is it really not there?

**Comment by moraroy** [comment]
@Pakstyle I haven't changed the name "Uplay" to "Ubisoft Connect", it's a typo on my part. I'll change it in the next update. However as of right now the download link for Ubisoft Connect is broken. If you can find me a reliable alternative source for the Ubisoft Connect launcher I'll gladly swap out the link.

**Comment by kevlav84** [comment]
I think this URL should work?  https://ubi.li/4vxt9

**Comment by moraroy** [comment]
@kevlav84 thats the one that is broken...it works manually, something has changed in the steam decks credentials or Ubisoft is having certtificate server issues because i cannot download from there anymore automatically. I use "wget" command to download the link automatically. this no longer works for some reason. Using that link manually will download it perfectly fine though.

**Comment by kurzonmorris** [comment]
> @kevlav84 thats the one that is broken...it works manually, something has changed in the steam decks credentials or Ubisoft is having certtificate server issues because i cannot download from there anymore automatically. I use "wget" command to download the link automatically. this no longer works for some reason. Using that link manually will download it perfectly fine though.

is there or could there be a way to tell your program where the executable is on our machine? that way we download it and ur program then can be told where the file is (aka downloads folder) and ur program does the rest?

by the way amasing program thanks for making it

**Comment by kevlav84** [comment]
> @kevlav84 thats the one that is broken...it works manually, something has changed in the steam decks credentials or Ubisoft is having certtificate server issues because i cannot download from there anymore automatically. I use "wget" command to download the link automatically. this no longer works for some reason. Using that link manually will download it perfectly fine though.

Gotcha.  I'm not sure if it's an awful idea, but could you use --no-check-certificate?  Maybe just for the ubisoft trainwreck?  That seems to ignore the cert issue on my linux box.

**Comment by moraroy** [comment]
@kevlav84 @kurzonmorris @Pakstyle fixed!! i updated the script just now , i also fixed Uplay typo it now says Ubisoft Connect

**Comment by kurzonmorris** [comment]
> @kevlav84 @kurzonmorris @Pakstyle fixed!! i updated the script just now , i also fixed Uplay typo it now says Ubisoft Connect

amazing thanks assassins creed is instslling as i type. ur amasing man. now onto a request so making a new issue hehe

**Comment by Pakstyle** [comment]
Thanks!
