### ISSUE TITLE
Need a little help (please!)

### ISSUE THREAD

**Issue by Treyway995** [moraroy/NonSteamLaunchers-On-Steam-Deck#135]
So i recently decided to download the non launchers application to my steam deck on desktop mode, i had previously already done this before without any extra steps needed, but that isn't the case this time. Every time i click on the application it pops up kate option instead of doing what it is actually supposed by default. Any suggestions? I will also attach a video so you can see what i am talking about.

**Comment by Treyway995** [comment]
https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/131362759/ac73a7a7-8cd6-4260-a9d4-7581617a1da4

**Comment by moraroy** [comment]
@Treyway995 try the github page and just use the .sh file.....you may have to enable it to execute in the properties of the sh file by right clicking on it. Either way, the download file shouldnt open up Kate, you can right click on the download file and choose to riun it in konsole if thats what you want. either way would work

**Comment by Treyway995** [comment]
> @Treyway995 try the github page and just use the .sh file.....you may have to enable it to execute in the properties of the sh file by right clicking on it. Either way, the download file shouldnt open up Kate, you can right click on the download file and choose to riun it in konsole if thats what you want. either way would work

Thank You!! I was able to get it up & running just a slight overlook on my part🤣
