### ISSUE TITLE
The install is stuck when detecting GE-Proton

### ISSUE THREAD

**Issue by liopeg** [moraroy/NonSteamLaunchers-On-Steam-Deck#143]
Hello,

When I launch the script, I get the menu where I can select all the app nd choose the option I want.
I tried different option (ok, uninstall, search for game, etc). When I select the app I want (epic and xbox game pass) and press ok, a windows open. Updates Status, but remain stuck on Detecting, Updating and Installing GE-Proton. The bar on the window does not goes up and stays stuck at the bigining.

Did someone already had this issue?
If you did, what should I do to resolve it?

Thanks

**Comment by liopeg** [comment]
after leaving the install alone for 1h30, it start loading.
Sorry for the false alarm

**Comment by moraroy** [comment]
@liopeg not sure why the download took that long to download Proton GE what does your log say? It's in the downloads folder

**Comment by moraroy** [comment]
@liopeg i just updated the script with a new release please let me know how it works now it should dynamically grab the latest geproton

**Comment by rahmatmaulana18** [comment]
I've had the exact same issue on the latest NonSteamLaunchers v4.2.85, still waiting on the progress bar
