### ISSUE TITLE
nonsteam launcher not showing on my library after installing 

### ISSUE THREAD

**Issue by Darkalll** [moraroy/NonSteamLaunchers-On-Steam-Deck#144]
Whatever the launcher I install, it's not showing up in my steam library after the installation

**Comment by CornChip723** [comment]
Same issue here. The only thing that showed up was Game Pass, but when I tired to launch it would close immediately.

**Comment by moraroy** [comment]
@Darkalll @CornChip723 i just released a new version 3.0, i updated the GE proton to correctly extract hoepfully that fixed your guys issues sorry about that

**Comment by pavel-frolov** [comment]
I've got the same issue even after trying the 3.0 version. Launchers are downloaded and they exist, but there are no Steam shortcuts for them. Here's the log:
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/13464762/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@pavel-frolov I will look into this thank you for the log

**Comment by moraroy** [comment]
@pavel-frolov @Darkalll @CornChip723 do either of you guys have a second account on the steam deck by any chance? i havnt really added the ability to differentiate between multiple accounts yet, also if not, do you guys have any symlinks associated with your sd card? alot of directories changed in the new steam update and i havnt updated the new directory yet.

**Comment by pavel-frolov** [comment]
> @pavel-frolov @Darkalll @CornChip723 do either of you guys have a second account on the steam deck by any chance?
Yes, I do, so no luck installing launchers automatically?

**Comment by moraroy** [comment]
@pavel-frolov check the other steam account the shortcuts are probably in there... I need to figure out a better way to do multiple accounts

**Comment by uwantfries** [comment]
I have the same problem but without the complexity of different accounts. I also noticed that after trying to access the tab (and it prompting for chrome) the virtual keyboard and volume fails to work until a reboot when I get a "Verifying integrity" message during bootup.

**Comment by pavel-frolov** [comment]
I did a fresh install of SteamOS, logged into a single Steam account and everything worked fine. I understand that it's not an option for everyone, just sharing my experience

**Comment by kingblah** [comment]
Bumping on this one as just had the same issue - tried adding Geforce Now, the script runs, steam restarts, but nothing new is there
