### ISSUE TITLE
Epic Games shows blank screen

### ISSUE THREAD

**Issue by Ashulat** [moraroy/NonSteamLaunchers-On-Steam-Deck#145]
I've added Epic Games Launcher successfully using the script. 
I can open Epic in game mode. And I get the login screen for the store. Which I can successfully login to. But after that the screen stays blank. I have the new OLED deck. 
Online there are lots of suggestions for it. But I have no idea how to implement any of them. Like changing resolution etc. 
Is that something you can do in the script? 
Would love to try out any changes to see if they work.

**Comment by moraroy** [comment]
Sorry about that @Ashulat I'm looking into it now!

**Comment by LukeNowland** [comment]
Came here to say I'm having the exact same issue. However even if I bypass NonSteamLaunchers and install Epic manually, it still does not work.

**Comment by moraroy** [comment]
@LukeNowland yeah I'm thinking this is a proton issue. An epic issue or the new steam update... I'm looking into it now..

**Comment by moraroy** [comment]
@LukeNowland @Ashulat I have the 64GB old steam deck LCD... everything I've tested is running fine and the script is running fine on my end. I'm guessing this may be an Oled issue, specifically the resolution, maybe something in epic changed.... add this to the end after the %command% in the launch options... make sure there is a space between. -screen-width 1280 -screen-height 800 -screen-fullscreen 1

**Comment by LukeNowland** [comment]
Tried it, unfortunately didn’t make any difference. Also ran a bunch of other custom resolutions from the drop down menu forcing resolutions internal and external with no success.

**Comment by moraroy** [comment]
@LukeNowland ...hmm do you have the new oled? Or just the old lcd?

**Comment by LukeNowland** [comment]
@moraroy I also have the OLED, I suspect you’re right about it being specific to that model, though I’m not sure why that would cause a problem like this.

**Comment by moraroy** [comment]
@LukeNowland try changing the refresh rate... the oled is running at 90hz maybe try forcing 60? - refresh 60

**Comment by jcoker85** [comment]
I have an older 512 GB LCD and new 1 TB OLED and I have tried everything to remediate this issue on the OLED model (or hell at this point I even tried to replicate the issue on the LCD model). Exact same settings on the 1 TB. Tried Proton Experimental, 8, 7, GE, no dice. Tried factory reset, limiting refresh rate as well, no dice there either.

**Comment by LukeNowland** [comment]
@moraroy No luck. Also tried every combination of refresh rates and scaling modes I could think of.

**Comment by moraroy** [comment]
@LukeNowland maybe a gamescope oled issue? But I don't know why that would effect anything.

**Comment by bluedoggy** [comment]
Same here. Blank screen. Oled 512

**Comment by Ashulat** [comment]
Could there be high issues? 
https://www.epicgames.com/help/en-US/epic-games-store-c5719341124379/launcher-support-c5719357217435/epic-games-launcher-displays-incorrectly-or-appears-blank-a5720229169819?sessionInvalidated=true

**Comment by moraroy** [comment]
@Ashulat it's possible at this point.. try this? -forcedesktopscaling 2

**Comment by LukeNowland** [comment]
> @Ashulat it's possible at this point.. try this? -forcedesktopscaling 2

Just tried it on mine, no dice.

**Comment by moraroy** [comment]
@LukeNowland :( well it's definitely a graphical issue. I'm thinking one of the command lines from epic game or steam will be able to fix this in the launch options just have to figure out what setting it wants

**Comment by yuric5555** [comment]
I'm having the same problem on the 1tb OLED.  It works in desktop mode, just not game mode.

**Comment by moraroy** [comment]
@yuric5555 I only own the 64GB LCD Steam Deck so I can't test things on the new, we've narrowed it down to maybe a gamescope issue when in gamemode.game mode.. can you confirm other launchers work with the oled?

**Comment by Ashulat** [comment]
Amazon works. Can check Gog later today.

**Comment by TomFanella4** [comment]
I'm also having the same issue on latest stable + oled deck. Please let me know how I can help debug. (I'm a software eng)

**Comment by bluedoggy** [comment]
Rockstar launcher works fine

**Comment by bluedoggy** [comment]
Observation. If you click blindly on where unreal engine button is it shows the unreal page. If you click back to your library, its a blank page again

**Comment by TomFanella4** [comment]
Even though the UI isn't rendering, the cursor still changes when hovering over buttons. I am able to launch games by clicking on where they should be in the UI.

**Comment by moraroy** [comment]
@TomFanella4 interesting thank you guys for troubleshooting, maybe go in konsole and and do gamemoded --help maybe see if there is anything in there that could potentially give info on why just gamemode is affected.. it sounds like everything is rendering but for some reason epic doesn't like being in game mode.

**Comment by Touhma** [comment]
Same here , any news ?

**Comment by ayinde6** [comment]
New here but I found this on another site and now it works perfectly FOR ME...

Thanks to --- Lopsided_Elephant_24
•
1 hr. ago
• Edited 45 min. ago

**I found something that seems to work. In the 3rd party launcher in Steam used for the Epic game launcher, go to Properties->Shortcut->Target, and change the text to:

"{The path to the epic game launcher}/EpicGamesLauncher.exe" -opengl**

From Ayinde6 --- LET ME KNOW IF IT WORKS FOR YOU

**Comment by bhoumik24** [comment]
> New here but I found this on another site and now it works perfectly FOR ME...
> 
> Thanks to --- Lopsided_Elephant_24 • 1 hr. ago • Edited 45 min. ago
> 
> **I found something that seems to work. In the 3rd party launcher in Steam used for the Epic game launcher, go to Properties->Shortcut->Target, and change the text to:
> 
> "{The path to the epic game launcher}/EpicGamesLauncher.exe" -opengl**
> 
> From Ayinde6 --- LET ME KNOW IF IT WORKS FOR YOU

Yup worked for me!  Thanks!!

**Comment by ayinde6** [comment]
Oh I am using Steam deck 1TB OLED BTW

**Comment by moraroy** [comment]
@ayinde6 thank you for the fix, I'll add it to the script. but I don't want to add it to the location tbh can you confirm it will work in the launch options... you may want to also test this in the launch options as well -force-opengl

**Comment by bhoumik24** [comment]
Didn’t work for me in launch options, only in target  (512 GB OLED model).

**Comment by LukeNowland** [comment]
> @ayinde6 thank you for the fix, I'll add it to the script. but I don't want to add it to the location tbh can you confirm it will work in the launch options... you may want to also test this in the launch options as well -force-opengl

Putting it at the end of launch options does not work. And I can confirm that putting olengl at the end of the target does work.

**Comment by moraroy** [comment]
@LukeNowland aw dang ok, that sucks.socks.. I didn't want to mess with the location directory too much just in case valve decides to update it... but I'll add --opengl to the end of it in the script.. if you guys are able to see if you can get --opengl or -force-opengl to work in the launch options that would be a big help thank you guys for figuring it out!!

**Comment by LukeNowland** [comment]
> @LukeNowland aw dang ok, that sucks.socks.. I didn't want to mess with the location directory too much just in case valve decides to update it... but I'll add --opengl to the end of it in the script.. if you guys are able to see if you can get --opengl or -force-opengl to work in the launch options that would be a big help thank you guys for figuring it out!!

I’m not sure if this was a just a typo, but I wanted to mention that “— opengl” does not work at end of Target, only “-opengl”

**Comment by ayinde6** [comment]
![20231125_220318](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/152046467/f1aefdd4-dc25-41ca-8751-f6982b15a95d)
![20231125_220256](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/152046467/e525f38d-61e9-4354-9dd1-ad5b2639bac8)

**Comment by moraroy** [comment]
@LukeNowland ohhh nice catch ok gotcha.. I'm used to command lines... ok "-opengl"

**Comment by ayinde6** [comment]
Sorry for the poor photo quality

**Comment by moraroy** [comment]
@LukeNowland @ayinde6 just updated the .sh file and its in the script now feel free to test it and make sure everything is working thanks again guys...no worries on the potato quality bro my own script is potato quality!

**Comment by Ashulat** [comment]
Woohoo! Glad the solution was found!

**Comment by moldof97** [comment]
Hi, i am sorry to bring this up, i have just bought an oled model 512gb. I tried to install epic through NSL, in desktop mode works however i still have black screen in game mode, i tried -opengl, tried both proton GE and experimental, changed the resolution and the refresh rate, nothing comes out of it, sometimes its totally black some times you can see it loaded half of the content but still the same. I managed to make it work by streaming the deck on my pc while opening epic games, that way it worked, I don't know if this would be of any help. After i launch epic from game mode i go on my PC and stream from the deck, that way i can use it without problems, but its not a fix, its only a workaround, I wont have the pc around me everytime.

**Comment by Ashulat** [comment]
You might want to create a new issue. Linking to this issue as the options you tried. Because this one is closed as solved.
