### ISSUE TITLE
not sure what's going on

### ISSUE THREAD

**Issue by j3Lo98** [moraroy/NonSteamLaunchers-On-Steam-Deck#147]
I have the latest steam update and I'm trying to install from v3.0. I click the launchers I want to install them choose fresh install. I click yes then it closes out and I'm back on the desktop. Just got my steam deck so 1st time trying this. I have decky loader installed.

**Comment by moraroy** [comment]
@j3Lo98 you need to install, start fresh is for deleting everything. Please read the prompts when you do it.
