### ISSUE TITLE
[Feature Request] Plex Video Streaming Support

### ISSUE THREAD

**Issue by SalmonSays** [moraroy/NonSteamLaunchers-On-Steam-Deck#148]
I note that NonSteamLaunchers supports Netflix, Amazon Prime Video, Disney+, Hulu, Youtube, and Twitch. Among these, it strikes me as a bit of an omission to not support video streaming over Plex ( https://www.plex.tv ). No pressure obviously if this is considered outside the scope of this project, but I personally consider selfhosted Plex video support of higher importance than the former 4 and only lower priority than Youtube and Twitch as "heavy hitters".

**Comment by moraroy** [comment]
@SalmonSays hey brother. I don't mind adding.. I've never used plex before.. but I'm a little confused... by going to plex.tv is this streaming through the browser? Or is this an app that needs to be downloaded? If it's through the browser... I've already made it possible to add any site you want. When you press install your prompted to Create your own Steam Shortcut for any website. Just type in your plex and you got it!

**Comment by SalmonSays** [comment]
@moraroy so it's correct that technically it can stream from browser, just like youtube/twitch/amazon prime/hulu/etc, but there is a dedicated client which is a generally preferable for better settings, codecs, UI, etc.

https://flathub.org/apps/tv.plex.PlexDesktop

Here's one example of their dedicated application. To be honest I haven't checked to see how all the video streaming apps are handled by NonSteamLaunchers, if they are all based on shortcuts then there's no good reason to make an exception for Plex. If on the other hand they do have dedicated apps built-in, then I propose this makes just as much sense.

**Comment by DanHolli123** [comment]
It's worth noting that the plex web app is app.plex.tv

**Comment by moraroy** [comment]
added
