### ISSUE TITLE
Battlenet 

### ISSUE THREAD

**Issue by Huntinseason** [moraroy/NonSteamLaunchers-On-Steam-Deck#149]
When I tried to install Battlenet it doesnt let me enter the password it just has a loading bar. I am able to put in my username and password Just cant enter it.

**Comment by sirnacnud** [comment]
I was able to fix the loading spinner by adding `WINE_SIMULATE_WRITECOPY=1` to the launch options in Steam for Battlenet.

Supposedly both Wine-GE-Proton8-25 and the latest Proton Experimental have this fix, according to this [article](https://www.gamingonlinux.com/2023/12/battlenet-broke-in-wine-proton-heres-how-to-fix-for-steam-deck-linux/), but I tried both, and only with specifying this launch option did the loading spinner go away and I was able to log in.

**Comment by Alvy04** [comment]
This may also affecting the install of the Battle.net launcher as well. I keep on getting this screen every time I'm running the installer. The NonSteamLaunchers.sh script also hangs if the Battle.net install fails (see log for details).
![Screenshot_20231202_125407](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/25238179/81ee4b7d-86e8-4fc0-a654-ba209ab1904d)

**Comment by M3DDL3R** [comment]
> I was able to fix the loading spinner by adding `WINE_SIMULATE_WRITECOPY=1` to the launch options in Steam for Battlenet.
> 
> Supposedly both Wine-GE-Proton8-25 and the latest Proton Experimental have this fix, according to this [article](https://www.gamingonlinux.com/2023/12/battlenet-broke-in-wine-proton-heres-how-to-fix-for-steam-deck-linux/), but I tried both, and only with specifying this launch option did the loading spinner go away and I was able to log in.

I tried this and still getting the endless loading spinner thing… so stressful, got my deck yesterday hopefully can get battle net to run soon for SoD

**Comment by moraroy** [comment]
@Alvy04 true... to be honest I don't like that command, but for now it'd just a bandaid... I may wait for ge proton to fix it.

**Comment by labrosman** [comment]
> @Huntinseason @Alvy04 @sirnacnud @M3DDL3R let me know how it goes just updated the .sh file to add that wine command, you have to add it before the compat data command, ive tested it on mine and it fixed the loading error.

Hi, i have the same issue.
What should i update in order to test that? 
Thanks in advace :D

**Comment by Huntinseason** [comment]
Thanks alot it worked <3.

**Comment by labrosman** [comment]
> Thanks alot it worked <3.

Same <3

**Comment by beret1212** [comment]
Hi, i also have some problem but with install. 
After downloading installation to folder nothing happened... even after few hours.. I tr many time but its stopped at thus point

![Uploading 17018880603189123258010694185271.jpg…]()

Some solution ?;(

**Comment by moraroy** [comment]
I'm going to be removing the command "WINE_SIMULATE_WRITECOPY=1" and I suggest everyone as well. This command isn't really that good as it potentially creates a new prefix folder outside of your main battlenet install... besides this, Battlenet now works again with proton expiremntal just requires waiting a bit for it to load. So I'll remove this command from the script and then when you install battlenet just use Expiremntal on force compatability for now.
