### ISSUE TITLE
Controller Support for Game Pass?

### ISSUE THREAD

**Issue by jkingsbury1000** [moraroy/NonSteamLaunchers-On-Steam-Deck#150]
Hi, Works fine for me - however when playing a game on Game Pass there is no gamepad detected. Have changed profile of controller but still no luck?

Can you use the app with the gamepad controller or do we need to add an external controller?

Funnily enough the trackpad works with the top left XBox menu, but not the in-game menu

**Comment by moraroy** [comment]
@jkingsbury1000 not sure what's going on there, but set your controller configuration back to default gamepad
