### ISSUE TITLE
Non steam launchers are showing in my library 

### ISSUE THREAD

**Issue by gazthe1** [moraroy/NonSteamLaunchers-On-Steam-Deck#151]
Hi trying to add non steam launchers into steam through your tutorial but having no luck getting it to work. Using google to download the zip files and extracting ok. Sometimes they show in steam but wont play even after going into properties and changing compatibility to experimental. Any advice or help would be amazing 👏

**Comment by moraroy** [comment]
@gazthe1 hi... not sure why you're doing any of those things... there's a button that says Download on the github, it will download a .desktop file


Select the launchers you want and then once steam restarts you click play, why change to experimental when the program gives you the latest proton GE?
