### ISSUE TITLE
protontricks appid

### ISSUE THREAD

**Issue by kdliu86** [moraroy/NonSteamLaunchers-On-Steam-Deck#156]
I'm trying to run protontricks on the NonSteamLaunchers appid but it is throwing 

     protontricks: error: argument appid: invalid int value 'NonSteamLaunchers

I need to install some fonts for the prefix.

**Comment by moraroy** [comment]
@kdliu86 there is no such things as a nonsteamlaunchers app I'd for protontricks. The folder is real in the compatdatd but is symlinked to an actual app ID say... Gog Galaxy or whatever launcher you installed first. "nonsteamlaunchers" is just an easy way for you to see where your games are installed.

**Comment by kdliu86** [comment]
Ah I see thanks, it is all under GoG Galaxy's appid.
