### ISSUE TITLE
Multiple issues.

### ISSUE THREAD

**Issue by Liamb135** [moraroy/NonSteamLaunchers-On-Steam-Deck#159]
GOG will not complete download. The download starts, and the file is a few kb, but never finishes - even after several hours.

All installed apps do not appear in Steam, they don't seem to install at all.

I have tried the "Start Fresh" option multiple times, can't get this to work at all.

**Comment by moraroy** [comment]
@Liamb135 can yous end your log its in the download folder, also, just to be sure of things. Go into steamapps/compatdata after pressing "Start Fresh" and make sure there is no files or folders regarding "NonSteamLaunchers" nor any symlinks. After that check and make sure the latest Proton GE is installed correctly by downloading the Proton Up QT Program from the discovery store. If you have proton installed delete and install it with Proton up QT sometimes my script doesnt extract this properly for some reason. but defintley send the log, if youre having download problems that sounds like a wifi issue or download issue with your deck.

**Comment by Liamb135** [comment]
Installing ProtonUp-Qt, removing the existing Proton installtion, and then reinstalling fixed all issues!
