### ISSUE TITLE
Nothing seems to run from steam

### ISSUE THREAD

**Issue by mightyflub** [moraroy/NonSteamLaunchers-On-Steam-Deck#16]
First issue is most launchers (Itch and Rockstar seem to be the exception) won't even download without using the option "Seperate app ids"

The next is nothing will run from steam afterwards. I can't even change the proton version it's using. The tickbox in compatibility isn't selectable. Same issues in both desktop and game modes.

**Comment by mightyflub** [comment]
After a few retries I was able to get Battle Net to work. No clue at all what was going wrong.

**Comment by moraroy** [comment]
@mightyflub weird ill take a look and see what going on thanks for letting me know

**Comment by pnhofmann** [comment]
> The tickbox in compatibility isn't selectable.

Definitly the problem - this tickbox must definitely be checked. I think, this is a weird bug in Steam. I had the same issue, but it fixed itself by restarting Steam once again.

**Comment by moraroy** [comment]
@pnhofmann that's a steam bug that has been for a while. You can't run non steam games or laun hers without selecting a force compatability tool, if you did it "Grey's out" the check box till you restart steam
