### ISSUE TITLE
Nothing I downloaded worked.

### ISSUE THREAD

**Issue by mikmikmikmik** [moraroy/NonSteamLaunchers-On-Steam-Deck#164]
Hulu - No
PsPlus - No
Amazon Prime - No
Netflix - No
xBox - No
I got fedup by that time and uninstalled the ones it said I could uninstall and then removed the non steam games for the others that were not in the uninstall list.

**Comment by moraroy** [comment]
@mikmikmikmik just updated try the new script :)
