### ISSUE TITLE
Vulkan Error on Epic Launcher only

### ISSUE THREAD

**Issue by NDC89** [moraroy/NonSteamLaunchers-On-Steam-Deck#168]
Tested with latest release as i was getting this error inconsistently on previous build.
Keep getting this error just for the Epic launcher.

![image](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/39611333/f29627ab-544f-4a0c-9a6c-9767238b6411)

Not sure why after doing clean install i still get this. not sure why i could be doing or this is bug?

**Comment by moraroy** [comment]
@NDC89 do you have the oled?

**Comment by NDC89** [comment]
Yes!

**Comment by jeppester** [comment]
I'm getting the same error on an OLED model.
I am not getting the error in desktop mode, ONLY in game mode.

For that reason I wonder if the issue is game scope related.

Okay, I have my Steam Deck right next to me, and it turns out that after having pressed the ignore button the store does eventually show after 2-3 minutes.

I just launched The Outer Worlds from the store and it seems to work as intended.

**Comment by NDC89** [comment]
I've tested doing this and it doesn't work for me just waiting

Should this be run on a specific type of Proton version or?

Just trying to maintain some consistency with it as i have to
reinstall/mess with it so much to get it working currently.

**Comment by moraroy** [comment]
@NDC89 its fixed

**Comment by certainOblivion** [comment]
I'm getting the error on Steam Deck OLED as well. The error did not go away after reinstalling. @moraroy what is the fix?

**Comment by moraroy** [comment]
@certainOblivion not sure...as I only have the LCD Deck to test... it's a Vulcan error.. so it has to do with the graphics drivers... I just added something to the script just now, -opengl to the installation as opposed to just the epic games shortcut, let me know if that helps you on the OLED.

**Comment by certainOblivion** [comment]
No luck unfortunately, still getting the assert

**Comment by Ratboy970** [comment]
I'm having this same issue on an OLED deck. It was working perfectly for awhile then on the weekend of the 10th I noticed it started having that issue. It will launch in desktop mode perfectly fine.

**Comment by moraroy** [comment]
@Ratboy970 IS -opengl inside the Start In text field in the shortcut ?

**Comment by Ratboy970** [comment]
yes. opengl is present i also tried without it to see if there was any change.

**Comment by Ratboy970** [comment]
switching to the beta version of the steam deck software solved the issues I was having
