### ISSUE TITLE
Kept trying to download GOG launcher but never did and now it filled my storage with OTHER data

### ISSUE THREAD

**Issue by arongkatz** [moraroy/NonSteamLaunchers-On-Steam-Deck#17]
Tried installing the script from desktop mode and it kept getting stuck downloading one of the launchers for multiple times and now i almost ran out of storage and it deleted many of my installed games and most of the storage space is showing as OTHER.
Is there a way i can fix it so i dont have to install everything all over again? Thanks!

**Comment by moraroy** [comment]
@arongkatz not sure whats going on there brother. but did you press the Start Fresh button?

**Comment by hgdagon** [comment]
Just had the same issue. GOG galaxy said it could not connect to to the internet. Then I started fresh and this happened:

![](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/15173076/7348cbcf-8893-4129-8b90-d0555aa2a7c3)
