### ISSUE TITLE
How to remove launchers?

### ISSUE THREAD

**Issue by ruifcastro** [moraroy/NonSteamLaunchers-On-Steam-Deck#18]
I installed Origin but want to remove it and install EA app.

I have started the installer again, but I don't see a remove button.

The "Start Fresh" button, what does it do? Does it remove every thing to start fresh?

Thank you for an excellent app. Good work.

**Comment by moraroy** [comment]
@ruifcastro yeah the start fresh wipes everything..I'll be adding an Uninstaller button soon!

**Comment by ruifcastro** [comment]
Cool! Thank you.

By the way, the EA app won't install because it says there is an Origin launcher.

I have found the Origin launcher folder 
/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/Origin/

Can I just delete it? Do you see any side effects?

**Comment by moraroy** [comment]
@ruifcastro yes you can delete it! Then you could install the ea app.... it's because the EA App overtakes the old origin that's why I designed it that way. You could also select separate app id's and you could install both that way

**Comment by ruifcastro** [comment]
Thank you again

**Comment by moraroy** [comment]
@ruifcastro ive added this feature in 2.7 and am closing this issue!
