### ISSUE TITLE
Can't install Epic on version 3.4

### ISSUE THREAD

**Issue by ZuhRayKing** [moraroy/NonSteamLaunchers-On-Steam-Deck#181]
Logs attached.  Seems like the installer is able to download but doesn't copy over to the compatdata file resulting in Epic Launcher not being added to game mode.  I don't see the EpicLauncher.exe file either.

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14058900/NonSteamLaunchers-install.log)

**Comment by ChildishBrando** [comment]
I’m having a similar issue, except I actually get an error that says “file not found.” Tried the Start Fresh function and still nothing.

**Comment by moraroy** [comment]
@ChildishBrando @ZuhRayKing yesterday alot of updates for proton were happening, i too also got that error with no file path found, as of today things seems to be working order on my lcd Steam Deck and evrything is isntalling jsut fine...To make sure there is no corruption, either us Proton Up Qt to get rid of all "Proton GE" and install the latest. Or go here manually and delete any proton GE's you ahve and let NSL update to the latest which it already should be doing... /home/deck/.steam/root/compatibilitytools.d/

**Comment by ChildishBrando** [comment]
@moraroy the second option worked perfectly. Thank you!
