### ISSUE TITLE
Game doesn’t launch from Game mode

### ISSUE THREAD

**Issue by windboy91** [moraroy/NonSteamLaunchers-On-Steam-Deck#182]
Hey there, 
Just installed Ubisoft connect and Prince of Persia. The game is installed on SSD and launch well from Ubi Connect.
The game automatically appears in the non steam  category but it does not start from here.
I tried switching to proton experimental but not working either.

**Comment by windboy91** [comment]
![IMG_0007](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/119671436/af05e347-6b94-47eb-885e-8259177feb36)

Does it help ?

**Comment by moraroy** [comment]
@sysmoon14 @windboy91 there's an extra Steam in there!

**Comment by windboy91** [comment]
Sorry I don’t get it 😅
This is my first time.

**Comment by moraroy** [comment]
@windboy91 it says Steam twice in the target and Startin directory it should just be Steam/steamapps/ so just delete "Steam" on both of them.. I just fixed this just now in the script.... however your scanner needs to be updated so RUN Nonstealaunchers.desktop again and it will update your .py

**Comment by windboy91** [comment]
Oh nice ! That’s working thanks 😃

another question: is it normal that it launches Ubi Connect when launching the game ?
Amazing script by the way!

**Comment by moraroy** [comment]
@windboy91 yes its normal that's what it's supposed to do. Make sure to run the .desktop file again though so you can get the fix! There is also a "Stop NSLGameScanner" that will restart the scanner for you with the latest fixes.
