### ISSUE TITLE
Nothing works once added to Steam Deck

### ISSUE THREAD

**Issue by defective1up** [moraroy/NonSteamLaunchers-On-Steam-Deck#183]
None of the shortcuts for Chrome load, they just crash on opening. Something is clearly broken. I just ran this on a fresh install of SteamOS and it'll add the apps for Hulu, Youtube,. etc, and they just crash. No version of Chrome seems to work for this either on troubleshooting. Used to work just fine. Hope it's something simple and I'm just missing something obvious.

**Comment by moraroy** [comment]
@defective1up its not clearly broken bro lol, just un check force compatability .. thats the only thing thats broken...since the new code ive been adding alot of stuff for the decky plugin so some code had to get switched around hopefully things will stablaize....just uncheck force compatability when using anything web related becuase Chrome is a flatpack and cant run with proton.

**Comment by moraroy** [comment]
@defective1up update your .py file let me know if the fix i just added helped? open up the .desktop and try to add them again

**Comment by defective1up** [comment]
> @defective1up its not clearly broken bro lol, just un check force compatability .. thats the only thing thats broken...since the new code ive been adding alot of stuff for the decky plugin so some code had to get switched around hopefully things will stablaize....just uncheck force compatability when using anything web related becuase Chrome is a flatpack and cant run with proton. ill try to get this fixed in the meantime

Sorry if my comment came off the wrong way. I appreciate all your work on this and I'm looking forward to the Decky plugin. Great stuff. 

Didn't even consider compatibility mode might be on, thanks for explaining what happened and knowing how to fix it. The applications are working with compatibility turned off. 

The only script I see if from 3 days ago, so not sure if that auto-updates or not, but it's working if I turn off compatibility so if you've got it sorted then all is well. Thanks again.

**Comment by moraroy** [comment]
@defective1up nah its all good brother my apologies, i get alot of comments so i get flustered myself
