### ISSUE TITLE
Issues configuring GoG Games in Boilr

### ISSUE THREAD

**Issue by curtisblackwell** [moraroy/NonSteamLaunchers-On-Steam-Deck#185]
I'm having difficulty getting GoG games to show up in my Steam library. I was able to install the launcher, and I can run it and I've installed Baldur's Gate 3 with it, but it won't show up in my Steam library like my Epic Games do.

I used the Find Games feature to open Boilr, and I looked at the settings. The path for GoG Games was blank, so nothing was being found. I saw [this issue](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/issues/80) talk about using Mini Galaxy, so I checked that in Boilr and saw that the path was auto-set to something like `/home/deck/GOG Games`, but that folder doesn't exist. I updated both the GoG Games and Mini Galaxy paths to the actual path where the GoG launcher was installing games by default (`/home/deck/.local/share/Steam/steamapps/compdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/GOG Galaxy/Games`), but it still isn't finding the games.

Is there something I'm doing wrong?

**Comment by moraroy** [comment]
@curtisblackwell the nslgamescanner.service should have picked that up.... press the stop game Scanner button and restart it. The. Look in your Steam library? If it's not there.. send me your log

**Comment by curtisblackwell** [comment]
I tried that and it ended up duplicating the launchers in the Non-Steam tab of my library, but didn't seem to have any effect on anything I see in Boilr. Still says "Failed finding games" for GOG and Mini Galaxy.

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14118101/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@curtisblackwell that's a boilr issue, I don't belive the Linux version of Boilr can find gog games. What I'm saying though is my program NonSteamLaunchers finds Gog games automatically if you've installed them from Gog, the game itself should be in your library once you've restarted, without you doing anything if it's working correctly. Send your log in the downloads folder so I can see.

**Comment by curtisblackwell** [comment]
Is the logs file from my last message the wrong one?

Just for clarity: I used your app to install GOG, went back to the regular Steam Deck UI, launched GOG from there, logged in to GOG, and installed Baldur's Gate 3. It's not getting added to my Steam Library like my Epic Games are.

**Comment by moraroy** [comment]
@curtisblackwell interesting ok, well the scanner is working for Epic so it's just not for gog ok, sorry I didn't see that! My bad I'll check the log!

**Comment by moraroy** [comment]
@curtisblackwell do me a favor bro, go to this fileon your deck /home/deck/.config/systemd/user/NSLGameScanner.py .... Right Click it and go to properties and set it as "executable" once done with that right click the file again, this time choose "Run In Konsole" this will show a log of the scanner in real time... let me know whats happening with baulder gate it should say whats going on

**Comment by curtisblackwell** [comment]
Looks like it's only hitting the Epic game I opened (A Short Hike).

```
['/home/deck/.config/systemd/user/Modules', '/home/deck/.config/systemd/user', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
Service started.
Existing Shortcuts:
AppID for None: -456079619
AppID for None: -66626
AppID for None: -854404784
AppID for None: -991797828
AppID for None: 0
AppID for None: 0
AppID for None: 0
AppID for None: 0
AppID for None: -32761137
AppID for None: -1961172798
Checking game: d6407c9e6fd54cb492b8c6635480d792
Match found: d6407c9e6fd54cb492b8c6635480d792
Searching for game ID for: A Short Hike
Found game ID: 2978157
No existing shortcut found for game A Short Hike. Creating new shortcut.
Downloading icons artwork...
Game ID: 2978157, API Key: 239745e39536fdc12bfa84ce0056b036
Sending request to: https://www.steamgriddb.com/api/v2/icons/game/2978157
Downloading image from: https://cdn2.steamgriddb.com/icon/75b4f712b9a4860516a726646282d56a/32/128x128.png
Traceback (most recent call last):
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 400, in <module>
    get_sgdb_art(game_id, unsigned_shortcut_id)
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 137, in get_sgdb_art
    download_artwork(game_id, api_key, art_type, app_id)
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 182, in download_artwork
    with open(file_path, 'wb') as file:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.steam/root/userdata/87418153/config/grid/4105637519-icon.ico'
```

**Comment by moraroy** [comment]
@curtisblackwell i added a small fix for you bro let me know how it goes and if  the scanner gets your games now...Press the StopScanner button and restart it and it will update

**Comment by curtisblackwell** [comment]
It worked, thanks!

This doesn't matter to me, but in case it's a bug and you wanna know about it: Boilr still shows the "Failed finding games" message for GOG and Mini Galaxy. I imagine this is the same Boilr issue you mentioned earlier, though.
