### ISSUE TITLE
NSL keeps adding the same apps over and over again

### ISSUE THREAD

**Issue by Athanaetos** [moraroy/NonSteamLaunchers-On-Steam-Deck#186]
Every single time I reboot my steam deck, there's a new Ubisoft Connect, EA app, and all the games I have installed get a new copy added to steam. Why does it keep adding the same games over and over again, is there a way to disable this or is this perhaps a bug? 

thanks

**Comment by Athanaetos** [comment]
things I have tried:

deleted the app, redownloaded it 
told it to clean install everything

**Comment by Athanaetos** [comment]
Ah I see, so I press stop scanner and I tell it to not turn on again? I don't know why I didn't think of that, but I'll try it. 
  
  I used the stop scanner, but immediately turned it on again in the prompt.  initially add all my games, but perhaps that was the wrong move.

Regardless, Ill give that a go.

**Comment by moraroy** [comment]
@Athanaetos my buttons kind of stuck right now, but in theory it should stop it, everything you open up the .desktop file the scanner gets set and is live. The button stops that and then closes the script. So as long as you don't need to open NSL it shouldn't bug you too much...what I would do for now is once the scanner is stopped just delete the duplicates and shortcuts and they won't come back, I'll try to fix why that's happening soon. I know it's annoying.

**Comment by Athanaetos** [comment]
From my limited testing, it seems to have stopped adding new entries via hitting stop. Reason why I worded my initial question like that was because I had a feeling it was user error, which is mostly true. Honestly deleting the extra entries and stopping the scanner is now working a lot better. So thank you for your help!

Before this I was manually adding game IDs to launch properties to add games, so this is a huge QOL alreay.

**Comment by moraroy** [comment]
@Athanaetos no worries yeah I think I may rename the scanner to Restart Scanner or something... I hope it's been a blessing to you, I know setting up the shortcuts can be hard sometimes on the deck especially with artwork. Hopefully it finds all your games so far, soo I'll be adding Amazon and battlenet games.

**Comment by moraroy** [comment]
@Athanaetos I added a small fix to see if the duplicates will stop, test the script again and see if they come back

**Comment by moraroy** [comment]
I belive this has been fixed actually with the latest changes, no more duplicates
