### ISSUE TITLE
"Path not found" error after attempting to reinstall EA App

### ISSUE THREAD

**Issue by AadilF1** [moraroy/NonSteamLaunchers-On-Steam-Deck#188]
The EA app has an annoying issue where it would say it needs to restart due to an update, but then turns itself off during the update and it'll prompt for a restart again. I installed the EA app through NSL, worked fine for a couple days, until there was an update. Now it no longer works. I pressed Uninstall > EA app through NSL, then tried to reinstall, but now getting the "path not found" error.

**Comment by moraroy** [comment]
@AadilF1 download the eap installer manually and when you run it under the same prefixxas your other ea app use the repair option

**Comment by moraroy** [comment]
@AadilF1 did you try to reinstall using the ea app you used just downloaded instead of repair?

**Comment by AadilF1** [comment]
I think it will be better if I can speak to you on discord (and provide my solution here once completed), if that's okay with you?

**Comment by moraroy** [comment]
Yeah man no problem add me @moraroy

**Comment by AadilF1** [comment]
> Hi, I'm having the exact same problem with EA App. I wonder if there is already a solution? :(

Yes there's a solution, you use the launch options that the EA app comes with when you install it via Nonsteamlaunchers, use that on the EA installer that you can download from the website.

**Comment by OrionM21** [comment]
Sorry I'm a little new to all of this. Do you have a tutorial or a list of steps? I would be very thankful.

**Comment by loftmess** [comment]
I was having the same issue, I uninstalled the EA launcher after it stopped working and reinstalling it gave me the "Path not found"-error. When I tried installing it with separate app IDs it didn't show up or launch at all. I was wondering how people with the same issue resolved it since I don't quite understand the instructions above?

**Comment by moraroy** [comment]
Don't Uninstall it with nonsteanlaunchers.. the issue is fixed here. https://www.reddit.com/r/SteamDeckBro/s/CBFU3t5KDr basically when you install it with NSL it's working up until an update causes it to break. This will fix it in desktop mode and game mode. @loftmess

**Comment by Spurlos** [comment]
Can we force the installer to run in repair mode during subsequent install\uninstall cycles? I got EA Desktop broken in my shared prefix and had to go thru the repair method to revive it. Uninstallation of EA Desktop NSL thru script doesn't helps to clear the leftovers to run install process smoothly.
