### ISSUE TITLE
Ea play games not added to non steam games

### ISSUE THREAD

**Issue by NoobLegend07** [moraroy/NonSteamLaunchers-On-Steam-Deck#189]
Egs n Ubisoft connect games work great...
But the ea play games I've been install not showing on my non steam games, how to fix it?
I try run find games on NSL the caption is the "path not pound".. any one know, how to fix it? Thx

**Comment by moraroy** [comment]
@NoobLegend07 where are younseeing this path not found?

**Comment by NoobLegend07** [comment]
On the Boilr sir, the launcher work great (ea play) I can download install n play the games, but the games not showing on the non steam games(gaming mode), to play the game must launch the launcher (eaplay)..

**Comment by NoobLegend07** [comment]
On other launcher (epic n Ubisoft) the games I've been install showing individually on non steam games n running great..

**Comment by NoobLegend07** [comment]
Still not showing sir, i try reinstall the launcher n games isn't work..

**Comment by NoobLegend07** [comment]
Is it because I installed the games on the sd card? But in epic games, i install the game on sd card, the games can showing on non steam launcher..

**Comment by moraroy** [comment]
@NoobLegend07 its possible its an sd card issue , do me a favor go to this location /home/deck/.config/systemd/user/NSLGameScanner.py, once there, right click the file and go to properties and set it as "executable" after that right click it again and "Run in Konsole" this will show the log of whatt the scanner is doing let me know what it says about your games.

**Comment by NoobLegend07** [comment]
Is it because I installed the games on the sd card? But in epic games, i install the game on sd card, the games can showing on non steam launcher..

**Comment by NoobLegend07** [comment]
config/systemd/user/Modules', '/home/deck/.config/systemd/user', '/usr/lib/python311.zip', '/usr
/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
Service started.
Existing Shortcuts:
AppID for None: -759952242
AppID for None: -1959902941
AppID for None: -1004328105
AppID for None: -74078271
AppID for None: -941784691
AppID for None: -1830382955
AppID for None: -1569776389
AppID for None: -1808215438
AppID for None: -631731821
AppID for None: -2123777455
AppID for None: -1428563610
AppID for None: -1074509734
AppID for None: -1714084594
AppID for None: -40990864
Existing shortcut found based on shortcut ID for game Control. Skipping.
Existing shortcut found based on shortcut ID for game Death Stranding. Skipping.
Existing shortcut found based on shortcut ID for game Assassin's Creed Odyssey. Skipping.
Existing shortcut found based on shortcut ID for game Assassin's Creed Mirage. Skipping.
One or more paths do not exist.
GOG Galaxy game data not found. Skipping GOG Galaxy Games Scanner.
One or more paths do not exist.
Battle.net game data not found. Skipping Battle.net Games Scanner.
Amazon GameInstallInfo.sqlite not found at /home/deck/.local/share/Steam/steamapps/compatdata//pfx/drive_c/use
rs/steamuser/AppData/Local/Amazon Games/Data/Games/Sql/GameInstallInfo.sqlite

**Comment by moraroy** [comment]
@NoobLegend07 not sure if its the sd card. but ill be taking a look at this issue

**Comment by nyakaspeter** [comment]
Hi, I had the same issue. I think the problem is that the scanner only checks the `drive_c/Program Files/EA Games/` directory inside the prefix for games. I fixed it by replacing the EA Games folder with a symlink that points to a folder on my SD card.

**Comment by NoobLegend07** [comment]
@nyakaspeter yeah bro.. i try with fresh start, and intall the game with default directory and now the game showing in the non steam games, but i have other issue now Ubisoft games won't showing on non steam games..

**Comment by NoobLegend07** [comment]
#update now all of my games I've been install on 3 launcher ubi,ea,epic can showing on non steam games, start fresh and run nslscanner multiple time..

**Comment by moraroy** [comment]
@NoobLegend07 has this been fixed for you?
