### ISSUE TITLE
Humble Collection Login Allow Access

### ISSUE THREAD

**Issue by bestpersonevar** [moraroy/NonSteamLaunchers-On-Steam-Deck#19]
Humble collection installs and launches perfectly. I click login and login and after login it says “allow access”. I click allow and nothing happens, on desktop mode. In game mode i get error code -302 after clicking allow access

**Comment by moraroy** [comment]
@bestpersonevar ive added an error message in 2.7 for the installtion of humble and legacy untill things are fixed, humble requires a weird workaround that im stilll trying to figure out how to fix
