### ISSUE TITLE
Games installed through Amazon and GOG not added as non Steam games in library

### ISSUE THREAD

**Issue by TheDumplingMan** [moraroy/NonSteamLaunchers-On-Steam-Deck#190]
Hi there, wrote you on reddit, now here's the issue tread. :)
I installed games from Amazon and GOG but they don't show up in the library as non Steam games. Only the launchers are added to Steam. Tried "start fresh" several times, also did some restarts and shut downs. Also tried the "find games" button, but Boilr doesn't find anything except flatpaks.
Here's the log as you requested. MadE a zip because the txt was too big for upload.
Edit: Haven't tried adding UPlay and EA App games yet.

[NonSteamLaunchers-install LOG.zip](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14168307/NonSteamLaunchers-install.LOG.zip)

**Comment by moraroy** [comment]
@TheDumplingMan try again for me this time I think I had to change the api let me know if it's still not working

**Comment by TheDumplingMan** [comment]
I stopped the scanner and restartet it now. But I still only see the launchers in Steam desktop and gaming mode, not the games.
I then "started fresh", deleted everything, redownloaded NSL and set everything up again. It is still only showing the launchers in Steam and not the games. Current logg added to this post.
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14179628/NonSteamLaunchers-install.log)

**Comment by natewaites** [comment]
With 3.7, I had to go into the settings and add the gog folder.  Once I did that, it says it does not find any games.  However, after restarting the deck, it started showing games in non-steam collection.  However, it would do some games correctly and others it would choose the uninstall exe.

**Comment by moraroy** [comment]
@natewaites what do you mean by change the setting? And what do you mean by uninstall.exe?

**Comment by natewaites** [comment]
I launched NonSteamLaunchers, selected "Find Games", went to settings.  Under settings, I checked import from Gog Galaxy and added my Gog Galaxy Folder:  /home/deck/.steam/steamapps/compatdata/GogGalaxyLauncher/pfx/drive_c/ProgramData/GOG.com/Galaxy/
I hit save.  Then went back to import games, closed it with x at the top.  Clicked Stop NSLGameScanner. Then I chose to run it again.  

It will add your installed Gog games after this.  It may take a while though.  I found that some would appear and then next time I restarted my deck more would appear.

When it detects dlc for a gog game, for instance the Binding of Isaac: Afterbirth +, the launch options end up finding the uinstall.exe for another game.  In this case, it chooses Timeshift\unins000.exe.

I hope this helps.

**Comment by moraroy** [comment]
@TheDumplingMan from your log it seems like your modules arent loading for some reason, so the game scanner isnt even running

**Comment by TheDumplingMan** [comment]
> @TheDumplingMan from your log it seems like your modules arent loading for some reason, so the game scanner isnt even running, ill look at the code and see why

Thank you man! :)

**Comment by moraroy** [comment]
@TheDumplingMan has this since been fixed for you as of today? i just added small fix

**Comment by TheDumplingMan** [comment]
> @TheDumplingMan has this since been fixed for you as of today? i just added small fix

Whatever it was you fixed, it works! :)
Tested it with Amazon, GOG, EA App and Ubisoft Connect after "starting fresh" again. :)
Thank you so much!
