### ISSUE TITLE
Games with DLC installed through GOG will show up multiple times in Non-Steam.  However, extras launch uninstallers for other games

### ISSUE THREAD

**Issue by natewaites** [moraroy/NonSteamLaunchers-On-Steam-Deck#191]
For example I own Dead Cells and multiple DLCs.  Dead Cells shows up and opens properly.  However, there are 4 other entries for Dead cells under Non-Steam.  When you look at the Launch Options, it shows a random gog game uninstall.exe instead of the dead cells exe.

**Comment by moraroy** [comment]
@natewaites yeah that's helpful, thank you.. I'm going to actually remove Boilr now from the whole script

**Comment by moraroy** [comment]
@natewaites let me know if that helped first click the "Stop Scanner" and dont restart it. Then delete your shortcuts that you dont need/want. And then open up the .desktop file and click on "Stop Scanner" again, and this time restart it and let me know what happens.

**Comment by natewaites** [comment]
It is still saying version 3.8.  After following the instructions, it still is adding random uninstallers/games to dlc entries.  For example Dead Cells - Rise of the Giant is linking to the SOR4.exe

**Comment by moraroy** [comment]
@natewaites I see, ok for now just use the stop Scanner button, and then don't restart the scanner. I'll keep looking into fixing it better and making it more robust

**Comment by moraroy** [comment]
@natewaites this has just been fixed
