### ISSUE TITLE
Can't install Epic launcher

### ISSUE THREAD

**Issue by jlht01** [moraroy/NonSteamLaunchers-On-Steam-Deck#194]
Hello!  I'm having the same issue I noticed another user had recently. I can install all the other launchers I need, but Epic isn't working. I'm not Linux proficient, so I genuinely don't know what to provide you to show the problem. Epic appears to install, switches to Steam, and then Epic is not in the library at all.

**Comment by MrHSito** [comment]
Hi! Same problem with Ubisoft Connect: it appears to install, close Steam and reopen again, switches to Steam, and then Ubi is not in the library at all.

**Comment by Shajbuss** [comment]
I have the same problem! Please help

**Comment by moraroy** [comment]
@jlht01 @MrHSito @Svartkeiser Install Proton Up QT from the Discovery Store, from there delete the Proton GE's that you have and Reinstall the latest Proton GE, if you dont want to do that, you can go here manually and delete any Proton GE folders you have, its possible the proton got corrupted somehow /home/deck/.steam/root/compatibilitytools.d/ Once you ve done that i would then install Proton GE through Proton UP QT and then use NonSteamLaunchers to ensure there is no corruption.

**Comment by Svartkeiser** [comment]
@moraroy Not working :( Still the same issue
