### ISSUE TITLE
No launchers seem to be installing

### ISSUE THREAD

**Issue by blaeeeeek** [moraroy/NonSteamLaunchers-On-Steam-Deck#203]
This should be hard to mess up, right? Launched desktop file, from desktop. Selected rockstar social club, ps plus and ubisoft connect. Click 'Ok'. I see a progress bar of things downloading and then i see steam restart. Nothing new appears in non-steam games. Tried this about 4 times, even just rockstar by itself, no dice. (dear god why is it so impossible to install non-steam games to SD cards kill me)

**Comment by moraroy** [comment]
@blaeeeeek alot of Code was moved around this past week, try to use the .sh file from 3.7

**Comment by krissag95** [comment]
I had the same problem and removed Firefox explorer from the system and installed Chromium. After that the launchers were installed and appeared in Steam.

**Comment by Taemobato** [comment]
Hi. I's not launching for me either. attaching my log. i can't find it in the steam library
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14391756/NonSteamLaunchers-install.log)

**Comment by gitscosh** [comment]
> I had the same problem and removed Firefox explorer from the system and installed Chromium. After that the launchers were installed and appeared in Steam.

DId you install Chrome or Chromium? Would Brave or Ungoogled Chromium serve the same purpose?

**Comment by moraroy** [comment]
@gitscosh for some reason the logic of the code of the Google Chrome installation in the nsl script is blocking the installation of the launchers, it shouldn't be that way I still need to fix this

**Comment by gitscosh** [comment]
> @gitscosh for some reason the logic of the code of the Google Chrome installation in the nsl script is blocking the installation of the launchers, it shouldn't be that way I still need to fix this

Ok. The Battlenet launcher install worked just fine, but I can't get the GOG Galaxy or Xbox installs to work properly. No entries in Steam. I'll wait for an update.

**Comment by moraroy** [comment]
@gitscosh send your log that could be a number if reasons

**Comment by gitscosh** [comment]
> @gitscosh send your log that could be a number if reasons

Sure thing. On the Steamdeck, which log do you want? Just the main one in the top level folder? Do you wanted it pasted here?

**Comment by moraroy** [comment]
@gitscosh upload the nsl log in the downloads folders

**Comment by gitscosh** [comment]
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/15180846/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@gitscosh still waiting for all the fixes and approval on the decky team

**Comment by gitscosh** [comment]
This is now resolved as of today (3.8.7 was released today), but I had to start from scratch and clean out the old stuff, and I used the Deck Plugin. Now all I have to do is figure out how to get the mouse to work in GOG Galaxy... or find another way to navigate. Any ideas?

**Comment by moraroy** [comment]
@gitscosh let's goooo baby!! I'm glad it's working ... NSL used to supply three controller configuration, and we still do but it's in the process of rewriting, so for now just use a template in the controller setting called Web Browser that's what I use for the launchers. It works very good.
