### ISSUE TITLE
heroic laucher shows GOG games but not Epic games

### ISSUE THREAD

**Issue by mrhardees** [moraroy/NonSteamLaunchers-On-Steam-Deck#205]

**Comment by mrhardees** [comment]
No steps on what to make the launcher work.

**Comment by moraroy** [comment]
@mrhardees I don't understand what you're saying or asking, this isn't heroic?

**Comment by mrhardees** [comment]
It is Mr Roy the Heroric launcher only shows a small part of Epic games and the rest is greyed out. I have all my Epic games in one place.

**Comment by moraroy** [comment]
@mrhardees this is nonsteamlaunchers not heroic brother
