### ISSUE TITLE
Star Wars Jedi Survivor causing full system crash

### ISSUE THREAD

**Issue by Alfamari** [moraroy/NonSteamLaunchers-On-Steam-Deck#213]
I have star wars jedi survivor through epic games which then needs to connect to the EA app to authenticate and run properly. But when it runs, it starts kind of working but at incredibly low frames while the logos play, and then inevitably causes the entire steam deck to freeze until I force the system to turn off by holding the power button down.

I admit I don't know if this is really at all related to this program, I only bring it up because I can't get it to work otherwise on the steamdeck without your program or without installing windows since I don't have the steam version and my other games from epic work very well when they don't need to cross authenticate with EA.

I thought maybe the fact it needs to cross authenticate may somehow have been a point of failure from this program's end that may not have been an anticipated use, maybe its a performance optimization issue with trying to force it to work non-natively on linux or maybe there's some settings I need to adjust, I really don't know.

If this has nothing to do with anything on your end, just feel free to close this issue, I understand not everything is in your control. And I want to thank you for this tool that has been able to achieve things that I could not have otherwise achieved with heroic launcher or lutris.

**Comment by moraroy** [comment]
@Alfamari couple questions, are you saying that you have that game through Epic or EA App, if it's EA App you might as well just install through there that way you're not opening up 2 launchers. However, if you want to stay with using Epic, I would suggest you install the EA APP inside the same prefix folder as the Epic Games Launcher, what this means in regards to NSL is I'm assuming you didn't click on separate app ids for installing Epic Games Launchers, so all you would simply do is open NSL and install EA App, once steam restarts sign in to the EA App, and then close it? Epic Games will now use that EA App to authenticate theoretically.

**Comment by Alfamari** [comment]
@moraroy I own the game through epic, but it really just uses the EA app to actually manage the game via downloads and updates and execution. So if I run the game from epic it then loads up EA, but if I run the game from EA it also loads up Epic (since that's what I own it from). I don't really care how I run it, but either way seems to require both launchers.

I didn't click on separate app ids, currently I have Epic Games in 'Program Files (x86)' and EA App in 'Program Files' both under pfx/drive_c. Are you saying to put them under the same Program Files folder? If so, is there a nice way to move them without reinstalling (it's like a 130gb+ game), maybe symbolic links? If not, so be it. I kept all the downloads default cuz I don't understand enough about setting up these windows environments on linux to move the folder paths around to organize them and mess with them. Especially with the additional moving parts of NSL and steam.

Nevertheless, thank you for the quick response and trying to help, I appreciate it.

**Comment by moraroy** [comment]
@Alfamari no I'm saying just install the EA App like you did with the Epic Games Launcher. Then sign in to the new EA APP

**Comment by Alfamari** [comment]
@moraroy Well, I have already done that then. Both installed and logged in and then I went into game mode and ran from both launchers and the individual tile for the game itself. Everything works cleanly at first and boots up the opposite launcher as necessary, both launchers minimize properly, game runs, low frames, steam deck fan intensifies, freeze.

**Comment by moraroy** [comment]
@Alfamari hmm interesting, are you using proton ge or expirmental?

**Comment by Alfamari** [comment]
@moraroy I'm using experimental as that's what was recommended in both of the youtube guides I watched for this project.

**Comment by moraroy** [comment]
@Alfamari switch to proton ge and let me know if it crashes on you bro

**Comment by Alfamari** [comment]
@moraroy So as I went to change the compatibility, everything had reverted back to GE. I tried it, it got to "optimizing game cache", freeze. I'm going to try again with the experimental again because that seems to have a hard time sticking and keeps getting reverted, and then I'll give it a try in Desktop mode both in and out of big picture just to see.

**Comment by moraroy** [comment]
@Alfamari to be honest with you....  I don't have that game personally. But here is my rule of thumb and my personal recommendation for the Steam Deck. I have the 64GB, I have always used Cryoutilities to set a 16GB page file( you don't need that much) I just did the max I could and on top of that. Went into the bios and gave that extra 4GB of VRAM. I have always used Proton GE and 90% of the time it works with no issues. Sometimes I've had to use experimental or other protons. It's very possible there is just not enough ram being used so maybe try cryoutlities. Don't listen to any fear mongering on YouTube or Reddit, it's your deck and most of the tools you experiment with can be reversed so they are safe.

**Comment by Alfamari** [comment]
@moraroy Alright, I will try out cryoutilities and the VRAM changes, thank you for those tips.

Again, thank you for your rapid responses and this awesome tool. I had conceded to installing windows but ultimately ended up doing nothing cause I didn't want to go through the headache of it all. So I was barely using my steamdeck and using it very minimally when I did as most of my games are on Epic. Your project has gotten me interested in using it again. And even if I can't get this one game to work I'm already getting other games I previously couldn't to work now. You're awesome!

**Comment by Alfamari** [comment]
@moraroy The cryoutilities and VRAM changes worked! Everything works! Thank you so much!

**Comment by moraroy** [comment]
@Alfamari no problem bro I'm glad that worked for you!!! Happy gaming! Sorry it wasn't working before!

**Comment by Alfamari** [comment]
@moraroy Seems like it had nothing to do with your tool anyways, so nothing to be sorry for. You saved me the huge headache of having to install windows and gave me access to all of my other games and breathed new life into my steamdeck. And took the time to help me fix an issue that was unrelated, you really went above and beyond for me. All in under 2 hours. I really, really appreciate it! I'm absolutely leaving a star on this project! I'll also be leaving positive reviews on youtube and recommending it to others. Again, thank you so much!

**Comment by moraroy** [comment]
@Alfamari no worries bro! I'm glad I could help! If you use Decky Loader, Be sure to get the NonSteamLaunchers Decky Version in the testing store.
