### ISSUE TITLE
Minecraft Launcher will reappear in Steam after a reboot

### ISSUE THREAD

**Issue by Brandon98SE** [moraroy/NonSteamLaunchers-On-Steam-Deck#219]
I have uninstalled Minecraft launcher through the script and it keeps getting re-added to steam after rebooting or logging off and back on.

**Comment by moraroy** [comment]
@Brandon98SE sorry about that in the next update I will be removing mine craft all together as there is a better flat pack in the discovery store.

**Comment by Brandon98SE** [comment]
@moraroy No problem!
I normally use Prism Launcher for Minecraft on Linux anyway! :D

Also no need to apologise, this is a Free and Open Source project and I have absolutely zero expectations, I appreciate and respect what you're doing and I thank you for creating and maintaining this! ❤️

**Comment by moraroy** [comment]
@Brandon98SE I added a fix for this let me know if it works, just need you to run the script again and "Uninstall Minecraft" again. Let me know what happens.

**Comment by Brandon98SE** [comment]
@moraroy It worked perfectly! 
Thank You, I really appreciate you doing this!
♥️ :3

**Comment by moraroy** [comment]
<3
