### ISSUE TITLE
Little Question

### ISSUE THREAD

**Issue by PabuGithub** [moraroy/NonSteamLaunchers-On-Steam-Deck#228]
Hi moraroy,
How do u got epic games working? Epic Games work fine while the tool is installed, but if I press start fresh (even if I renamed the Proton prefix or copied it where Epic is installed) it crashes if you try to start it. Would be nice if you could explain that to me.

**Comment by moraroy** [comment]
@PabuGithub why did you press start fresh? it deletes everything, there is no "tool Installed"

**Comment by PabuGithub** [comment]
@moraroy Sorry for the late response . My problem is that when I run the script, some of my blanket plugins no longer work properly. I have no idea why that is. That’s why I have manually installed only the launchers I need, Rockstar and Epic Games, using the method for Steam unknown games. Rockstar Games Launcher worked, but the Epic Games launcher no longer works after the update screen. If I Use you’re Tool for the Epic Games Lounge der is the Problem so how do you prevented it?

**Comment by PabuGithub** [comment]
@moraroy Please

**Comment by PabuGithub** [comment]
@moraroy maybe it's something else I reinstalled steam OS. But that wasn't my question. How do you got epic up on running???

**Comment by moraroy** [comment]
@moraroy you select Epic games and hit install and restart steam

**Comment by PabuGithub** [comment]
@moraroy  No, without the tool

**Comment by moraroy** [comment]
@PabuGithub download the Epic game installer fromt he website and add it as a non Steam game, then run it with whatever proton you want in Steam from there install Epic, then go into that same shortcut you just made and change the Start In and Target and Launch Otpions to correctly match the directory path paths associated with your newly created prefix and paste them into the shortcut properties, from there you need to add the Compat data command in the launch options associated with your prefix. Then you'll be able to launch Epic games, this is all done for you by using the tool.
