### ISSUE TITLE
Image download suggestion

### ISSUE THREAD

**Issue by hgdagon** [moraroy/NonSteamLaunchers-On-Steam-Deck#23]
I just found out about this. This is exactly what I've been waiting for for months now. Thank you so much! 

Now, I've been using Heroic Launcher for my non-Steam games. A tool that came in handy was Boilr. It's available in the Discover Store. It can edit images for native Steam games as well, but I found it very useful for any non-Steam games I have. After the game is added to the Steam library, all you need is your SteamGridDB API key.

Hope this helps.

**Comment by moraroy** [comment]
@hgdagon heck yeah brother that's definitely on my radar to add. I'm still trying to figure out the best way to do it! But thank you for the suggestion that really helps!
