### ISSUE TITLE
Removed Epic and EA launchers still keep showing up

### ISSUE THREAD

**Issue by slimshader** [moraroy/NonSteamLaunchers-On-Steam-Deck#235]
after uninstalling Epic and EA launchers, I manually removed entries in Steam as they were not removed automatically but they keep showing up again and starting then does nothing (as Launchers no longer are there)

**Comment by moraroy** [comment]
@slimshader use the stop Scanner button. I will  be rewriting how uninstall works in the future.

**Comment by slimshader** [comment]
Problem is I do want it to work for when I am installing and uninstalling games. I guess I will just wait for a fix for now then.

**Comment by moraroy** [comment]
@slimshader keeps your eyes peeled o. The Decky Plugin, very soon an update will fix exactly what you are having problems with.

**Comment by moraroy** [comment]
@slimshader hey I attempted a small fix for you, here's what I need you to do, open up NSL using the .desktop file and simply hit the uninstall button again and uninstall your launchers that you wanted. Then let me know if that fixes your shortcuts from popping up again. You should be able to now add new games without the launchers coming back.

**Comment by slimshader** [comment]
Downloaded new NSL and when trying to re-install EA installer with it I am getting error "path not found"
