### ISSUE TITLE
Battle.net launcher installation error

### ISSUE THREAD

**Issue by carmine19** [moraroy/NonSteamLaunchers-On-Steam-Deck#237]
Hi, I wanted to report this problem that I encounter on Steam Deck Oled with firmware dated March 7, 2024, when I try to install Battle.net Launcher it reaches 45% of installation and stops opening the blizzard popup to report the error.

Things I tried:
-clean installation from scratch then restore and install only the battle.net
-installation with separate ids for the prefixes
-version 3.8 and 3.8.1

**Comment by moraroy** [comment]
@carmine19 weird. Do you have enough space on your hard drive?

**Comment by carmine19** [comment]
of course, I did the process starting from a factory reset as I had previously installed various launchers but none of them opened anymore, they were Gog, Amazon, Battle.net and Epic, so I decided to do a factory reset and even before installing the games I tried to install the launchers but on Battle.net the process stopped at 45% with a blizzard client error.

**Comment by cnietoc** [comment]
I had the same problem, but when I retry it (without do a fresh install or anything) it works

**Comment by JFERSD** [comment]
It happens to me too with firmware dated March 7, 2024 :S at 45% crashes :S

**Comment by carmine19** [comment]
I have also tried resetting the deck several times but it always stops at 45%.

**Comment by moraroy** [comment]
@carmine19 @JFERSD please do as @cnietoc suggested it works on the second try

**Comment by carmine19** [comment]
I tried and it installed it but the client doesn't start. I tried various versions of Proton (the default was 9.01), I also tried rebooting but the client doesn't start.

**Comment by moraroy** [comment]
@carmine19 @cnietoc @JFERSD i just pushed a temp fix for battle net let me know how it goes

**Comment by carmine19** [comment]
I did a couple of tests and I'll give you some feedback:

I started by uninstalling all the clients by doing a fresh start, I saw that amazon games was installed with the path but not battle.net, I did a fresh start, stopped and restarted the search service to see if there was an update , I manually removed the connection symlinks from Steam (the program did not remove them) and every time the download started it was unable to download the data, I restarted a few times, opened and closed Steam, always did the complete cleaning again and then it started a little, the error always came out but it continued with the installation, it installed correctly and it even started, so the fix worked.

**Comment by JFERSD** [comment]
It worked, somehow Battle.net installation crashed during installation but it was installed anyway and I was able to install and run games. 

Thank you so much!
