### ISSUE TITLE
Battle.net download issue

### ISSUE THREAD

**Issue by philo23** [moraroy/NonSteamLaunchers-On-Steam-Deck#24]
When I try to install Battle.net through this it always fails on the "Updating Battle.net Update Agent" step, and then seems to get stuck in a loop waiting for the installer to finish. Any ideas what could be causing it?

![Screenshot_20230520_151820](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/171550/89986760-5ee0-49eb-9b86-2bb1888aa0ea)
![Screenshot_20230520_151844](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/171550/1c02d863-6c7a-47b1-baae-de1bd93bad90)
![Screenshot_20230520_151937](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/171550/9fcd58fe-8e56-4542-91ac-d15918b81f3b)
![Screenshot_20230520_151958](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/171550/45ee8886-5153-45df-aa92-c3fb0807eaf7)
![Screenshot_20230520_152011](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/171550/d1527cd7-a4e2-429a-b58d-5a2046b8e4a0)

**Comment by adam-fox** [comment]
Having the same problem. Any chance you were able to troubleshoot this @philo23?

**Comment by philo23** [comment]
No luck I'm afraid. I ended up manually installing Battle.net.

Basic steps from memory:

- Add the installer `
Battle.net-Setup.exe
` as a non steam game from desktop mode
- Then go into the new shortcuts' properties and switch the Compatibility to the latest version of GE-Proton (you might need to figure out how to install this if you've not already got it)
- Launch the installer through Steam, go through install (it should just work) and then login. 
- Quit Battle.net from Battle.net's top left menu (ignore any updates)
- Go back into Properties and change the shortcut you added for the installer to point to the `Battle.net Launcher.exe` you just installed, it'll be under `/home/deck/.steam/steam/steamapps/compatdata/<uniqueid>/pfx/drive_c/Program Files (x86)/Battle.net` (**don't** add a new shortcut, update the existing one)
- Make sure you change the "Start in" path to the same folder too, and change the name to `Battle.net` or something sensible.

At this point you should be able launch Battle.net from Steam, update it (if it needs to be updated) install whatever game you want, then switch back to Gaming Mode and you'll be able to launch Battle.net there too, and through it launch any games you installed on Battle.net.

You'll probably want to go into Battle.net settings and disable "Run at start up" and set it to exit Battle.net on game launch so it's not running in the background once you open the game.

Also it should be possible to move the install to your SD card, but I've not looked into and it's probably a lot more fiddly to setup, so I didn't bother.

**Comment by moraroy** [comment]
@Silviyius could you send a log?

**Comment by joesyuh** [comment]
I am having the exact same issue. Epic Games installer works just fine, but battle.net won't run. I am a steam deck novice and still figuring out how to grab this log for you.

**Comment by Silviyius** [comment]
![image](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/7122428/28c8f324-afbb-4807-a8b4-8fd05b1d9b83)
Is there a location logs are kept?

**Comment by Silviyius** [comment]
still having issues on 2.89. even did a fresh start.

**Comment by moraroy** [comment]
@Silviyius what the heck that's weird... ok... I think I need to rework the prton ge code to do multiple checks and make sure it doesn't error out during that part... also... I've never seen or heard of these kinds of proton ge so that's interesting. Dang I'm sorry you had to do a factory reset that shouldn't have been needed tbh

**Comment by Silviyius** [comment]
@moraroy you made a free tool that makes my life easier. Your not responsible for the bs I install. lol. But yeah more layer 0 checks would probably help.

**Comment by moraroy** [comment]
@adam-fox I just updated the .sh file to use a different url and file
