### ISSUE TITLE
Launchers are not adding to Steam Library

### ISSUE THREAD

**Issue by imsofresh54** [moraroy/NonSteamLaunchers-On-Steam-Deck#256]
After running script, EA Play is launching, but shortcut is not added to Steam Library. 

Tryed doing restart, disabling NSL, separating APP IDs, using decky loader plugin. Nothing helps.

**Comment by moraroy** [comment]
@imsofresh54 are you installing to the sd card?

**Comment by imsofresh54** [comment]
> @imsofresh54 are you installing to the sd card?

Nope, on internal SSD

**Comment by moldof97** [comment]
Hi, I hope this might be of help, I was tweaking a bit and when doing a fresh start after a while I encountered the same problem, tried reinstalling again and again but with no result. I read some old closed issues where it said it might fix doing a **_log out from the steam account and closing the application then restarting the device and logging in again_**. tried that, reinstalled NSL and the launchers were added in the library

**Comment by imsofresh54** [comment]
> Hi, I hope this might be of help, I was tweaking a bit and when doing a fresh start after a while I encountered the same problem, tried reinstalling again and again but with no result. I read some old closed issues where it said it might fix doing a **_log out from the steam account and closing the application then restarting the device and logging in again_**. tried that, reinstalled NSL and the launchers were added in the library

Thank you for answer, but no luck for me. 😢

**Comment by imsofresh54** [comment]
I found what was an issue. 
After fresh install of Steam OS, and installing NSL, nothing seems to work. But later i entered gaming mode, and in non-steam section i was promted to download Google Chrome. After i done this, and restarting NSL, launchers appeared in library.

**Comment by moraroy** [comment]
@imsofresh54 interesting ok.. will take a look at the logic @moldof97

**Comment by rafal-zelek** [comment]
I had the same issue on my fresh steamOS.
Adding chrome like guy above said fixed the issue.

**Comment by theimpulson** [comment]
Just had the same issue. Installing Chrome first and restarting NSL afterwards fixed it.

**Comment by cgiraldo** [comment]
I also hit this in a fresh steamOS install. The error in log is:
```
['/home/deck/Downloads/NonSteamLaunchersInstallation/lib/python3.11/site-packages', '/home/deck/.config/systemd/user/Modules', '/home/deck/.config/systemd/user/Modules', '/home/deck/.config/systemd/user', '/home/deck/Downloads/NonSteamLaunchersInstallation/lib/python3.11/site-packages', '/home/deck', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
Traceback (most recent call last):
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 406, in <module>
    create_new_entry(os.environ.get('epicshortcutdirectory'), 'Epic Games', os.environ.get('epiclaunchoptions'), os.environ.get('epicstartingdir'))
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 366, in create_new_entry
    if check_if_shortcut_exists(signed_shortcut_id, appname, exe_path, startingdir, launchoptions):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 324, in check_if_shortcut_exists
    if any(s.get('appid') == shortcut_id for s in shortcuts['shortcuts'].values()):
```

NSLGameScanner.py does not check for an empty shortcuts.vdf file. As @imsofresh54 did with Chrome, a workaroung is to add any non-steam product before running the script (I just add "Ark" as non-steam app).

**Comment by moraroy** [comment]
@cgiraldo dang ok thank you for providing the error log that explains alot, unfortunately I can't put in a fix just yet as I have irl things going on. I'll try to apply a fix perhaps this weekend.

**Comment by ckhan101** [comment]
yep same here - got new steam deck last week and had same issue as @cgiraldo with nothing being added to steam and random behaviour (some launchers opening in desktop, most not).  I will strart fresh after installing chrome to see if that works..!!

**Comment by Jusecace** [comment]
> I found what was an issue. After fresh install of Steam OS, and installing NSL, nothing seems to work. But later i entered gaming mode, and in non-steam section i was promted to download Google Chrome. After i done this, and restarting NSL, launchers appeared in library.


Edit:

I had the same problem and doing the above process made it work.

**Comment by moraroy** [comment]
@Jusecace this has been fixed just now using the Desktop Version of NonSteamLaunchers. i will be adding this fix to the plugin version as well.
