### ISSUE TITLE
Problem with Epic Games

### ISSUE THREAD

**Issue by revaldozen** [moraroy/NonSteamLaunchers-On-Steam-Deck#257]
Problem with Epic Games.
when I started the launcher:
The Epic Games Logo is Showed then Blank Windows Screen
![image](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/7719900/1c8c8c10-0d52-44e3-8333-0fd849902920)

I've tried from this issue #145 :
1. Add '-force-opengl' to target
2. Add '-screen-width 1280 -screen-height 800 -screen-fullscreen 1'

Nothing Works 

Thank You

**Comment by moraroy** [comment]
@revaldozen does it open correctly in desktop mode?

**Comment by moraroy** [comment]
@revaldozen yes it should from there it would create a game shortcut,  and you wouldn't need to access the epic games launcher

**Comment by revaldozen** [comment]
> @revaldozen yes it should from there it would create a game shortcut,  and you wouldn't need to access the epic games launcher

I've tried it and the game don't show up in steam library. When we launch epic from steam game the game we've played automatically added to non steam game library

**Comment by BigCheems** [comment]
I am having the same exact issue it is strange as everything was working fine before but now as of this morning I get the same little black screen when opening up the epic games store.

**Comment by moraroy** [comment]
@BigCheems if it was working before most likely an epic games issue, I only have the lcd steam deck so I can't test too much further but can say as of yesterday it was working normally. I don't have my deck with me so I can't test.

**Comment by BigCheems** [comment]
I still have my LCD deck I'll put this on there and see if its an oled
issue or not

**Comment by moraroy** [comment]
@BigCheems but epic is working on my lcd just tested right now :/

**Comment by BigCheems** [comment]
I'll do a reboot and get mine all updated then probably my fault as I havent touched this since the OLED came out haha

**Comment by BigCheems** [comment]
@moraroy  Went through it did clean install now its not even showing up in the non steam games section, strange I know its installed as I see it in the folders and all but steam just doesn't "see" it

**Comment by BigCheems** [comment]
@moraroy So I managed to figure out the issue and this may solve it for @revaldozen also. Essentially the problem is GE Proton that is currently programmed with this being GE-Proton9-2 does not work with the Epic games store currently as when I switch it to proton 8.0-5 it boots up just fine as if I dont have an issue at all. The only issue being that the program always wants to default to that newer proton instead of this one so I have to constantly go and restart the compatibility settings to force it back to that. Another quirks with it though being I have to change my controller settings each time to let me be able to use the "mouse" again. But I can confirm this has figured it out as now I can get it working again.

**Comment by moraroy** [comment]
@BigCheems thats very strange, only because...i recently reimaged my steam deck, and put NSL on it. it only added the latest Proton GE which would have been Proton GE 9-2. thats the one im currently using on a fresh lcd deck and its working fine. im going to remove the controller configuration code because its causing alot of problems, this controller configuration code will be added to the plugin version instead.

**Comment by BigCheems** [comment]
@moraroy Yeah it is weird and sort of a shot in the dark for me to try and do the compatibility mode to roll back a proton and now it works, I just have to make sure it runs that one instead every time like I said.

**Comment by moraroy** [comment]
@BigCheems also, just to point out, the reason NSL uses the latest Proton GE is because it usuallly has the latest most up to date fixes, logically, i figured that most people arent going to continually re-install the launchers, haha obv thats not the case cuz some launchers break, so... i think once you install the launchers succesfully, then i would use Proton Up QT from the discover store to install other "protons" without touch the NSL installer again because once its run, it will delete the pther proton GE's. the NSL script only keeps the latest and greatest version. It doesnt touch any other protons in that folder if that makese sense.

**Comment by EdoTarani** [comment]
I'm having the exact same issue with Epic Launcher. Using proton 8.0.5 does not fix the issue for me. Steam Deck Oled.

**Comment by willsonho2000** [comment]
I got the same issue on SD OLED. However, the normal panel will flash past at the moment I exit the application.

By the way, does anyone know how to install GTA5 through Epic Games? The rockstar games launcher doesn't support Windows 7 or less anymore. The error message will pop out when I launch the game in SD.

**Comment by willsonho2000** [comment]
> I got the same issue on SD OLED. However, the normal panel will flash past at the moment I exit the application.
> 
> By the way, does anyone know how to install GTA5 through Epic Games? The rockstar games launcher doesn't support Windows 7 or less anymore. The error message will pop out when I launch the game in SD.

Sorry, the '-opengl' command in the end of the TARGET works for me.

**Comment by revaldozen** [comment]
> @moraroy So I managed to figure out the issue and this may solve it for @revaldozen also. Essentially the problem is GE Proton that is currently programmed with this being GE-Proton9-2 does not work with the Epic games store currently as when I switch it to proton 8.0-5 it boots up just fine as if I dont have an issue at all. The only issue being that the program always wants to default to that newer proton instead of this one so I have to constantly go and restart the compatibility settings to force it back to that. Another quirks with it though being I have to change my controller settings each time to let me be able to use the "mouse" again. But I can confirm this has figured it out as now I can get it working again.

Thanks for the solution. The problem solved by changing the GE-Proton9-2 to proton 8.0-5.  I have one more question, when I install Sifu in the epic game then played the game, the shortcut for Sifu was created in Non Steam Games. When the epic launcher error, I was Installed Hitman on Desktop Mode. then I play via steam launcher, the shortcut was not created. how to make shortcut for a game?

**Comment by revaldozen** [comment]
> I'm having the exact same issue with Epic Launcher. Using proton 8.0.5 does not fix the issue for me. Steam Deck Oled.

have you add the '-opengl' command in the end of the TARGET?

**Comment by RealKyllin** [comment]
> @BigCheems also, just to point out, the reason NSL uses the latest Proton GE is because it usuallly has the latest most up to date fixes, logically, i figured that most people arent going to continually re-install the launchers, haha obv thats not the case cuz some launchers break, so... i think once you install the launchers succesfully, then i would use Proton Up QT from the discover store to install other "protons" without touch the NSL installer again because once its run, it will delete the pther proton GE's. the NSL script only keeps the latest and greatest version. It doesnt touch any other protons in that folder if that makese sense. it only detles the other proton GE's once you choose to install a launcher btw

@moraroy
Hello.  If I change the proton to 8.0-5 under compatibility for the epic games store then it works again (as others have stated).  But, if I exit and restart my steam deck for whatever reason and then launch the epic store again, it goes back to the non working 9 version.  How is that happening?  When I launch the epic store from the icon your program created does it run a script calling for the latest proton and overwrite the one from Proton up QT I told it to use previously?  My understanding was that it just installs the latest proton initially when you use the nsl to set everything up, not every time you actually just want to enter the epic store and play the games.  Thanks.

**Comment by moraroy** [comment]
@RealKyllin it shouldn't the doing that :/ but the scanner is doing that yeah

**Comment by RealKyllin** [comment]
> @RealKyllin it shouldn't the doing that :/ but the scanner is doing that yeah

@moraroy I'm completely confused.. oh well, it was fun while it lasted. Thanks.

**Comment by RealKyllin** [comment]
@moraroy How do I stop the scanner?

**Comment by moraroy** [comment]
If you're using the decky plugin you can select Stop Scanner. If you're using the desktop file you can select "Stop Scanner" and then follow the prompts to turn it off and leave it off or restart it.

**Comment by RealKyllin** [comment]
@moraroy Oh ok.  I thought the NSL just set everything up and that was the end of it.  I didn't realize it was always running.  I'll give it a shot.  Perhaps the fun will last after all.  Thanks.

**Comment by revaldozen** [comment]
hi @moraroy , how about my question adding shortcut for the installed game from epic on steam launcher? is it possible?

**Comment by moraroy** [comment]
@revaldozen not sure, it should be working would need to see your log

**Comment by revaldozen** [comment]
I think we can closed this @moraroy 
Thanks for the solution from @BigCheems 

> @moraroy So I managed to figure out the issue and this may solve it for @revaldozen also. Essentially the problem is GE Proton that is currently programmed with this being GE-Proton9-2 does not work with the Epic games store currently as when I switch it to proton 8.0-5 it boots up just fine as if I dont have an issue at all. The only issue being that the program always wants to default to that newer proton instead of this one so I have to constantly go and restart the compatibility settings to force it back to that. Another quirks with it though being I have to change my controller settings each time to let me be able to use the "mouse" again. But I can confirm this has figured it out as now I can get it working again.

**Comment by revaldozen** [comment]
The Solution 

> @moraroy So I managed to figure out the issue and this may solve it for @revaldozen also. Essentially the problem is GE Proton that is currently programmed with this being GE-Proton9-2 does not work with the Epic games store currently as when I switch it to proton 8.0-5 it boots up just fine as if I dont have an issue at all. The only issue being that the program always wants to default to that newer proton instead of this one so I have to constantly go and restart the compatibility settings to force it back to that. Another quirks with it though being I have to change my controller settings each time to let me be able to use the "mouse" again. But I can confirm this has figured it out as now I can get it working again.
