### ISSUE TITLE
Battlenet install failing with blizzard error

### ISSUE THREAD

**Issue by M3rl1nnn** [moraroy/NonSteamLaunchers-On-Steam-Deck#258]
Battlenet installation failing mid install with a blizzard error code.

**Comment by moraroy** [comment]
@M3rl1nnn did you close the window and let it install?

**Comment by jaco9613** [comment]
first, I got same problem too. Always install in 45%, It will appear an error message. But still can install and log in to battle.net. 
Steam deck lib doesn't show the app.

second, I install Youtube, Netflix or EA, they doesn't show in the lib

**Comment by jaco9613** [comment]
Install Battle net and EA app success when I enable developer mode. But Youtube and Netflix still can not work.

**Comment by moraroy** [comment]
@jaco9613 what is developer mode?

**Comment by jaco9613** [comment]
@moraroy It's under Settings -> System SETTINGS --> Enable Developer Mode.
This is for software developer use.

**Comment by moraroy** [comment]
@jaco9613 oh OK gotcha... well I'm not on developer's and nsl works fine for me. Can you show in your log what are the changes or permissions that are different in developer mode?

**Comment by jaco9613** [comment]
[Uploading NonSteamLaunchers-install.zip…]()

**Comment by lfilho** [comment]
Hi @moraroy thanks for this awesome project. Same error here. Error says "The application encountered an unexpected error" and you're offered to send detaild do Blizzard, also with Dev mode enabled. I had other launchers selected during install time and non appear on the Non-steam tab.

Started the installation again (not afresh, just ran the installer again, selected the same launchers, clicked next). No errors this time but still nothing on the non-steam tab. Restarted the deck just in case, no dice.

Then tried again but with the option to install afresh, same error. And nothing on the non-steam tab.

**Comment by lfilho** [comment]
Here's the log file. I do see some errors in there but not sure if they are expected or not. [NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14912066/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@lfilho you guys need to close that error and let battlenet install twice

**Comment by lfilho** [comment]
Hey @moraroy you mean just clicking ok on the error message and then running the installer again? That's what i did

**Comment by moraroy** [comment]
@lfilho hmmm should work... basically with the current Proton, battlenet needs to be installed twice over on top of each other to install. Check the compatdata folder and see if there is any left over files that needs to be deleted it should just be a NSL folder once it's done that is ymlinked to your real folder. But regardless battlenet should install once you close that error window.

**Comment by lfilho** [comment]
Alright, i just saw another #256 and the comment about not having a previous non-steam app installed borked it. Indeed after adding Chrome and running the installer, it worked! (Ignoring the battle.net error as you mentioned). Now i see all the installer on the non-steam tab, just have to test the actual games now! Woop! I'll definetely donate something later

**Comment by moraroy** [comment]
@lfilho yeah not.your fault I need to fix that chrome error I don't know why it's doing that and preventing people installing properly.

**Comment by jaco9613** [comment]
@moraroy I do add chrome. But I reinstall the launch, it doesn’t appear in steam.
Event now, I play battle net still need open developer mode
