### ISSUE TITLE
Launchers not in library

### ISSUE THREAD

**Issue by RaejenXaxios** [moraroy/NonSteamLaunchers-On-Steam-Deck#26]
Non of the launchers show up in the Steam library.

**Comment by Skyline969** [comment]
I'm also seeing this issue. Latest stable version of SteamOS.

**Comment by doejohnjr3** [comment]
Same thing for me. Three days ago was on latest Preview version, no launchers in Steam after install. Yesterday switched to latest Beta, same result - installer sees launchers installed, but no launchers in Steam.

**Comment by vralfy** [comment]
Same here ... Installed it for the first time on a deck with nearly no customisations on the os itself

**Comment by moraroy** [comment]
@vralfy @Skyline969 @RaejenXaxios @sagman76 @doejohnjr3 I've updated and added a fix to 2.75 that may help some people, I'll be adding the rest of the code in a couple of days to 2.8

**Comment by SuperChaoHai** [comment]
HI i am on SteamOS 3.4.6
i downloaded SteamDeck 2.8 for the first time
i tried installing twice, and got the yoda contemplation.
then i start fresh.. 
all attempts fail to get the launcher in the library 
please help @moraroy

**Comment by Kaabvoo** [comment]
https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/issues/27

It was resolved within the last push (2.83)
