### ISSUE TITLE
Amazon prime mobile number change

### ISSUE THREAD

**Issue by Wh4t3v3r73** [moraroy/NonSteamLaunchers-On-Steam-Deck#277]
I used the nsl to install prime, but when I try to load I need a pin which is sent to my phone, but an email is also sent which claims that the nsl is trying to change my delete my mobile number on my account and not just trying to log me in, seems dodgy.

![Screenshot_20240428_101542_Gmail](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/168336328/4e5b45e9-9c9a-4824-b658-ce6e0b587bcf)

**Comment by Wh4t3v3r73** [comment]
Edit, I have used nsl to load epic, gog and ubisoft and all work fine, so no idea why this is trying to delete my phone number from my amazon account, safe to say I didn't use it and deleted the prime loader off and also changed my amazon password. 

Downloaded the nsl from official download.

**Comment by moraroy** [comment]
@Wh4t3v3r73 LOL, this has absolutely nothing to do with NonSteamLaunchers. Sorry brother, but you most definitely need to make sure your account isn't getting hacked. No where in the code of nsl is any account being accessed nor does nsl have anything to do with amazon prime? Check your own Google Chrome Browser settings or somehow keep track of what you do online.

**Comment by moraroy** [comment]
You're aware amazon Luna and all the streaming sites are in fact using Google Chrome right? And the steam deck is a Linux machine...

**Comment by Wh4t3v3r73** [comment]
I am aware of what you say and I've used the app and its worked fine, all I'm saying is I used my steamdeck to add prime via nsl and I tried to login on amazon but needed a 6 digit code, I tried it 4 times and 4 times I got the same email, within seconds of trying to log the code, you can see it in the email I got above, I was not doing anything else at the time, I was only on my steamdeck trying to login to prime, I'm not trying to blame anyone, I'm just saying I added prime via nsl, tried to login 4 times, got 4 different codes and 4 different emails telling me the same thing, and all my amazon stuff is secure that's why I get a message and email to confirm its me.

Sorry, but this is what happened.

**Comment by Wh4t3v3r73** [comment]
I'll close this then as you have answered my question.

Thank you
