### ISSUE TITLE
[EA App] Sims 3 will stop working all together if I launch it from steam. 

### ISSUE THREAD

**Issue by mbrow237** [moraroy/NonSteamLaunchers-On-Steam-Deck#279]
I installed EA App from the non-steam-launcher script, and from there I was able to download and play the Sims 3.

I restarted steam and saw the script added EA App and Sims 3 onto steam for me. If I launch the Sims from the EA App, it will work no problem. If I launch Sims 3 directly, it will launch the EA App, tries to launch the game, and then fail with an error stating:

"Failed to launch game
An error on our end caused the launch to fail. Try again a little later."

After this happens, If I try to launch the Sims from the EA App I get the same error. I did a "start fresh" installation of the EA App and was able to launch the Sims 3 again, until I tried to launch the game it directly from steam, starting the cycle anew.

**Comment by mbrow237** [comment]
Yeah you're right. Launching it with my deck connected to my mobile hotspot launched the game from the steam launcher. Hopefully EA fix this soon(doubt)

**Comment by moraroy** [comment]
@mbrow237 still trying to figure out why that is though I love looked in the log files of the ea app and it seems that the authentication website is being blocked somehow in game mode

**Comment by moraroy** [comment]
@mbrow237 I fixed it bro!! https://www.reddit.com/r/SteamDeckBro/s/jBl4mPV39J it works in game mode and desktop, wifi, Hotspot, offline , online it all works!

**Comment by mbrow237** [comment]
Ah this is good to know! Thank you!!
