### ISSUE TITLE
Add the Minecraft Launcher!

### ISSUE THREAD

**Issue by TheIronboy** [moraroy/NonSteamLaunchers-On-Steam-Deck#28]
can you please add the minecraft launcher for windows?
this is VERY useful for people trying to play minecraft dungeons or legends and did not buy the steam version.

**Comment by Dasart0** [comment]
Oh that would be so cool! I would love that!

**Comment by moraroy** [comment]
@TheIronboy @Dasart0 once i squahc bugs ill be adding more features thank you for the suggestion, i just updated so let me know if 2.82 is adding the launchers to the library

**Comment by moraroy** [comment]
@Dasart0 @TheIronboy is there some source that you can provide that the windows exe version will work.. or some form of it at least? I tried to test it out on my steam deck but it wouldn't install.

**Comment by TheIronboy** [comment]
the .exe version of the launcher doesn't work, you need to use the .msi version (minecraft legacy launcher)

you can find it here:
https://www.minecraft.net/it-it/download

**Comment by moraroy** [comment]
@TheIronboy ah gotcha ok. thank you ill look into this!

**Comment by moraroy** [comment]
@TheIronboy @Dasart0 added Minecraft to NonSteamLaunchers!

**Comment by mtsr** [comment]
Should this work with Microsoft accounts as well? I've converted mine for reasons, but that means I can't sign it with mojang anymore.

I'm getting:

"Error Code: 0x80004005 code: Eroded Badlands. A file that the Windows Product Activation (WPA) requires is damaged or missing. Please reboot, verify system permissions, and make sure your operating system is up-to-date. For more information, go HERE or contact Customer Support directly."
