### ISSUE TITLE
Xbox Game Pass

### ISSUE THREAD

**Issue by Chidorick** [moraroy/NonSteamLaunchers-On-Steam-Deck#282]
Can I install Xbox Game Pass and install games from it or is it all just the cloud version? After selecting to install Xbox Game Pass and launching it, it just won't open

**Comment by moraroy** [comment]
@Chidorick make sure you have chrome installed, and make sure compatability is blank

**Comment by Chidorick** [comment]
how to make compatibility blank?

> @Chidorick make sure you have chrome installed, and make sure compatability is blank

**Comment by moraroy** [comment]
@Chidorick in game mode, properties, uncheck

**Comment by Chidorick** [comment]
okey. Thank you
