### ISSUE TITLE
Previously installed proton versions wiped on installation of NonSteamLaunchers

### ISSUE THREAD

**Issue by paladin181** [moraroy/NonSteamLaunchers-On-Steam-Deck#285]
I installed NonSteamLaunchers with the executable desktop file, and chose to install GOG Galaxy. I had several versions of GE Proton installed for different games, and after this installed, all those were gone and just the latest version of GE Proton was installed (I had not previously downloaded that version).

This is inconvenient since links to my older games are broken and I don't remember which version of Proton worked best with each one.

**Comment by moraroy** [comment]
@paladin181 yeah sorry about that, I'm going to edit the script now so it doesn't do that. It installs the latest ge only when you install a launcher and wipes the rest. I'll fix that now. However I wanted to also say the current decky plugin has been updated to for real time shortcuts no longer needing to restart steam. You may try that in the testing store to see if that is better for you liking and convenience. I don't believe the decky plugin version will wipe your GE's. Let me know it works. Give me about 15 min to update the desktop version.

**Comment by moraroy** [comment]
@paladin181 just fixed that in the bash script brother, again sorry about that. let me know if youre able to still keep old proton ge's when you install the launchers.

**Comment by paladin181** [comment]
Fast response. I like that.

**Comment by moraroy** [comment]
@paladin181 i like you
