### ISSUE TITLE
GOG Galaxy games with DLC adds DLC as separate entries in your Steam Library.

### ISSUE THREAD

**Issue by paladin181** [moraroy/NonSteamLaunchers-On-Steam-Deck#291]
Tested with Asterigos: Curse of the Stars. 
Tested with The Witcher 3: Wild Hunt (original release)
Installed on GOG Galaxy and ran manual scan. Got shortcuts for the games and each individual DLC added to Steam.

Desktop version 3.8.5

**Comment by moraroy** [comment]
@paladin181 should be fixed on desktop and plugin version... give it a go, but for the plugin version I can't yet update in real time so you have to wait for "patches". So the desktop should give you the correct shortcuts for gog now.

**Comment by paladin181** [comment]
That's working properly
