### ISSUE TITLE
Cannot Install Sites - 😫 

### ISSUE THREAD

**Issue by githubUser01946** [moraroy/NonSteamLaunchers-On-Steam-Deck#295]
I have installed Google chrome.
I have then installed via Decky, NonSteamLaunchers 1.0.0-91b52e1
I chose Xbox Game Pass and Fortnite (xCloud) but after I click the installed button it just goes back to selection and nothing is added to Steam.

Video of what happens: https://youtu.be/cD-qHdHW_Js?si=Zx-GooZpeJOSdQdG

**Comment by moraroy** [comment]
@githubUser01946 thank you for testing this, it shouldnt be doing that. it only does that when they are already added to steam I believe, are you sure they aren't there? I also have the plugin installed and I do not have this issue, the only way I can replicate it is if I already have the shorcuts... hmmm..unless it can't find the env_vars file. Let me do a quick test on my deck I'm going to factory reset , I'll get back to you.

**Comment by moraroy** [comment]
@githubUser01946 yeah I just tested it there is no env_vars. To get around this for now, you would have to install any launcher to create that file. Keep an eye out for updates to the plugin soon, as we will push these fixes to the testing store!

**Comment by githubUser01946** [comment]
> @githubUser01946 yeah I just tested it there is no env_vars. To get around this for now, you would have to install any launcher to create that file. Keep an eye out for updates to the plugin soon, as we will push these fixes to the testing store!

I've not checked for an update yet but will keep an eye out.

Thanks for looking into it.

**Comment by githubUser01946** [comment]
@moraroy,  Does the store update on a specific day?
Is there any work around I can do in the meantime?

I'm very impatient 🤣

**Comment by moraroy** [comment]
@githubUser01946 same! Just pushed an update right now as well. It may not be the update yet that fixes your issues specifically but the problem is having to wait so long :/

https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/527

**Comment by moraroy** [comment]
@githubUser01946 yeah I told you a work around lol install a launcher

**Comment by githubUser01946** [comment]
> @githubUser01946 yeah I told you a work around lol install a launcher

That too doesn't seem to work. It shows a toast to say they're installed but I can't find them and trying to install the sites after does the same as before, nothing.

New video with some parts speeded up:

https://youtu.be/GT0F4Etln_g?si=NMCGdnuIrfhv_X6l

**Comment by moraroy** [comment]
@githubUser01946 interesting ok, to better fix this issue, message me on discord @moraroy it seems like the launchers are indeed installing just the scanner seems to be messing up. Message me there so I can walk you through it!

**Comment by githubUser01946** [comment]
Ok I'll do that tomorrow, it's late here for me.

Cheers 👍🏻

**Comment by githubUser01946** [comment]
Now sorted.
