### ISSUE TITLE
Itchio missing on Decky version ?

### ISSUE THREAD

**Issue by PunkyBust** [moraroy/NonSteamLaunchers-On-Steam-Deck#299]
Hello,

On decky version of NonSteamLauncher Itchio is missing.
Is it normal ?
Because on desktop version it is here.

Thank you very much or this great app.
🙂

**Comment by moraroy** [comment]
@PunkyBust I've already added itchio and Rockstar, I'm waiting for the decky loader team to approve the changes.  https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/527

**Comment by moraroy** [comment]
@PunkyBust this has been added to the latest build!
