### ISSUE TITLE
Installers dont work?

### ISSUE THREAD

**Issue by Koruyo** [moraroy/NonSteamLaunchers-On-Steam-Deck#3]
Battle.net

+ echo 'Running BATTLE file using Proton with the /passive option'
+ true
+ pgrep -f Battle.net.exe
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-1/proton run /home/deck/Downloads/NonSteamLaunchersInstallation/BattleNetInstaller.exe Battle.net-Setup.exe --lang=enUS '--installpath=C:\Program Files (x86)\Battle.net'
+ sleep 1
/home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh: line 149: /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-1/proton: No such file or directory
+ true
+ pgrep -f Battle.net.exe
+ sleep 1
+ true
+ pgrep -f Battle.net.exe
+ sleep 1
+ true
+ pgrep -f Battle.net.exe
+ sleep 1
+ true
+ pgrep -f Battle.net.exe
+ sleep 1
+ true
+ pgrep -f Battle.net.exe
+ sleep 1
+ true
+ pgrep -f Battle.net.exe
+ sleep 1
+ true
+ pgrep -f Battle.net.exe
+ sleep 1
+ true
pgrep repeats infinite...
waited 20min then aborted, tried again with fresh... same thing.

Just
Epic Games works...

///edit
Correction
Epic Games the script finishes and wants to restart steam...  but its not added in steam, where does it install / should it be under compatdata nonsteamlaunchers? Nothing there...

**Comment by Koruyo** [comment]
I assume it has to do with compatibilitztools
There is a GE Proton 8-1 folder but no subfolder proton but instead files\

/home/deck/.steam/root/compatibilitytools.d/GE-Proton8-1/files/bin/

**Comment by Koruyo** [comment]
removed ge-proton8-1 folder and now it works.

**Comment by Koruyo** [comment]
removed ge-proton8-1 folder, then tried again... works now.

**Comment by moraroy** [comment]
sorry brother im new to github and didnt see this message... yeah there is some bugs i have to squash BUT im slowly working my way toward a stable version for everyone... right now certain installers wont trigger the steam restart BUT they do get installed. Also, the reason youre not seeing the launchers in your steam library is a bug that im really trying to fix cuz that shortcuts have the important compat data command and directories you need. SO i would always grab the latest version. I also implimented a version check updater that lets you know when a new version is out that way it helps you. Version 1.8 and up is the way to go
