### ISSUE TITLE
Issue recognising apostrophes

### ISSUE THREAD

**Issue by JoshTheTofu** [moraroy/NonSteamLaunchers-On-Steam-Deck#308]
I have installed Assassin's Creed Chronicles Russia via Ubisoft Play but when I scanned it into game mode it has called it "Assassin\2019s Creed Chronicles Russia" and has given me the cover art for a Team17 game called Assassin.

Kind regards

Josh

**Comment by moraroy** [comment]
@JoshTheTofu ill let you know when there is a fix

**Comment by moraroy** [comment]
@JoshTheTofu sorry for the long wait this has just been fixed in the desktop version, i will be pushing this change to the plugin version as well, the plugin updates take longer push just fyi

**Comment by JoshTheTofu** [comment]
Hi Roy

Thank you for the fix. It is very much appreciated. Would you like me to give it a test?

Kind regards

Josh

**Comment by moraroy** [comment]
@JoshTheTofu no need I tested already!
