### ISSUE TITLE
Battle.net Install crashed

### ISSUE THREAD

**Issue by funny0facer** [moraroy/NonSteamLaunchers-On-Steam-Deck#310]
Hi, I wanted to install battle.net but it stopped during updating the agent.
I do not know, if my setup is supported. I run Arch Linux and not SteamOS.

here is the crash report:
[2024-05-27 08.41.05 Crash.txt](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/15452004/2024-05-27.08.41.05.Crash.txt)

Thanks :)

**Comment by moraroy** [comment]
@funny0facer can you show me the NSL log in your downloads as well?

**Comment by chichekebbab** [comment]
Same here, brand new SteamDeck, up to date, impossible to install Battle.net

**Comment by Aimela** [comment]
Yeah, it was working for me a bit ago(albeit intermittently) from an install a while ago, but I reinstalled it because of some control weirdness with ConsolePort on WoW, and now I have some troubles getting it back again.

**Comment by SockHatAbe** [comment]
Finally some others saying that battle net doesn't install anymore. Heck, it won't even update ge proton for me now.

**Comment by moraroy** [comment]
@funny0facer @chichekebbab @Aimela @SockHatAbe this has been fixed, Battle net no longer requires the temp fix i had placed, make sure youre using the latest proton GE, i installed it just fine on the desktop version of NonSteamLaunchers
