### ISSUE TITLE
can't run the NonSteamLaunchers.desktop

### ISSUE THREAD

**Issue by tsq456** [moraroy/NonSteamLaunchers-On-Steam-Deck#312]
I downloaded NonSteamLaunchers.desktop to the desktop, double-clicked it to run it, and it just pops up the bash window and immediately closes itself, how do I fix this?

**Comment by moraroy** [comment]
@tsq456 make sure its executable, right click and go to properties, and cmake executable then double click it, it shouldnt open up kate
