### ISSUE TITLE
Environment variable "controller_config_path" not found

### ISSUE THREAD

**Issue by shadow7412** [moraroy/NonSteamLaunchers-On-Steam-Deck#313]
Firstly, is this project willing to support non-steamdeck installs? If not, then I guess this can be closed.

But, if you're willing to consider it, this project would be a very useful tool in the arsenal of linux gamers.

Skimming through the logs, this seems to be the part of interest;

```
Starting the service...
+ python3 /home/steven/.config/systemd/user/NSLGameScanner.py
Traceback (most recent call last):
  File "/home/steven/.config/systemd/user/NSLGameScanner.py", line 54, in <module>
    controller_config_path = os.environ['controller_config_path']
                             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'controller_config_path'
```

What would normally be in this variable, so I can populate it myself? Or perhaps so we can make this script have a fallback route?

Much appreciated.

**Comment by moraroy** [comment]
@shadow7412 im going to fix this right now

**Comment by moraroy** [comment]
@shadow7412 fixed
