### ISSUE TITLE
Cannot download Minecraft Launcher

### ISSUE THREAD

**Issue by arspaper** [moraroy/NonSteamLaunchers-On-Steam-Deck#319]
Made factory reset for my Steam Deck. Wanted to install launchers and found out that Minecraft Launcher is missing. Using Beta steamOs
![Screenshot_20240605_130613](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/59622720/f8128bd0-f683-4c54-8c28-442ba0a3a9f1)

**Comment by moraroy** [comment]
@arspaper I removed Minecraft as the Decky Team no longer wanted it installed for the decky plug in.

**Comment by arspaper** [comment]
Damn, that's unfortunate
