### ISSUE TITLE
Uninstall not working

### ISSUE THREAD

**Issue by ItMeCorban** [moraroy/NonSteamLaunchers-On-Steam-Deck#320]
I uninstalled rockstar games launcher and then removed it from steam, but everytime I open steam it re-appears, how do I get rid of it?

**Comment by moraroy** [comment]
@ItMeCorban it should be sort of fixed now please try again, in the future this will be done in a better way.

**Comment by moraroy** [comment]
@ItMeCorban this has been fixed in the latest version, please try again, also don't forgot to delete your shortcuts after you uninstall
