### ISSUE TITLE
Requesting HoyoPlay launcher support.

### ISSUE THREAD

**Issue by adriansticoid** [moraroy/NonSteamLaunchers-On-Steam-Deck#327]
Hi. I was hoping support for HoyoPlay https://hoyoplay.hoyoverse.com/ can be added.

**Comment by moraroy** [comment]
@adriansticoid yes this could be added but currently waiting to add any launchers until the decky plugin is in the main store.

**Comment by moraroy** [comment]
@adriansticoid could you find me the link to the actual download? I couldn't find it unfortunately

**Comment by adriansticoid** [comment]
@moraroy it's on https://hoyoplay.hoyoverse.com/. If you open the link on your mobile, you need to set your browser tab to desktop mode so the download button shows. Screenshot attached.

![Screenshot_20240703-182159_Firefox](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/122187236/36a85c00-5455-4700-8a9e-a8e813ae7c5c)

**Comment by moraroy** [comment]
@adriansticoid I can't extract the actual link from that though for some reason

**Comment by adriansticoid** [comment]
@moraroy can you try this? 

https://download-porter.hoyoverse.com/download-porter/2024/06/07/hyp_global_setup_1.0.5.exe?trace_key=HoYoPlay_install_ua_109daee2060b

**Comment by moraroy** [comment]
@adriansticoid OK thanks that's good, how did you extract that?

**Comment by adriansticoid** [comment]
@moraroy I use an app called ADM. It's a download manager. It shows a prompt when initiating a download that includes the direct link for it.

**Comment by moraroy** [comment]
@adriansticoid that's tight! I'll look into using that from now on! Just so you know the script is now alot easier to add launchers now through pull requests. If you know any bash of course! But thank you for the link I'll see about adding it.

**Comment by adriansticoid** [comment]
@moraroy thank you so much for your work!

**Comment by moraroy** [comment]
@adriansticoid added it let me know how it goes, for now this is on desktop only

**Comment by adriansticoid** [comment]
@moraroy thank you but I already have a working setup for that launcher. I requested it for the people not as tech savvy as us.

**Comment by moraroy** [comment]
@adriansticoid a man of culture I see! For the people!

**Comment by moraroy** [comment]
@adriansticoid seems easy enough to also parse for shortcuts too, ill do that next

**Comment by GlassedSilver** [comment]
> @adriansticoid seems easy enough to also parse for shortcuts too, ill do that next

I take it you mean adding non-Steam game shortcuts to Steam from the list of installed games within HoyoPlay?
Any ETA on this possibly?

**Comment by moraroy** [comment]
@GlassedSilver no eta as of yet but technically you could just download the hoyo games from epic games launcher, then NSL will make shortcuts of those hoyo games from epic , thats what did lol but ill see if i can add that hoyo scanner soon

**Comment by GlassedSilver** [comment]
The less I need to touch Epic the better haha

Would you mind creating an issue for this, so I can keep tabs on it and I guess manually adjust my launch parameter for the time being?

**Comment by moraroy** [comment]
@GlassedSilver https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/issues/353#issue-2420841971
