### ISSUE TITLE
Launchers won't appear in library anymore

### ISSUE THREAD

**Issue by abyxgail** [moraroy/NonSteamLaunchers-On-Steam-Deck#331]
got my steam deck a couple of weeks ago and had no issues with the launchers until they recently disappeared from my steam library   .   i have tried restarting the console and uninstalling and reinstaling the launchers. the download works and steams reload but they don't appear

**Comment by moraroy** [comment]
@abyxgail can you upload your log it's in the downloads folder

**Comment by moraroy** [comment]
@abyxgail could you send your log? It's in the downloads folder, also just sent in a small fix let me know if it works

**Comment by abyxgail** [comment]
That seems to have fixed it ! Thank you so much I was so bummed out !!
