### ISSUE TITLE
The script deleted all my non-steam shortcuts

### ISSUE THREAD

**Issue by jullebarge** [moraroy/NonSteamLaunchers-On-Steam-Deck#334]
I used NSL to install an EA game last week, and after this installation, I lost all my other non-steam games: emulation games from Emudeck, and abandonware games that I added manually (Blur, NFS Carbon, ...)
I ended up deleting everything and I'll will reinstall them one by one but if you could check that, it would be nice so it doesn't happen again.

**Comment by moraroy** [comment]
@jullebarge this is already fixed in the new update?
