### ISSUE TITLE
EA Downloader - Path not found

### ISSUE THREAD

**Issue by thesnable** [moraroy/NonSteamLaunchers-On-Steam-Deck#335]
Hi

I cant install it: "Path bot found" Box which i can only ok

**Comment by thesnable** [comment]
With a separate knstallation it seems to run through but no ea entry in steam

**Comment by thesnable** [comment]
Bonlaunchers show up on steam

**Comment by moraroy** [comment]
@thesnable can you send your log?

**Comment by thesnable** [comment]
I think if gound the issue:

reverting to stable / stable
made all work again

i think valve changed something in the main branches / steam beta

**Comment by moraroy** [comment]
@thesnable ah dang no worries yeah sometimes the new updates mess stuff up, I hope it's all working now for you!

**Comment by moraroy** [comment]
@thesnable this has also been fixed in the latest
