### ISSUE TITLE
Most Chrome clients (Disney, Prime, etc.) installed successfully but are not launching

### ISSUE THREAD

**Issue by julianrios** [moraroy/NonSteamLaunchers-On-Steam-Deck#337]
I installed the apps one by one and can see them in steam but they are failing to launch

**Comment by moraroy** [comment]
@julianrios make sure chrome is installed, also, make sure the compatability is "unchecked" in properties.

**Comment by julianrios** [comment]
yep chrome is installed and set as default and compatibility is unchecked

**Comment by moraroy** [comment]
@julianrios send your log in the downloads foldder

**Comment by julianrios** [comment]
Thanks for taking a look I'll try a reboot. I just tried removing and readding but doesn't seem to be taking now. [NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16036970/NonSteamLaunchers-install.log)

**Comment by julianrios** [comment]
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16036987/NonSteamLaunchers-install.log)
Adding these logs since I was able to get the apps back on steam but still failing to launch for xbox, geforce, and netflix. App just starts and stops

**Comment by moraroy** [comment]
@julianrios hmmm your logs look successful, there is no errors....I have a feeling this may be a chrome issue. Someone a long time ago mentioned that the chrome installation isn't quite right. The steam shorcuts that are created are looking in usr/bin for chrome. Check the properties of the shortcuts and see if chrome is installed there on your system. If it isn't I have to figure out why that is

**Comment by julianrios** [comment]
So I think it might be stable now not sure if the reboot did it but I was also trying to launch from desktop mode maybe that was causing this bug

**Comment by moraroy** [comment]
@julianrios ah OK so it's working now?

**Comment by julianrios** [comment]
Really appreciate you looking into this. Also a side note not sure if the move to sd card is functionally but I also have that a try and it showed as successful but nothing was moved at all

**Comment by julianrios** [comment]
Yea it’s work so far tested Netflix and Xbox just need to reinstall geforce. Really great app love how easily everything just works once isn’t installed

**Comment by moraroy** [comment]
@julianrios no problem brother! I'm glad it's working now.
