### ISSUE TITLE
Unable to install GeForce Now and Xbox Game Pass through desktop app

### ISSUE THREAD

**Issue by julianrios** [moraroy/NonSteamLaunchers-On-Steam-Deck#358]
Netflix installed without any issues also another chrome app:
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16356809/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@julianrios try one at a time?

**Comment by julianrios** [comment]
@moraroy thanks tried again but no luck doesn't seem to install for me anymore

**Comment by julianrios** [comment]
Would Netflix be install differently than these two? Since that one installed without any issues.

**Comment by moraroy** [comment]
@julianrios ok , I'm going to take a look at your log again, may be a couple a days

**Comment by julianrios** [comment]
Alright thanks this is also on a new steamOS install I’m using the latest desktop version but I’ll try a few others.

**Comment by julianrios** [comment]
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16385394/NonSteamLaunchers-install.log)

**Comment by julianrios** [comment]
Thanks that seemed to work!

**Comment by moraroy** [comment]
@julianrios nice! So everything g is working now?

**Comment by julianrios** [comment]
Yea I did the same steps for the YouTube install since it was failing to install and it worked on the right after deleting the file in downloads

**Comment by moraroy** [comment]
@julianrios dang that's weird hahaha ok I'll see if I cam fix that in the next update sorry about that

**Comment by julianrios** [comment]
Yea no worries bugs happen. I appreciate the support! It’s definitely a great app

**Comment by moraroy** [comment]
@julianrios this been fixed! be sure to use the latest .desktop file
