### ISSUE TITLE
Launchers immediately crash back to game mode

### ISSUE THREAD

**Issue by TheDarkSpock** [moraroy/NonSteamLaunchers-On-Steam-Deck#360]
I’m running into a problem with NonSteamLaunchers after trying to download a game from Itch. Here’s what happened:

I set up NonSteamLaunchers and signed in to all my launchers (Amazon, Epic, Itch, etc.), and everything seemed to work fine.

I downloaded a game from Itch, but after restarting, the game didn’t appear in game mode.

I went back to desktop mode to restart the NSLGameScanner.service, hoping that would resolve the issue.

Since then, almost everything is broken. None of the downloaded launchers (Amazon, Epic, Itch) will open—they crash immediately and return me to game mode. 

The only applications that still launch are the streaming services.

Does anyone have any suggestions on how to fix this? Any help would be greatly appreciated!

Thanks in advance!

**Comment by moraroy** [comment]
@TheDarkSpock go back into desktop mode, and download the newest .Desktop file and use that instead, open NSL using that new .desktop file and click on Stop NSL Scanner and then click NO. This will stop the scanner. Then restart steam and see if you can open up the shortcuts again. As far as itchio is concerned is it a game that requires to play in a web browser? If so, I don't know how to set that up yet, the game in itchio needs to be a .exe som of them are web based

**Comment by TheDarkSpock** [comment]
Thanks for your suggestions. I’ve downloaded the latest desktop file and followed the provided steps, but the issue with the launchers persists. Here’s what’s happening:

All non-streaming apps (Amazon, Epic, Itchio) continue to crash back to the desktop.
When I try to launch them, the Steam logo appears briefly before the app crashes and returns me to game mode.

Thanks!

**Comment by moraroy** [comment]
@TheDarkSpock is compatabilty being forced in the shortcuts? open the properties of those shortcuts and check to make sure compatability is being forced to the latest proton ge.....if that is correct, then open up NSL and check your paths, NSL lets you know what is actually installed.

**Comment by TheDarkSpock** [comment]
Thank you for your help. ProtonGE is being forced, and while all the launchers have paths listed in the properties section in game mode, there are no paths listed when I open NSL. I have no idea why this happened, as I didn't uninstall or move anything. All the streaming apps are still working without issue.

**Comment by moraroy** [comment]
@TheDarkSpock the fact that you have no paths when you open NSL means nonething is installed, if you have clicked the button "Start Fresh" this deletes and wipes everythingeverything. Not sure what would have caused this to happen but somehow it seems nothing is installed? Please check your /home/deck/.local/share/steam/steamapps/compatdata/ folder... in there there will be folders that tell you what is installed. When it comes to your shortcuts those are just shortcuts. You can delete them and start over if you wish.

**Comment by TimAldejohann** [comment]
I had the same issue! The symlink NonSteamLaunchers in the compatdata directory broke after an update and was pointing to the wrong directory. I renamed the old compatdata folder (found it by looking through all and one contained all installed launchers) to the one referenced in the symlink.

**Comment by moraroy** [comment]
@Timmelz I really want to fix that issue, I think the error is in the logic of the NSLGameScanner.py with the symlinks

**Comment by Timmelz** [comment]
I think the hardcoded app id caused the issues. That is the same id, I changed my symlink to:
https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/blob/16779f01a4c9f77fb948639acbce2e9842a70e1a/NSLGameScanner.py#L663

Previously the first app id was used, right?

After launching NSL in the newer version, it updated the symlink to the new folder, which was empty.

**Comment by moraroy** [comment]
@Timmelz yeah they're may be better logic to do instead maybe unlink everyone's old symlink and then symlink to the new one? Idk

**Comment by moraroy** [comment]
The first app I'd was used but I got rid of that logic because it was confusing for some

**Comment by psxlover** [comment]
Want to add that start fresh does not delete all symlinks so trying to reinstall launchers from scratch may fail until you manually delete any leftover symlinks.

**Comment by moraroy** [comment]
@psxlover thanks for the heads up, I'm going to try to add some more logic that deletes them better

**Comment by woodsielord** [comment]
Exact same issue, everything lost. What's the current symlink workaround?

**Comment by TheDarkSpock** [comment]
Is there any update on this? I would like to give NonSteamLaunchers another try, but I'm unsure of the best approach. Should I try and reinstall all the launchers, or do I need to go through all the compatdata folders to see if the launchers are still installed?

**Comment by moraroy** [comment]
@TheDarkSpock open up NSL with the latest .desktop file and see what is installed. If you have things installed then sure you can use your old launchers. Hitting start fresh should wipe eveythting if you want to start over.

**Comment by moraroy** [comment]
@woodsielord was this solved for you? Or did the symlinks break?

**Comment by woodsielord** [comment]
> @woodsielord was this solved for you? Or did the symlinks break?

Sorry I went another route and reinstalled, I can't be much help in troubleshooting.

**Comment by moraroy** [comment]
@woodsielord no worries brother glad you're up and gaming

**Comment by Andrii-Brykaliuk** [comment]
Hello @moraroy , seems that I've stuck with the same issue.
Instead of installation of any Launcher - I'm getting an item called "NonSteamLaunchers" in my library.
Everything worked few weeks ago.

I've tried desktop version and plugin, the result is the same.
Also, I've tried to perform "Fresh Start"

Let me know how I can help you to investigate this further =)
![photo_2024-10-04_19-30-47](https://github.com/user-attachments/assets/5fb9e28c-35fd-45c8-ae31-fe67364f36e4)

**Comment by moraroy** [comment]
@Andrii-Brykaliuk strange that shoulnd tbe happening , what launchers di you try to install, please upload your log!

**Comment by Andrii-Brykaliuk** [comment]
@moraroy , this happens to any launcher, here is my log
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/17282308/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@Andrii-Brykaliuk first hit. Start Fresh, then re-install the latest proton GE using Proton Up Qt, or the plugin Wine Cellar if you're using game mode. Next, go into desktop mode and go into compatdata and delete any strange or broken files or symlinks. Then try to use NSL again

**Comment by Andrii-Brykaliuk** [comment]
@moraroy , many thanks! 
Removing corrupted file in compatdata folder resolved my issue.

**Comment by moraroy** [comment]
@Andrii-Brykaliuk i want to fix this permanently but for some reason i cant delete broken symlinks in bash i dont know why

**Comment by moraroy** [comment]
should be fixed in latest?
