### ISSUE TITLE
Ubisoft Connect broke after update

### ISSUE THREAD

**Issue by 0fMothsAndMen** [moraroy/NonSteamLaunchers-On-Steam-Deck#367]
I was playing a game on Ubisoft Connect when I got a notification to update the decky plugin NSL, I hit update and my game immediately got laggy before freezing up the entire console. I passed it off as an issue of trying to update something currently in use so I restarted my deck and now Ubisoft Connect will not open at all. I just get the Steam logo for a few seconds before it crashes. 
I have tried reinstalling on both the plugin and desktop versions, both say they installed correctly but when I reopen them they have no check marks next to any of the launchers I had previously installed. Ubisoft Connect still appears in my library but it still just gives me the logo before crashing. I tried uninstalling the plugin to see if that was the problem but it had no effect. I also tried changing the proton version and installing an older version of the decky plugin. I am running the beta updates and was having no issues until about an hour ago, I did try switching to the stable update channel but no dice. The NSL plugin was the only thing I updated, nothing else was changed. I'm not really sure what else to do from here or what the actual problem even is.

ETA: I did try opening the other launchers I had installed as well with the same results

**Comment by moraroy** [comment]
@0fMothsAndMen wow that's very strange, over the weekend I'll do some testing on the beta channel as I'm on stable only, ummm... to be honest though, there isn't really any code in my plugin that would do something like that, as most of the code is about creating shortcuts. Maybe the main.py of the decky plugin is at fault... but you said you even used the desktop file and it still won't do anything?

**Comment by moraroy** [comment]
@0fMothsAndMen when you use the .desktop version make sure you're using the new .desktop file byw

**Comment by 0fMothsAndMen** [comment]
No worries! Yeah I have no idea what exactly happened but I really appreciate the help! I wouldn't have thought it was the issue if I wasn't mid-game when it happened after changing nothing else.
Yes I am using the latest .desktop, I decided to try moving all my game files and doing a full fresh install which seems to have worked! Still not sure what I did the first time to mess it up, I only switched to beta within the last week so it very well could be something on my end. 
I believe I have fixed it for the time being and hopefully won't have any more issues but thank you so much for the response!!

**Comment by moraroy** [comment]
@0fMothsAndMen the NSL plugin isn't working beta too well that may be the issue too, I'm testing over the weekend for the beta branch and will see if I encounter any issues, the plugin is pretty stable on Stable branch of SteamOS, but yeah sorry about that! Will keep testing!

**Comment by moraroy** [comment]
@0fMothsAndMen is this still an issue?

**Comment by 0fMothsAndMen** [comment]
Thank you for following up!
I have not had any issues but I also haven't tried to replicate the problem. I've done all updates with apps closed to be safe. 
The new Ubisoft Connect SD card support is also working very well!

**Comment by moraroy** [comment]
@0fMothsAndMen heck yeah man im glad to hear that, do you mind adding a comment about your experience on the pull request for the main store? The link should be in the read me

**Comment by 0fMothsAndMen** [comment]
Happy to! The decky plugin pull request, right?

**Comment by moraroy** [comment]
@0fMothsAndMen yes thsnks bro, its because it needs testers to test, ill also close this issue as well!
