### ISSUE TITLE
All shortcuts are added to steam regardless

### ISSUE THREAD

**Issue by Dartis4** [moraroy/NonSteamLaunchers-On-Steam-Deck#37]
Despite my choice in the menu for what launcher I want to install, it adds shortcuts for all launchers into Steam. It seems like it might be just the default launchers, but it adds all of them back in. There is nothing in the script that prevents duplicate shortcuts from being added to Steam either, so there will be infinite duplicates of the shortcuts each time the script is run, which I don't think anything is installed at the locations the shortcuts are supposed to be linking to, so they are shortcuts that don't even work, meaning they just have to be manually deleted. This is also annoying since some changes need to be made to the shortcuts to get them to work since there are other issues with where they are linking to, so each one needs to be checked to make sure you manually delete the correct shortcut. There needs to be some kind of check here to make sure that the script is only adding the shortcut for the selected shortcuts and that duplicates are not being created endlessly.

**Comment by moraroy** [comment]
@Dartis4 this is actually not true. "There is nothing in the script that prevents duplicate shortcuts from being added to Steam either, so there will be infinite duplicates of the shortcuts each time the script is run" --- my script does this check for each and every shortcut. please send a log so i can see whats going on!!
