### ISSUE TITLE
Controller not recognized in games

### ISSUE THREAD

**Issue by emosludge** [moraroy/NonSteamLaunchers-On-Steam-Deck#370]
Hi, I just got a steam deck and installed NSL. The launchers all seem to work just fine, but when I open games, all controls stopped being recognized after the first 10 seconds or so. I’ve only tried GOG and Itchio, but the problem is present in both. Even if I launch the games straight from the steam library. I have the most up to date version and I already tried restarting NSL Game Scanner and updating everything I could and that didn’t help.

**Comment by moraroy** [comment]
@emosludge that code has been removed for the time being, there is no code anymore that sets controller profiles... you need to edit them yourselves, for all the launchers I personally just use the template "Web Browser". It works very well.

**Comment by moraroy** [comment]
@emosludge also that's very strange that shouldn't be happening??

**Comment by emosludge** [comment]
I tried all the controller template profiles in steam and they all had the same result of stopping working after a few seconds. :-/

**Comment by moraroy** [comment]
:( I'm not too sure what would be causing that are you sure it's NonSteamLaunchers? Do me a favor try stopping the NSL Games scanner see if that helps

**Comment by emosludge** [comment]
Stopping NSL Game Scanner worked! Thank you for your help!
