### ISSUE TITLE
 [Bug] Cannot install Rockstar Games Launcher

### ISSUE THREAD

**Issue by short-circuit** [moraroy/NonSteamLaunchers-On-Steam-Deck#375]
Using separate prefixes, Rockstar Games Launcher refuses to install correctly. 
[nohup.out.log](https://github.com/user-attachments/files/16514473/nohup.out.log)

**Comment by moraroy** [comment]
@short-circuit should be fixed?

**Comment by short-circuit** [comment]
Yes, it works correct after the PR I made :)

**Comment by moraroy** [comment]
@short-circuit sweet thanks for the catch brother! Good job!
