### ISSUE TITLE
Steam shortcuts are not linked correctly to the launcher executables

### ISSUE THREAD

**Issue by Dartis4** [moraroy/NonSteamLaunchers-On-Steam-Deck#38]
When running the script as is, the installation of the launchers works fine, however the steam shortcuts that are created are pointing to the wrong executables or just generally an invalid path. Everything is very hardcoded as well which limits the flexibility of the script for use on other linux systems that are not the steam deck or non-default usernames on the steam deck. When they are linked to the wrong place, you also can't select a steam compatibility layer in the menu. I was able to just browse and select the correct executable, so obviously the hardcoded path is just incorrect and needs to be changed to the correct one. It should be the same executable that is pointed to by the desktop shortcuts on Windows, just within the given prefix, which might change depending on the "separate app id" menu selection. The steam shortcuts did not work when running the script in both cases, so the pathing needs to be fixed for both options.

**Comment by moraroy** [comment]
@Dartis4 this seems like something new that has happened... could you show  me your log file? youre the first to describe this bug! thank you for reaching out and letting me know!

**Comment by moraroy** [comment]
@richardestes i see, well ill be able to help you as soon as you show me your log so i can see whats going on.. NonsteamLaunchers exports a log to a file in the downloads folder..

**Comment by richardestes** [comment]
From what it looks like, the directory is being truncated at some point? It's missing the `drive_c` directory.

EXPECTED: /home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/...
ACTUAL: /home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/Files (x86)/...

I've attached the log file as well. For future reference, the log file was located in /home/deck, not my downloads folder.

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11629166/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@richardestes hey brother how are you downloading and running the .sh file? youre error log says this at the top and throughout ... chmod: cannot access 'bash': No such file or directory.

**Comment by richardestes** [comment]
@moraroy I downloaded the latest zip from the releases page. Then I extracted it to my downloads folder and double-clicked the .desktop file to run the script. I wasn't directly running the .sh file at any point

**Comment by moraroy** [comment]
@richardestes strange... @cchrkk upgraded the download page just a couple hours ago. Perhaps try the big download button now? It shouldn't give a zip anymore it should just give you the .desktop file now. I would "Start Fresh" and then delete those left over shortcuts in your library that you don't want. And then see if the script works properly. If it doesn't, it seems you may have a bash or command issue happening either in the script or on your system.

**Comment by richardestes** [comment]
Just tried again with 2.85 and still seeing the incorrect pathing issue. This is after running through the "Start Fresh" option and removing all previous shortcuts in my library. Tested with both the newest release from the GitHub page (which is still a zip file) as well as the download page that's linked in the README. Appreciate you trying to help but I think I'll end up using Lutris in the meantime!

**Comment by cchrkk** [comment]
@moraroy please don't do releases or at least write a disclaimer to not download the .sh but go on the main page and hit that huge DOWNLOAD button 😂Or when you do releases just ad the same .desktop file. It's too confusing for users I see

**Comment by Dartis4** [comment]
@cchrkk is very correct. I am a pretty savvy user and was not really able to understand or find what I was supposed to do. I downloaded the zip from the releases which is normally what you do on GitHub and just used the desktop shortcut from that. 

Here is my log file for cross-referencing as well. 
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11637802/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@Dartis4 @cchrkk @richardestes I hear you guys loud and clear and don't worry optimizing and getting these bugs cleared is the top priority right now, just today a huge number of changes were made. Thank you guys for being patient and sending these logs they are very helpful. I'm also still learning how to use github lol I never know when to do a "release" so everything a major changes happens I just do a release lol my bad guys.

**Comment by Dartis4** [comment]
A release is used for versioning. Whatever is the latest stable version that you want people to use, add it to the releases. If you just want people to download the desktop file, just put that in the release, if you want to make an executable, put that in the release. Whatever people should be downloading, that is the easiest and simplest way to give people what they need to get up and running.

**Comment by moraroy** [comment]
@Dartis4 wait so you're saying I can pick and choose what gets released file wise? Like just the desktop file. In the release? Dang I see why you guys were confused my bad.

**Comment by cchrkk** [comment]
> @Dartis4 wait so you're saying I can pick and choose what gets released file wise? Like just the desktop file. In the release? Dang I see why you guys were confused my bad.

![image](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/12370126/fb20d0c2-467e-4e69-af5e-5114a6cd3a84)
You simply add the desktop file there and idk maybe write a note in the changelog section to just download the .desktop file or just use the one you already have on desktop to use the latest version

**Comment by moraroy** [comment]
@cchrkk I see, I'd I do it like that from now on does github removed the zip files under assets? Or are those permamant?

**Comment by cchrkk** [comment]
> @cchrkk I see, I'd I do it like that from now on does github removed the zip files under assets? Or are those permamant?

I think GitHub still zips all the source code every release, I'm not a GitHub expert as well 😂

**Comment by Dartis4** [comment]
GitHub always has the zip of the full repo. You just add what ever you want as the release and people can download that. You can take a look at other repos and see what people have in their releases for examples.

**Comment by moraroy** [comment]
@Dartis4 I've been trying to stay consistent with the updates and adding the .desktop file...seems to be better right?

**Comment by Dartis4** [comment]
@moraroy looks great. Seems like things are coming along well. If the launcher linkage issue is resolved, you're probably good to close this issue. Good luck! I know myself and many others appreciate the work you're doing on the script and making life easier on the deck.

**Comment by moraroy** [comment]
@Dartis4 were you able to fix all of your issues?

**Comment by cchrkk** [comment]
> @Dartis4 I've been trying to stay consistent with the updates and adding the .desktop file...seems to be better right?

It's not working Bro. You added a .desktop.download file and It doesnt run sadly

**Comment by moraroy** [comment]
@cchrkk well when I download the desktop file from the raw it turns into .desktop.download

**Comment by cchrkk** [comment]
> @cchrkk well when I download the desktop file from the raw it turns into .desktop.download

Exactly, It should be .desktop to run. I need to check and fix because it needs thinkering right now

**Comment by cchrkk** [comment]
> @cchrkk well when I download the desktop file from the raw it turns into .desktop.download

If downloaded from the big button in the readme:

![image](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/12370126/d345a7b0-8236-483d-84d7-e287408efb84)
 VS
 If downloaded from the releases
![image](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/12370126/f722a060-cf5a-4656-a740-ba32ac7b7b8c)

**Comment by moraroy** [comment]
@cchrkk ah i see.. how would I add that button file to the release page though? When I hit download it gives me the .desktop.download instead just .desktop

**Comment by cchrkk** [comment]
You find the .desktop file and attach it to every release. It's 100% possibile, see here https://github.com/cchrkk/NSLOSD-DL/releases/tag/DlLinkFix

**Comment by moraroy** [comment]
@cchrkk gotcha thanks brother, in the next release I'll add the .desktop instead of the .desktop.download
