### ISSUE TITLE
GOG Galaxy Installing a game that starts with a number doesn't create a shortcut.

### ISSUE THREAD

**Issue by paladin181** [moraroy/NonSteamLaunchers-On-Steam-Deck#381]
Installed 9 years of Shadow with Galaxy, and it is the first game the automatic version doesn't add a shortcut for. I installed another game and it adds a shortcut. I can only speculate that it has to do with the number in the title.

**Comment by moraroy** [comment]
@paladin181 ahhh probably, I don't have that game to test :/ but, maybe look in the logs and see what it might say? Also if you can find what the shortcut is creating, then we could track down the error better but yes you're probably right

**Comment by paladin181** [comment]
Where are the logs, and I'll post here.

**Comment by moraroy** [comment]
@paladin181 in the Downloads folder, it should have a log but if you want a scanner log for the desktop version of NSL, then that will have to be ran manually i believe, you have to run this manually ${logged_in_home}/.config/systemd/user/NSLGameScanner.py" right click it and go to properties and make sure it is set to executable and then right click it again, and RUN in Konsole

**Comment by paladin181** [comment]
What about the Decky Loader version?

**Comment by moraroy** [comment]
@paladin181 oh my bad i thought you were doing desktop version, in that case, the logs would be located here /home/deck/homebrew/logs/NonSteamLaunchers/

**Comment by paladin181** [comment]
[2024-08-09 18.37.05.log](https://github.com/user-attachments/files/16568022/2024-08-09.18.37.05.log)
Here is the log from today.

**Comment by moraroy** [comment]
@paladin181 hey brother i think the reason is because you need to update the nonsteamlaunchers plugin in the decky testing store

**Comment by paladin181** [comment]
You're right. Thanks.
