### ISSUE TITLE
Battle.net not installing/not added to steam

### ISSUE THREAD

**Issue by AquaFoxxx** [moraroy/NonSteamLaunchers-On-Steam-Deck#392]
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16623875/NonSteamLaunchers-install.log)
Hey, i am using your newest version of the launcher (downloaded today).
if i want to install Battle.net it says downloading and installing and afterwards Steam is closing and opening again. But nothing is added to steam. I think battle.net was not installed.

i had Battle.net installed until last week. Because of some download issues i wanted to install it newly with your launcher.

Please see attached my log.

Thank you especially for your hard work!

**Comment by moraroy** [comment]
@AquaFoxxx you need to delete the NonSteamzlaunchersfoldwr in compatdata and re-install proton GE, thentry to install it again.

**Comment by AquaFoxxx** [comment]
Thank you now it is working :)!

i reinstalled the GE before so i think the Problem was the File in die compdata folder!

Thanks a lot for your help!
