### ISSUE TITLE
Please remove Bazzite from the supported section of your readme.

### ISSUE THREAD

**Issue by KyleGospo** [moraroy/NonSteamLaunchers-On-Steam-Deck#393]
Hi, I am the founder and lead developer of Bazzite.

I would like Bazzite removed from your readme. We do not support running multiple launchers or multiple games from one launcher under a single prefix and as such we do not want to deal with support requests from your project.

We've already had to explain this to numerous people who've come to us for game support and left disappointed because they had to remove their entire library before we'd offer any support.

Thank you.

**Comment by moraroy** [comment]
@KyleGospo what seems to be the technical issue?

**Comment by KyleGospo** [comment]
> @KyleGospo what seems to be the technical issue?

I answered on Reddit but I will re-explain here. 

NonSteamLaunchers is the only wine prefix manager that uses a single prefix for all launchers, or optionally a single prefix for each launcher. 

We do not support this. That is a ticking time bomb where every time you install something new you risk breaking things you've installed in the past. We've had users come to us asking for support and our answer to them is always "Please uninstall non-steam launchers and all games installed with it. Afterward we can help you set it up the right way."

Having Bazzite listed as supported in your readme breeds confusion, because they will then go back and look at the readme and not understand why it is we are telling them not to do it.

I appreciate your understanding.

**Comment by moraroy** [comment]
Could explain this ticking time bomb that you are speaking of and provide proof of a video game that is going to cause such destruction? I have never come across a video game that broke something ive installed in the past can please provide a source of your claims and the video game that is causing this issue?

**Comment by KyleGospo** [comment]
It's been explained to you many times in the past. Please remove my project from your readme.

**Comment by moraroy** [comment]
@KyleGospo why do you keep saying that? And why cant you name the game or application? Haha

**Comment by KyleGospo** [comment]
> @KyleGospo why do you keep saying that? And why cant you name the game or application? Haha

I am not interested in rewriting this project, all I'm interested in is ending support requests from your users toward my distro. 

It does not benefit you to have Bazzite listed in your readme when we are instructing people to uninstall this project every time they come to us.

**Comment by moraroy** [comment]
@KyleGospo no one is telling you to rewrite anything..... but sure ill remove your name from it, just to let you know, i put added bazzite to the read me because i found a youtube video that clearly showed NonSteamLaunchers being installed on Bazzite. Heres the video https://youtu.be/dyC69Pa0OUI?si=1CPQ8J90MFsBbXbd unlike you, i have proof. Next time try to provide yours.
