### ISSUE TITLE
RemoteplayWhatEver in Decky Plugin

### ISSUE THREAD

**Issue by Kamikaze01git** [moraroy/NonSteamLaunchers-On-Steam-Deck#395]
What about [RemotePlayWhatever integration](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/releases/tag/v3.8.8) from Desktop Version?  :)

**Comment by moraroy** [comment]
@Kamikaze01git could you do me a huge favor, could you check and test if that current version works on the deck, wasnt sure if the latest version wss compatable since steam was updating

**Comment by Kamikaze01git** [comment]
Hello.

I am on Steamdeck Stable Version 3.5.19 and installed the DeckyPlugins 2.12.3.
The NonSteamLauncher plugin version 1.0.0 installs the launcher and streaming pages that I've tested without any problems. There were only problems with the manual scan when creating the corresponding shortcuts.

After I restarted the scan via the desktop script, it worked. Even after I switched to “autoscan” in the plugin, the links were added correctly.

When uninstalling, nearly all launchers were removed as desired, but only Humble could not be uninstalled via the Decky plugin. There was no error message, there was even a message that it was successfully uninstalled. But I was able to start Humble afterwards without any problems. Uninstalling via desktop script was no problem.

When uninstalling something, in general it would be desirable for the shortcuts to be removed automatically (or at least an indication that this should be done manually).

The "RemotePlayWhatever" mentioned in the first post above would also be great if you could install and uninstall it via the DeckyPlugin (I have to admit, I have [no idea how to uninstall this RemotePlayWhatever](https://github.com/m4dEngi/RemotePlayWhatever/issues/143) again...).

**********

In the end, all that's left for me to say is what a great job you've done here. Many thousands of Steamdeck users are extremely happy about this convenient option to install all launchers in a single Proton folder.

I couldn't start RDR2 via Epic (error message on the deck that the graphics drivers need to be updated), but had to start it via R* Launcher, which in turn could only recognize the game in Epic because both launchers are in the same Proton folder.

Anyway: THANK YOU VERY MUCH. FANTASTIC JOB!!!!!!

**Comment by moraroy** [comment]
@Kamikaze01git WOW thank you for the kind words i really appreciate it!, i hope you have been able to game a little easier! NonSteamLaunchers isnt perfect by any means, and its definitely been a tough road haha. But thank you, Your comment on all the other issues is great information that is very helpful. ill try to fix the sxanner in the upcoming versions, and thats strange the humble isnt uninstalling, ill take a look at that. When it comes to remote play i havnt added it yet because i wasnt sure if the latest version of remote play is working yet with the new steam update. As far as uninstalling it good question! there is actually nothing to "Uninstall" as im downloading the file directly. So in order to get rid of it i believe its in the home/deck/.local/share/applications/ should be two files , a .desktop file and the remoteplay whatever that you could delete. I hope ive been able to allow people to play their games alittle better. Alot of people dont like the onew prefix idea, but thats ok. thats why there are many other options to choose from!

**Comment by Kamikaze01git** [comment]
Hello.

yeah. It is actually currently the absolute best (and most convenient) way to install the launchers. And with the Decky plugin you will now delight many more players with it.
Valve should think about integrating your script in general 😄

And thank you VERY MUCH for the tip on how to uninstall RemotePlayWhatever. Unfortunately, I have massive problems with RemotePlay (together or whatever). But I'll have to test this more carefully when I get a better fiber optic with 275/100 this week.

If you need further tests, just get in touch. I'm happy to help if I can.

Keep doing what you do 😎🤜🏼🤛🏼

**Comment by moraroy** [comment]
@Kamikaze01git i fixed the desktop versions for the uninstalltion of remoteplaywhatever you should be able to uninstall  it now with the .desktop file. Remote Play whatver is very finicky on the steam deck in game mode, there is a certain wa to use it, but i did test it this week and seems to work fine

**Comment by Kamikaze01git** [comment]
wow !!
Thank you very much for this information. I tested it straight away and uninstalled RemotePlayWhatever with your .desktop file and reinstalled it immediately again.
Everything works perfectly :-))

Can't I ask what you meant by the "certain way" to use it?

As far as I understand it, you have to
1) first start an instance of RPW,
2) then start any game and
3) then generate and send a link via RPW.

This is extremely tedious in desktop mode without a keyboard :)

But no matter: this is about YOUR great work and the NonSteamLauncher. This is an essential tool for all Steamdeck owners!!
I can't say it often enough: THANK YOU for everything and your great work!

**Comment by moraroy** [comment]
@Kamikaze01git wow tha k you for the support! But yes, what i mean is you can use RPW in game mode and invite your friends in game mode to play NonSteam Games over steam, its just a bit of a "keyboard hassle" to do it in game mode, i tested this week and played a game from epic games with a other computer and worked just fine, this means you can do local co-op online with other people in game mode without needing the game!
