### ISSUE TITLE
Epic Games DLC shows up in Steam games list

### ISSUE THREAD

**Issue by Kosai106** [moraroy/NonSteamLaunchers-On-Steam-Deck#399]
Maybe I missed some configuration but I recently updated to the latest version of the tool, and now my DLC for Hitman 3 has started to show up as individual games in Steam even though they shouldn't.

It's a bit frustrating <sup>and time consuming</sup> to remove them after each time I run NonSteamLaunchers.

(Sorry for being lazy and not taking a direct screenshot)

<a href="https://github.com/user-attachments/assets/b75e376a-e7c5-4e3c-b723-8453377d2440"><figure>
  <img src="https://github.com/user-attachments/assets/b75e376a-e7c5-4e3c-b723-8453377d2440" alt="Example" style="width:100%" height="300px">
  <figcaption>Example: Click to see full size</figcaption>
</figure></a>

**Comment by moraroy** [comment]
@Kosai106 wow thats alot, and this is for epic games launcher correct?

**Comment by moraroy** [comment]
@Kosai106 and youre on plugin or desktop?

**Comment by Kosai106** [comment]
@moraroy Yeah it's a bit much lol

I've primarily used the desktop script which causes this, but I just confirmed the issue also happens when using the plugin version.

**Comment by moraroy** [comment]
@Kosai106 ok thank you, basically the NSLGameScanner.py in the desktop and the NSLGameScanner.py needs more logic to prevent those for the epic games launcher, ill do my best over the next days to fix it, if you use the plugin try to use manual scan for now i guess

**Comment by Kosai106** [comment]
@moraroy No worries, thanks. I'm not very familiar with Python but let me know if I can be of assistance in some way.

**Comment by moraroy** [comment]
@Kosai106 hey brother, let me know if that fix helped, i just updated the desktop version. Hit Stop Scanner and then when it asks to restart press yes and that should let the scanner update to the latest fix, make sure you delete your other entries to test even the orginal game to make sure i didnt break anything
