### ISSUE TITLE
Add a way to move the launchers and the games to the SD card

### ISSUE THREAD

**Issue by roydbt** [moraroy/NonSteamLaunchers-On-Steam-Deck#4]
Basically what the title said.
I don't know if I can just move the `compatdata/NonSteamLauncher` to the SD card and rewrite the shortcuts in the Steam library and everything would work, and I don't want to break the whole setup just to find out. After all, the SD card also has a folder named `compatdata` for the same purpose as the main one, I presume.

**Comment by roydbt** [comment]
So apparently copying the whole folder to the SD card works (of course you need to change the shortcuts in the library).

**Comment by moraroy** [comment]
@roydbt im already working on this feature

**Comment by cchrkk** [comment]
@moraroy You should close issues you have completed 😅 Is this completed right?

**Comment by moraroy** [comment]
@cchrkk true! closing now!

**Comment by do-kevin** [comment]
The feature move to micro sd doesn't work for me. I wanted GOG in my micro sd

**Comment by moraroy** [comment]
@do-kevin its legacy code right now as I no longer have an sd card and cant test anything :(

**Comment by do-kevin** [comment]
I can do an 1 time sponsor in February so you could buy 1. I can't figure out why GalaxyClient.exe won't launch from my microSD despite using Proton Experimental or such

**Comment by moraroy** [comment]
@do-kevin Attempted a fix for the SD Card just now in the new release using NonSteamLaunchers.desktop. Feel free to try, not sure about Gog yet. Maybe its not installed fully or any paths broken that you can see?
