### ISSUE TITLE
Battle.net Stuck

### ISSUE THREAD

**Issue by gfrcr** [moraroy/NonSteamLaunchers-On-Steam-Deck#407]
Hello Ive installed bazzite on my rog ally and im trying to download battle.net but every time ive tried i wa stucked on “Updating Battle.net Update Agent… (45%)” , iv tried to reinstall proton ge but istill the same issue

**Comment by moraroy** [comment]
@gfrcr cool thank you brother for reaching out, do you mind if you pload your log, it should be in the Downloads folder

**Comment by gfrcr** [comment]
@moraroy 
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16770717/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@gfrcr thank you brother will, update you as soon as i put in the fix, thrn you could run the .desktop file ill let you know

**Comment by moraroy** [comment]
@gfrcr alright bro you can go ahead and try. make sure youre using the latest .desktop File, let me know if battle net installs correctly, also, please let me know if any windows were left "open". i also want to know if all the battlenet windows closed once the installation was completed. i dont have bazzite so i have no idea whats going on it haha

**Comment by moraroy** [comment]
@gfrcr were you able to test this fix?

**Comment by gfrcr** [comment]
@moraroy Im so sorry, i didnt have enough time to test it, but ill asap !

**Comment by moraroy** [comment]
@gfrcr no worries brother take your time no rush!

**Comment by mckinnsb** [comment]
I'm seeing this also on the Steam Deck, I do a fresh start/clean the directory, update Proton, restart steam, and when I try to install Battle.net, it gets stuck at 45-70% and then two windows open; one saying that it can't open the Update Agent, and another one saying another instance of the installer is already open.

**Comment by moraroy** [comment]
@mckinnsb can you upload your log?

**Comment by mckinnsb** [comment]
Yep, give me a day or two
