### ISSUE TITLE
HoYoPlay launcher doesn't install

### ISSUE THREAD

**Issue by WojTechnical** [moraroy/NonSteamLaunchers-On-Steam-Deck#408]
Basically what the title says - latest version of NonSteamLaunchers(v.3.9.3), I select HoYoPlay to install, then nothing happens. Looking at the log it says that the file with that name cannot be found - it looks like the installer has a different name than the one expected.

**Comment by WojTechnical** [comment]
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16789555/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@WojTechnical OOOPS, i made a mistake last night when i was updating, ill fix it in a few hours

**Comment by moraroy** [comment]
@WojTechnical allright bro, sorry about that, i just added the fix into the .desktop version, let me know how it goes

**Comment by WojTechnical** [comment]
@moraroy just tried it - works fine now. Thanks for the super quick resolution!
