### ISSUE TITLE
Migrating desktop version install to Decky plugin version

### ISSUE THREAD

**Issue by cardcathouse** [moraroy/NonSteamLaunchers-On-Steam-Deck#409]
I am currently running the desktop version, but I want to switch to using the decky plugin  as it seems easier to use and manage. Is there any way to migrate my launcher installations, preferably without having to uninstall any of my games? Currently have all launchers on a single prefix

**Comment by moraroy** [comment]
@cardcathouse theres no need to do anything just download the plugin, it should be seamless
