### ISSUE TITLE
Stuck at Detecting, Updating and Installing Proton

### ISSUE THREAD

**Issue by PvtKlemmer** [moraroy/NonSteamLaunchers-On-Steam-Deck#41]
Hello
Tried both the latest version and the one from a couple days ago. I chose only Uplay and Epic Launcher to install. But the installer is stuck at "Detecting, Updating and Installing GE-Proton" and nothing is happening. 
Tried multiple times and also tried restarting the Steam Deck. 
Haven't done anything except choosing a password and installing Decky.

**Comment by moraroy** [comment]
@PvtKlemmer I'm sorry to hear this brother! Do you mind sending the log file? It should be in the the same directory as the desktop file.

**Comment by PvtKlemmer** [comment]
Here are the last 3 attempts
file:///home/deck/Desktop/wget-log
file:///home/deck/Desktop/wget-log.1
file:///home/deck/Desktop/wget-log.2
file:///home/deck/Desktop/wget-log.3

**Comment by WolfMad** [comment]
have you used ProtonUp-Qt to install GE-Proton 8-3 or manually installed GE-Proton 8-3 
on desktop Linux i reamed /home/UserName/.local/share/Steam/compatibilitytools.d to compatibilitytools.d.old then crated a new compatibilitytools.d folder

**Comment by PvtKlemmer** [comment]
No I haven't used ProtonUp-Qt nor have I knowingly installed GE-Proton 8-3.
Under the compatibility settings, the newest it's showing me is 8.0-2
Tried renaming the folder and creating a new one but the installer still got stuck at the same point with nothing happening

**Comment by WolfMad** [comment]
hi
looking at the wget-log it looks like the Connection is getting timed out

this will download to /home/user/Downloads/Proton 
Test 1 does the file download work if not what return codes do you get and what errors do you get
Test 2 this disable all timeouts this may help in downloading the file if not what return codes do you get and what errors do you get

Test 1
wget https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-3/GE-Proton8-3.tar.gz ~/Downloads/Proton
RETURN=$?
echo "the return codes is"
echo $RETURN

Test2
wget  --timeout=0 https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-3/GE-Proton8-3.tar.gz ~/Downloads/Proton
RETURN=$?
echo "the return codes is"
echo $RETURN

**Comment by moraroy** [comment]
@WolfMad @PvtKlemmer were guys able to trouble shoot this? When I wrote the code I tried to automatically grab GE's latest with using the github app. But Githubs api seems to be broken and the the .tar files wouldn't extract on my system for some reason so I had to resort to downloading each release via the release page.

**Comment by PvtKlemmer** [comment]
@moraroy Sadly not. Downloaded the proton thing that wolf provided and also the newest NSL release from here. Still stuck and didn't even get any log files this time. 
Weird though, I just got the Deck on tuesday and haven't done anything to it except downloading Decky and some games from the steam store.

**Comment by moraroy** [comment]
@PvtKlemmer hey have you set up your username and password on your deck yet? Like in konsole?

**Comment by PvtKlemmer** [comment]
Hey, I changed the Deck name in gaming mode, under settings. 
In desktop mode I set a password, then it also asked me to set some KDWallet (not sure if I remember that name correctly) password. But I didn't touch the username in desktop mode

**Comment by moraroy** [comment]
@moraroy that may be what's causing the issue on the bottom of your log it says username/authentication failed... I'm trying to think about this, perhaps since you have changed ged the "default name" it may not be able to load the .sh file correctly. I'm researching this as we speak.

**Comment by WolfMad** [comment]
you may need to reset the steam deck back to the factory defaults there may be a problem with the wifi access point do you have a ethernet to USB C adaptor?
I do not think "changed the Deck name in gaming mode" is the problem 

what do you get when you run Test 1 and Test 2?

**Comment by moraroy** [comment]
@WolfMad this error may also be attributed to the "Nonsteamlaunchersinstallation" folder not being checked and wiped before the script is ran

**Comment by Teravibes** [comment]
I seem to have the same issue. I did also change username/psw in the past if it matters.

**Comment by PvtKlemmer** [comment]
> I seem to have the same issue. I did also change username/psw in the past if it matters.

I did a factory reset a couple days ago. Didn't change the username or anything. Still the same issue

**Comment by JKelloggs** [comment]
Currently getting this issue

**Comment by moraroy** [comment]
@JKelloggs can you provide the log?

**Comment by JKelloggs** [comment]
> @JKelloggs can you provide the log?

I’ve tried locating the logs but I can’t find the path to them. Can you help me out? Thanks

**Comment by JKelloggs** [comment]
I’ve just been successful for the first time after testing across yesterday.

I was moving the files to my desktop which wasn’t working it seems. Ran it from the downloads folder and it started to populate a folder with the proton files etc. and actually proceeded with the installations.

**Comment by moraroy** [comment]
@JKelloggs wow I need to fix that... tha k you for being patient and finally finding out why it wasn't working I'm sure many people have been wondering why haha dang man I'm sorry, I'm still new to all this coding I'm sorry about that

**Comment by PvtKlemmer** [comment]
> I’ve just been successful for the first time after testing across yesterday.
> 
> I was moving the files to my desktop which wasn’t working it seems. Ran it from the downloads folder and it started to populate a folder with the proton files etc. and actually proceeded with the installations.

Thank you very much, worked for me too. Didn't even think of trying that before I saw your post

**Comment by PvtKlemmer** [comment]
That's okay, stuff like that happens

**Comment by JKelloggs** [comment]
All good, that’s what the issues is for! Glad I could help!

**Comment by cnctrasher** [comment]
Unfortunately i got the same issue and to execute the file on the Desktop or in download folder let it both stuck at detecting, updating and installing.

**Comment by moraroy** [comment]
@cnctrasher still looking into the issue... it may be because the NonSteamInstallation folder isn't being checked correctly.

**Comment by cnctrasher** [comment]
@moraroy okay, do you got an Idea for a workaround or something? Also tried older Versions too, execute from Desktop and download folder, but nothing seem to work for me.

**Comment by knorrre** [comment]
> @moraroy okay, do you got an Idea for a workaround or something? Also tried older Versions too, execute from Desktop and download folder, but nothing seem to work for me.

Same here. :(

**Comment by 187Rival** [comment]
Hello friends, i tried to install, but still stuck at the update of proton....
Is there a way to install Uplay with an other Method ?
Thanks

**Comment by wolf-hook** [comment]
I had this issue as well, resolved it by installing Proton GE manually using "ProtonUp-Qt". Once it was installed I was able to install EA app via NonSteamLauncher.
