### ISSUE TITLE
Battle.net not downloading

### ISSUE THREAD

**Issue by itzzjd123** [moraroy/NonSteamLaunchers-On-Steam-Deck#418]
I have tried to download battlenet through decky loader on games mode plug-ins and also I have tried the nonsteamgames launcher on desktop mode and it downloads but doesn't show in my non steam games library after download. Is there a file I can go to to add it to my steam library?

**Comment by itzzjd123** [comment]
Got it to launch now but the keyboard won't show up for me to login... anyway around that to bring up keyboard??

**Comment by moraroy** [comment]
@itzzjd123 I'm glad you got it working....do you mind doing me a favor? Can you also test the latest version of the plug-in in the testing store?

**Comment by itzzjd123** [comment]
Yeah can you tell me step by step how I do that please

**Comment by itzzjd123** [comment]
@moraroy
