### ISSUE TITLE
Can't login to Ubisoft Connect

### ISSUE THREAD

**Issue by ZobaJakColbert** [moraroy/NonSteamLaunchers-On-Steam-Deck#432]
I'm trying in Desktop Mode to login to Ubisoft, but I've got error: An error occurred while trying to send your request. Please try again later.

![Screenshot_20240916_150652_1514620753_RustDesk](https://github.com/user-attachments/assets/6e39ede8-1cd9-4b3e-ab7d-80ad42ed2478)

**Comment by moraroy** [comment]
@ZobaJakColbert this doesn't have anything to do with NonSteamLaunchers brother, either ubisoft is down or your credentials aren't right or you need to restart your internet.

**Comment by chrisday144-maker** [comment]
Same Thing Hile Crating an Account on desktop
