### ISSUE TITLE
Launchers won’t open

### ISSUE THREAD

**Issue by Peternbrown** [moraroy/NonSteamLaunchers-On-Steam-Deck#436]
Installed via desktop mode 2 days ago to use Ubisoft Connect. I was able to use Ubisoft launcher one time successfully. 

Suddenly the launcher won’t open when clicking play in Game mode. It starts playing and then immediately closes. I tested this and same thing happens in desktop mode. I did a fresh start and reinstalled. I also hit fresh start and then redid the install using the Decky plugin instead. All exhibit the same issue. The same thing happens with Battle.net launcher. Apps are forced compatibility with GE 9-13. I tested all proton GE too.

**Comment by moraroy** [comment]
@Peternbrown turn off the scanner. Open up the desktop file and hit stop Scanner and then restart steam. Alternatively, and a much better way to do things currently is this. Download Decky Loader, and install the testing store version of NonSteamLaunchers. Install your launchers using the plugin... and then.... jump into desktop mode with the scanner on. You will be able to have real time shortcuts in Desktop mode, no longer needing to restart steam for anything. Here's a video: https://youtu.be/CJKyaPIeeKs?si=y4oK6pjcedqjg-9w

**Comment by moraroy** [comment]
Fixed
