### ISSUE TITLE
External controllers don't work!!

### ISSUE THREAD

**Issue by ralmoued** [moraroy/NonSteamLaunchers-On-Steam-Deck#438]
Hi, I have installed [NonSteamLaunchers-On-Steam-Deck to my steam deck. Then I added "Epic games" and start working there. it works perfectly via builtin controllers, but once I connect to external controllers (which recognized perfectly by steam deck games), once I open any game from epic the external controllers stop working!!
It this bug? Or is there some setting need I to do to support external controllers? Please help

**Comment by moraroy** [comment]
It's not a bug, if you're using external controllers  on the steam they have their own controller profiles separately from the steam deck you just have to change them because they are probably on gamepad layout

**Comment by ralmoued** [comment]
OK I see, thanks, I have change the layout, but fount something else.. that once  I start the launcher with a X-Controller then launch a game I will have access only via X-Controller but not the other controllers or even not bia builtin steam controller!! As well if start via builtin Controller other external controllers will not work!! It is not the case via native steam games. Is it something related to settings? or the launcher?

**Comment by moraroy** [comment]
@ralmoued why not use the shortcut of the game NSL created for you? That way you use controller/gamepad? Turn on scanner

**Comment by ralmoued** [comment]
What shortcut? Can I get game shortcut of Epic games in steam game mode?

**Comment by moraroy** [comment]
@ralmoud yes you can that's what the scanner is for open up the desktop file to restart the scanner.

**Comment by ralmoued** [comment]
Excuse my ignorance and Please have a little patience what is scanner? where to find it. You are telling to open up the desktop file!! what is that as well?
