### ISSUE TITLE
NSL decky plugin won't update GE-proton.

### ISSUE THREAD

**Issue by mrboomblaster** [moraroy/NonSteamLaunchers-On-Steam-Deck#440]
I'm still on GE-proton 9-11. Tried reinstalling the plugin and restarted my steam deck but it won't update to latest version, currently 9-14.

I don't know what I'm doing wrong.

**Comment by moraroy** [comment]
@mrboomblaster for now use a plugin called Wine Cellar.

**Comment by mrboomblaster** [comment]
> @mrboomblaster for now use a plugin called Wine Cellar.

Ah oke, thanks. I was using protonqt to update it but figured this is much easier. Will use wine cellar for the time being.

**Comment by moraroy** [comment]
@mrboomblaster currently in the plugin it only updates the ge proton for you if you re-install a launcher. In order for proton ge to be recognized by steam, steam needs to also be restarted.

**Comment by moraroy** [comment]
Fixed
