### ISSUE TITLE
Does not install Gog

### ISSUE THREAD

**Issue by IRequireAssistance89** [moraroy/NonSteamLaunchers-On-Steam-Deck#442]
I have tried installing GOG Galaxy multiple times. It seems to work just fine during the installation process, but when steam launches afterward, it does not show up in the library. Itch.io installs correctly.

Edit: Both logs are identical, I accidentally attached it twice.

Logs attached.
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/17174082/NonSteamLaunchers-install.log)
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/17174084/NonSteamLaunchers-install.log)

**Comment by IRequireAssistance89** [comment]
Update. I have tried stating fresh, updating Proton GE, and re-downloading GOG galaxy, aswell as Itch.io multiple times.
Still no dice, it only installs itch.io. is seems to connect to gog and download it, but it does not show up anywhere afterwards. Log attached
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/17174163/NonSteamLaunchers-install.log)

**Comment by 117EM** [comment]
Same issue with GOG. Tried both decky loader plugin and desktop installer. Makes no difference. On desktop I see the GOG installer launching for a split second then closing immediately. On decky I just get the notification that the installation was succesfull. In both cases GOG does not appear in steam. Installed Chrome as well after reading it is mandatory for GOG installation.

**Comment by moraroy** [comment]
@117EM @IRequireAssistance89 working on a gog fix, thank you for your patience and logs.

**Comment by moraroy** [comment]
@117EM @IRequireAssistance89 this has now been fixed in the desktop version, will be adding this fix into the plugin version but that will take time, ill try to push it to the testing store as quickly as possible happy gaming brothers and sisters!

**Comment by IRequireAssistance89** [comment]
Thanks For the quick fix. It works great!
