### ISSUE TITLE
Epic Game Launcher error "Assertion failed"

### ISSUE THREAD

**Issue by ralmoued** [moraroy/NonSteamLaunchers-On-Steam-Deck#446]
From time to time when I run Epic games launcher (added from NSL) in game mode, I got following error:
![Skärmbild 2024-09-29 191709](https://github.com/user-attachments/assets/aa093a4f-16e3-442c-8e1f-ec246e12d354)

The only way is to switch back to desktop mode then back to game mode and run the launcher again. But it is annoying and start to happen almost every time.
For Compatiblity, I am runing the launcher using GE-Proton9-13

**Comment by moraroy** [comment]
@ralmoued have you tried reinstalling epic?

**Comment by ralmoued** [comment]
Not really. Should I do it? Should I do it by running"nonSteamLauncher.desktop" and select Epic games? that is all?
Will I lose my installed games from Epic launcher? 
Does it matte what Proton version to select?
I made search about this error and found some result, but I am not sure about them, like:  Install DXVK and Vulkan and Wine dependencies are installed.

**Comment by moraroy** [comment]
@ralmoued try reinstalling firet. It won't effect anything whether you use the plugin or desktop version. Don't Uninstall it though, just reinstall. NSL will automatically install the latest proton GE then steam will need to be restarted to select ge proton 15 see if that fixes it first.

**Comment by ralmoued** [comment]
OK I did it, but it didn't solve the issue.  now I think I know how to reproduce the issue.. simply once I open any Nintendo switch via emulator Ryujinx then close it and open Epic launcher, then I will get that error. reboot the steam deck will not help, only switch to desk mode and the to game mode helps

**Comment by moraroy** [comment]
@ralmoued dang that's weird :/ it kind of sounds like an environment variable issue that's being set for the deck... will need to investigate further!

**Comment by ralmoued** [comment]
Who should investigate you or me?

**Comment by moraroy** [comment]
@ralmoued both of us, I don't have emudeck or anything lies that installed so I have to install and see why it's doing that.

**Comment by GreatWiz** [comment]
I had this issues, tried running the nonSteamLaunchers script and reinstall epic, and now both epic, gog and their games stopped working. uninstall/reinstall doesn't do anything. Resintalling ProtonGE also doesn't do anything

**Comment by moraroy** [comment]
@GreatWiz i think its an environment issue, as i cant replicate that error on my deck

**Comment by GreatWiz** [comment]
Any pointers as to what to check? I can check, and let you know

**Comment by GreatWiz** [comment]
Ok it seems like the hardlink points to `.../compatdata/4206469918' while the actual dir is `.../3838887677`
I've tried manually updating the hardlink, but something resets it back to the non existing `4206469918` dir
any pointers as to what I should look at next?

**Comment by moraroy** [comment]
@GreatWiz it's the scanner doing that, press stop scanner and you should then be able to change it. The coding isn't that great when it comes to symlinking and I still have yet to fix it.

**Comment by GreatWiz** [comment]
yea I did stop and restart the scanner. it didn't help. only renaming the dir to the name the scanner decided worked. I guess the scanner has cached variable that doesn't refresh?

**Comment by dontsnm** [comment]
Same issue in my deck. I try to unnistall and to update to test version, but no way. 

In desktop mode is working fine.

**Comment by GreatWiz** [comment]
@dontsnm did you try my solution? changing the folder name to the one specified by the hardlink? Or is it a different issue

**Comment by dontsnm** [comment]
> Ok it seems like the hardlink points to `.../compatdata/4206469918` while the actual dir is `.../3838887677` I've tried manually updating the hardlink, but something resets it back to the non existing `4206469918` dir changing the name of the dir to `4206469918` seens to have fixed this. Anything I can do to help you resolve this?

> @dontsnm did you try my solution? changing the folder name to the one specified by the hardlink? Or is it a different issue

My system doesn't have 4206469918 or 3838887677 folders. I'm using "separate folder" option. It runs from EpicGamesLauncher folder.

If I run the Epic Store from desktop, it runs fine, and when I return to game mode, runs fine too. But if I reboot my deck, the issue returns.

**Comment by ralmoued** [comment]
> OK I did it, but it didn't solve the issue. now I think I know how to reproduce the issue.. simply once I open any Nintendo switch via emulator Ryujinx then close it and open Epic launcher, then I will get that error. reboot the steam deck will not help, only switch to desk mode and the to game mode helps

OK, it seems I am mistaken, it is not related to Ryujinx emulator. I am still unable to replaicate the pattern of that error 100% accurate but... It starts to happened often, like if rebooting the device to let the scanner adding installed game from the launcher to game mode.. And always just switching to desktop mode then back to game mode will let me able to login to epic game launcher untill next time rebooting

**Comment by moraroy** [comment]
@ralmoued @dontsnm @GreatWiz  nvidia_drm.modeset=1 kernel parameter or maybe -dx12 command in steam

**Comment by ralmoued** [comment]
@moraroy I didn't get it!! what should we do with these parameters?

**Comment by moraroy** [comment]
@ralmoued try putting -dx12 in the launch options of epic

**Comment by ralmoued** [comment]
This is the Lunch option: 
![WhatsApp Image 2024-10-23 at 15 36 37](https://github.com/user-attachments/assets/674ccaae-c4a1-493f-8c55-6cc7a1eb456d)
how it should be set the command?

**Comment by ralmoued** [comment]
Hi @moraroy,
This is the Lunch option:
![WhatsApp Image 2024-10-23 at 15 36 37](https://github.com/user-attachments/assets/0f5d21fd-0025-4756-b270-f2613ef3aa39)

how it should be set the command?

**Comment by ralmoued** [comment]
Hi @moraroy,
This is the Lunch option:
![WhatsApp Image 2024-10-23 at 15 36 37](https://github.com/user-attachments/assets/c7d705d8-81dc-476c-b791-20dd2232baa8)

how it should be set the command?

**Comment by dontsnm** [comment]
> @ralmoued @dontsnm @GreatWiz nvidia_drm.modeset=1 kernel parameter or maybe -dx12 command in steam

This is not working. Same error.

**Comment by dontsnm** [comment]
Seems to be fixed in SteamOS 3.6.19
