### ISSUE TITLE
NonSteamLaunchers shortcut always comes back

### ISSUE THREAD

**Issue by niklasalkin** [moraroy/NonSteamLaunchers-On-Steam-Deck#454]
I've tried uninstalling the pluging, hitting start refresh, then uninstalling again, deleting shortcut manually but the NonSteamLaunchers always returns to my library after restarting Steam or the Deck. How can I get rid of it?

**Comment by moraroy** [comment]
@niklasalkin uninstall in the launcher, then the scanner wont pick it up
