### ISSUE TITLE
Choose the browser used to make web apps

### ISSUE THREAD

**Issue by Globetrotter129** [moraroy/NonSteamLaunchers-On-Steam-Deck#462]
Id like the option to choose chrome, chromium, opera or edge so i can view 4  web apps at the same time. Or be able to open multiple instances of chrome would be better of course.

**Comment by moraroy** [comment]
@Globetrotter129 I'm going to stick with chrome for now, but I was able to do your second option in a pretty cool way! I will add this fix in the next update

**Comment by moraroy** [comment]
@Globetrotter129 actually bro i just updated the Desktop Version, feel free to delete your pre-existing streaming website shortcuts and re-add the new ones. feel free to try, here is how you use it: basically either use your finger or use the mouse somehow, but bring it to the top of the page and swipe down. you will see an "x" at the top click it, this will enable TABS. from here you can then choose whatever website you want in the same shortcut. You can also now fullscreen any page you want, on the TOP RIGHT of chrome, click the 3 vertical dots. Once clicked, look towards the middle of the chrome options you will see this, "Zoom        - !00% + | []   <--- click that square for full screen any tabs paged you want. i hope that makes sense. lol . ill be adding this to the plugin version right now as well.
