### ISSUE TITLE
EA app 

### ISSUE THREAD

**Issue by StormicalBLAST** [moraroy/NonSteamLaunchers-On-Steam-Deck#496]
The EA app is stuck on finalising.

**Comment by moraroy** [comment]
@StormicalBLAST did it eventually finish? Desktop or plugin?

**Comment by StormicalBLAST** [comment]
@moraroy nope it didn't finish, I was installing starwars squadrons.

**Comment by moraroy** [comment]
@StormicalBLAST oh bro that's an easy fix, dm me on discord @moraroy I have squadrons on my deck, it's a bit complicated steps but easy in general
