### ISSUE TITLE
Steam deck battle.net download and install seems stuck

### ISSUE THREAD

**Issue by spkuehl** [moraroy/NonSteamLaunchers-On-Steam-Deck#50]
Hello I’m trying to install bnet through NonSteamLaunchers. It is stuck on the first step “Downloading & Installing Battle.net…please wait…”

I’ve tried factory resetting my device and it is the same issue. Any others reproducing, or any tips to get this working?

Steps:
1. From Mozilla I navigated to this repo
2. I clicked the “download” button
3. I ran the script
4. Unchecked all launchers except bnet
5. Gets stuck making no progress on the status bar (image below)

![08FD64E3-B4A9-4D73-A965-78B56C5B6937](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/8636697/39572cb3-8f30-4713-913b-5897692a90a8)

**Comment by redoxeon** [comment]
Mine got so far as adding it to Steam, but it won't launch and the logs end with

```
/home/deck/.local/share/Steam/steam.sh: line 798: 33460 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
```

I did the same steps, only installed battle.net and no other programs.

**Comment by smachkovech** [comment]
Same issue as OP, same steps taken.

**Comment by spkuehl** [comment]
I dos the “start fresh” a few times and it didn’t work on retry. I’ll try again later today when I’m at the device. Thanks for feedback.

**Comment by moraroy** [comment]
@spkuehl @redoxeon @smachkovech looking into this... its weird because the code for it hasn't really changed which makes me think that perhaps a folder has in their updating of battlenet. This is the only launcher so far that seems to be stalling like this.

**Comment by WolfMad** [comment]
I have battle.net installed I installed it yesterday at 17:18:20 GMT I did not log in until today but I am not getting a notification for an update I was using 2.89 of NonSteamLaunchers-On-Steam-Deck

suggestion log a file checksum of the installers before the installer runs  this may help in determining if it is a change to the installer or a user error or maybe other software changes blocking the install

**Comment by redoxeon** [comment]
start fresh then install fixed it for me!

**Comment by moraroy** [comment]
@redoxeon @WolfMad @smachkovech @spkuehl  I might get rid of the quiet mode install of battle.net. meaning you will have to go through the install its self..... or I can get rid of the pkill  part of of the code, a window will then pop up prompting you to sign in which will be annoying but I'd rather do that then not have it install. If anyone wants to do a pull request to do that. I'm away from my computer. Also I realized the whole script will pause because I'm not checking and deleting the "NonSteamLaunchersInstallation" folder before the script is ran. Meaning the logic in the script is a little weird and I need to fix it. If the script is ran and you already have a nonstesmlaunchers installation folder in the downloads it will freeze and not work.

**Comment by spkuehl** [comment]
Tbh I’m trying to download the battle-net setup exe from blizzards website and it is failing to download (Mozilla). I can’t get it from the launcher or the official site, not sure is it’s related. The start fresh trick isn’t working and I factory reset my steam deck so I’m not sure why it seems specific to my device.

**Comment by moraroy** [comment]
@spkuehl i just updated the .sh file and removed the pkill command let me know how it goes, works for me

**Comment by LSA-username** [comment]
Hi! I have a problem with updating Battle.net launcher. If I chose at the launcher menu: “update: instal and restart” launcher was closed but nothing happened. If it possible please, fix this error. Thu so much!

**Comment by spkuehl** [comment]
Same problem with the newest version. Seems like this problem is unique to me, others in this thread with the same problem solved it with “start fresh”, not me though. Thanks for trying.

**Comment by spkuehl** [comment]
The “wget <bnet_url>” just fails for me for some reason. I can’t download it from a browser either, on steam deck. 
![image](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/8636697/0dc66099-9924-4f5f-9b99-118ac54e200f)

**Comment by moraroy** [comment]
@spkuehl I've changed the url and the file just now, it should be updated!

**Comment by spkuehl** [comment]
Sorry same problem. I don’t want to belabor this for you. I just can’t get the .exe from a request either from this program or from blizzards website. It is very strange. The download fails for me.

**Comment by WolfMad** [comment]
this may help in determining the problem you will need to create a new .sh file and paste one of the test codes into it you can then run the test you can find the URL for downloading the battle.net on line 1397 NonSteamLaunchers.sh V2.94
the problem may be 

1) permissions problems creating the NonSteamLaunchersInstallation or reading or writing into the NonSteamLaunchersInstallation folder
2) wifi access point settings isp blocking the download
3) internet connection
4) google linux troubleshooting internet connection and try some of the troubleshooting steps

this will download to /home/user/Downloads/Proton
Test 1 does the file download work if not what return codes do you get and what errors do you get
Test 2 this disables all timeouts this may help in downloading the file if not what return codes do you get and what errors do you get

Test 1
wget https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-3/GE-Proton8-3.tar.gz ~/Downloads/Proton
RETURN=$?
echo "the return codes is"
echo $RETURN

Test2
wget --timeout=0 https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-3/GE-Proton8-3.tar.gz ~/Downloads/Proton
RETURN=$?
echo "the return codes is"
echo $RETURN

the URLs in the NonSteamLaunchers.sh are on lines 1030 and 1031
wget return codes
0
No problems occurred.
1
Generic error code.
2
Parse error—for instance, when parsing command-line options, the ‘.wgetrc’ or ‘.netrc’...
3
File I/O error.
4
Network failure.
5
SSL verification failure.
6
Username/password authentication failure.
7
Protocol errors.
8
Server issued an error response.

https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html
https://www.baeldung.com/linux/wget-timeout
