### ISSUE TITLE
NonSteamLaunchers not showing in store list for Steam Deck OLED

### ISSUE THREAD

**Issue by ReneBarajas** [moraroy/NonSteamLaunchers-On-Steam-Deck#504]
Might be user error, but thought I'd check. I want to install NonSteamLaunchers and under general I've selected testing but NonSteamLaunchers does not show up, only 22 other plug ins.  I also tried Default and more plugins show up, but also no NonSteamLaunchers.  Any help would be apprieciated.  Steam Deck OLED.

**Comment by moraroy** [comment]
@ReneBarajas it's been removed from the decky plugin store... here is how to add it to your deck. Use the NSLPlugin.desktop https://github.com/moraroy/NonSteamLaunchersDecky/releases/tag/v1.0.1
