### ISSUE TITLE
Not finding games on manual scans?

### ISSUE THREAD

**Issue by CorneliousJD** [moraroy/NonSteamLaunchers-On-Steam-Deck#517]
I've installed Diablo 4 via battle.net (NOT using same prefix folder -- each launcher is separate) 

using plugin version.

manual scan doesn't find the game to add to library -- anything i'm doing wrong?

**Comment by moraroy** [comment]
@CorneliousJD sorry this took so long to fix but I believe I have somewhat fixed this issue, if you are running the Desktop Version, simply open up NonSteamLaunchers.desktop and hit "Stop NSL Game Scanner". This will stop it and it will ask to restart it, this will update the scanner to the latest version as well. If you are using the plugin please Reinstall the Plugin version by running the NSLPlugin.desktop file, this will install the latest fixes.

**Comment by CorneliousJD** [comment]
Chatted w/ you via reddit actually - sorry for double-submitting -- looks like we should be good now on that. was an issue w/ "FEN" vs "fenris" for D4
