### ISSUE TITLE
GOG Galaxy error message on first install

### ISSUE THREAD

**Issue by ivan-aws** [moraroy/NonSteamLaunchers-On-Steam-Deck#521]
when trying to run the latest version of the installation script on a clean steamdeck oled, i'm getting this error
![gog error](https://github.com/user-attachments/assets/c6c292bc-b3e2-4f63-b1b8-708ccf10fb6e)

log file attached
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/18006890/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@ivan-aws yeah that's a new error from gog can't do much about it

**Comment by ivan-aws** [comment]
ok, so probably then something that might resolve itself after a bit, right?

**Comment by moraroy** [comment]
@ivan-aws hopefully, if the error continues. I'll try to fix it myself I'll give it some time, currently if you're using GOG with nonsteamlaunchers whether decky or desktop, I would make sure the compatability is set to Steams Proton 9.0.3 for now. This will get rid of most errors.

**Comment by moraroy** [comment]
@ivan-aws ive fixed the installtion of it on both plugin and desktop.  but running the games and finishing the installs of each game may require a different proton
