### ISSUE TITLE
Gog galaxy not working

### ISSUE THREAD

**Issue by KhouryKhaos** [moraroy/NonSteamLaunchers-On-Steam-Deck#529]
I've tried installing gog galaxy from the decky plugin and desktop version and it won't show up in my library anywhere. Retarting doesn't help either. I don't see it with all the launchers in the launchers folder either.

**Comment by moraroy** [comment]
@KhouryKhaos been busy as of late, but thank you for reporting this, GOG doesn't seem to be installing now will try to fix this asap!

**Comment by moraroy** [comment]
@KhouryKhaos i believe GOG GALAXY is working , at least the installation again.
