### ISSUE TITLE
Game scanner not working with EA play

### ISSUE THREAD

**Issue by corbett3289** [moraroy/NonSteamLaunchers-On-Steam-Deck#539]
Installed the games, game scanner doesn’t pick them up at all. Unsure what to do other than play the ea play each time but this is frustrating as I need to rebind all my controls.

**Comment by moraroy** [comment]
@corbett3289 using desktop or plugin? Any logs? Should be in the downloads folder

**Comment by corbett3289** [comment]
Was using desktop. I ended up reinstalling the launcher and repairing the install and it was able to find the game then. Not sure what the issue was. But since its resolved i'll close the issue.
