### ISSUE TITLE
(Desktop mode) Amazon launcher can't enter login info

### ISSUE THREAD

**Issue by DarkenLX** [moraroy/NonSteamLaunchers-On-Steam-Deck#54]
Currently only tested in desktop mode the Login screen on the Amazon Games Launcher clicking or tapping (on screen 😅) on either of the text fields brings up the steam keyboard but also deselects the text field. Reselecting field causes the keyboard to disappear. External keyboard doesn't change the the issue. Not sure what is causing it but can't enter login info because this is all that happens text field refuse to stay selected doesn't seem like it is more than a possible glitch or bug with wine/proton but im reporting it just in case on here.

**Comment by moraroy** [comment]
@DarkenLX im going to close this because this has nothing to do with this app. This is a steam bug and is present in many cases. The keyboard sometimes cant open when proton is being ran with steam because of the overlay... thats something out of my control.
