### ISSUE TITLE
Cant Install Witcher 3 Game of The Year Editon

### ISSUE THREAD

**Issue by Valekj86** [moraroy/NonSteamLaunchers-On-Steam-Deck#542]
Hello,
last week I got a new Steam Deck 1TB OLED Edition.

I installed the latest non-Steam launchers plugin (Decky) from GitHub. Afterward, I set up the GOG Galaxy launcher and tried to install The Witcher 3: Wild Hunt Complete Edition. However, the installation always fails at 96% with an error message stating "installation failed."

I’ve attempted the installation several times and updated Proton to version 9.21 using the non-Steam launcher plugin.

What else can I try?

**Comment by moraroy** [comment]
@Valekj86 for now please use Ptoton GE9 -10 for all gog games and the launcher itself, very and repair that certain game and it should install.

**Comment by Valekj86** [comment]
Hello, i will try that.   Do you have a link where i can download the decky plugin?

**Comment by moraroy** [comment]
@Valekj86 Wine Cellar should be available in the Decky Loader store, no?

**Comment by Valekj86** [comment]
That worked 👍
