### ISSUE TITLE
[BUG]- When installing for the 1st time the installer does not properly add them to steam on the steam deck! [Critical] 

### ISSUE THREAD

**Issue by PS2ClassicsVault** [moraroy/NonSteamLaunchers-On-Steam-Deck#57]
Installing them is no issue but when it adds them to my steam library they fail to load in both desktop and game mode and no images as they used to, there is a very very slim chance that it will properly add them to  steam properly.

**Comment by moraroy** [comment]
@PS2ClassicsVault I just added a fix let me know how it works.. but what do you mean by images? I don't think they have ever had images...yet.

**Comment by PS2ClassicsVault** [comment]
Oh I think my plugin for images did it but  thanks for the fix hopefully it works

**Comment by PS2ClassicsVault** [comment]
> @PS2ClassicsVault I just added a fix let me know how it works.. but what do you mean by images? I don't think they have ever had images...yet.

So I tried new version it is still occuring however during setup it did get a error with gog saying something is missing.

I'm planning to reinage my deck to see if it's a deck thing before anything else

**Comment by moraroy** [comment]
@PS2ClassicsVault what plug-in do you use?

**Comment by ruineka** [comment]
> @PS2ClassicsVault I just added a fix let me know how it works.. but what do you mean by images? I don't think they have ever had images...yet.

I just used this tool for the first time and the shortcuts got added, but none of them will start in desktop or game mode.

**Comment by moraroy** [comment]
@ruineka wow ok.OK.. that's weird.. is force compatability check and using a proton?

**Comment by PS2ClassicsVault** [comment]
> 

I do try to force them but steam won't let me force them like the option won't allow to enable them

**Comment by moraroy** [comment]
@PS2ClassicsVault @ruineka make sure you guys have proton 7 installed because stesmbuses that automatically during runtime by default

**Comment by PS2ClassicsVault** [comment]
> @PS2ClassicsVault @ruineka make sure you guys have proton 7 installed because stesmbuses that automatically during runtime by default

I do have 7 installed, it installed when I launched a game

**Comment by PS2ClassicsVault** [comment]
> @PS2ClassicsVault what plug-in do you use?

Plugin?

**Comment by PS2ClassicsVault** [comment]
So I reinstalled steam os on my deck and reinstalled the script the new update think fixed where you can force the compatibility layer and they are working.

**Comment by ruineka** [comment]
> @PS2ClassicsVault @ruineka make sure you guys have proton 7 installed because stesmbuses that automatically during runtime by default

Ah I just forced proton 8 and it's now working so that must have been it. None of the shortcuts had compatibility forced.
