### ISSUE TITLE
Battle.Net won't update

### ISSUE THREAD

**Issue by DandeMC** [moraroy/NonSteamLaunchers-On-Steam-Deck#59]
Hi,
my Battle.Net launcher won't update. It shows always on the left top side the update mark and when I click on that, it close Battle.Net but nothing happens.
How can I update the launcher?

**Comment by Silviyius** [comment]
I'm also experiencing this issue, guessing this means the update is using more than what was installed from Proton, not really something the creator can account for but annoying,

**Comment by moraroy** [comment]
@Silviyius @DandeMC I've fixed battle net I changed the url and the file, should download and stay up to date

**Comment by tosj87** [comment]
What to do now? I have version 2.88. How can I update easy?

**Comment by moraroy** [comment]
@tosj87 use the .desktop file

**Comment by tosj87** [comment]
Do I have to first uninstall or just install “again” ?

**Comment by moraroy** [comment]
@tosj87 yeah Uninstall do you have any games there though, I don't want you to mess up any games you have

**Comment by tosj87** [comment]
Yeah have Diablo 4 installed? Is that a problem?

**Comment by moraroy** [comment]
@tosj87 yeah well unimstalling is going to delete everything?

**Comment by tosj87** [comment]
Can I dice the battle.net links manually??

**Comment by DandeMC** [comment]
> @Silviyius @DandeMC I've fixed battle net I changed the url and the file, should download and stay up to date

Year. Thank you! Is version 2.91 also with the Battle.Net fix?

**Comment by DandeMC** [comment]
It didn't work. I uninstalled and reinstalled batte.net. it still shows an update.

**Comment by LSA-username** [comment]
> It didn't work. I uninstalled and reinstalled batte.net. it still shows an update.

I have the same problem and the same result. In addition, Battlenet has been launching for a very long time for two days now. And like a cherry on the cake - they banned my client in Diablo 4... This is something new for Diablo... :(

**Comment by LSA-username** [comment]
When I try to update the desktop launcher, it just closes, steam continues to assume that it is running. When I run an update in a gamemode, I get this error:
![IMG_5250](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/120853024/486834ba-92da-4d19-a284-c6bb2fa03634)

**Comment by DandeMC** [comment]
> When I try to update the desktop launcher, it just closes, steam continues to assume that it is running. When I run an update in a gamemode, I get this error:
> 
> ![IMG_5250](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/120853024/486834ba-92da-4d19-a284-c6bb2fa03634)
> 
> 

After a few tests, I had the same error.

**Comment by moraroy** [comment]
@DandeMC @LSA-username I've updated to 2.94, with this update I removed the checks on all launchers meaning you can re-install them now, I've also removed the auto installation of battlenet so you have to go through the installation process yourself now, hopefully this will allow you to update battle net regularly.

**Comment by tosj87** [comment]
How can I update the launcher? Just download it and start it and ten I can reinstall Battle.net? Just that easy? Gonna give it a try !

**Comment by moraroy** [comment]
@tosj87 well if you were to select battle.net launcher in the script and you have it installed already this will hopefully give it a fresh re-install. I'm not sure if your games will be affected I don't think they will. This in turn will hopefully install it correctly and allow you to update.

**Comment by LSA-username** [comment]
ok, thanks for trying! I installed through the new launcher battelnet on top of the old version. Something has changed! Now in desktop mode, when you try to upgrade, the launcher restarts with the same error message. Now this tries to run the restart script but apparently doesn't get the new file and doesn't run the install.
![IMG_5256](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/120853024/733c21c9-1bf2-4fc0-961f-aa6b8e9ce3a8)

**Comment by LSA-username** [comment]
> @LSA-username try this https://us.battle.net/support/en/article/34719

I manually deleted everything I could find along the path local / share, etc. Together with the game files (it's good that I only have Diablo) Then I installed the launcher via NotSteam. I received a new version of the launcher, now I will download the game. I hope that when the next version of Battlenet is released, I will not have to go through this procedure again. Thanks a lot for your work and help. Have a good day!

**Comment by moraroy** [comment]
@LSA-username no problem I hope you got it resolved this is the only launcher giving people problems it seems. Hopefully they fix all these issues.. also, just FYI going forward I don't think I'll be changing the url or the battlenet file so this should be it, there is no other way to install this launcher without wine or proton and I'm not doing anything to the files during installation. So I'm not sure why it wouldn't work.

**Comment by LSA-username** [comment]
> @LSA-username no problem I hope you got it resolved this…

perhaps the game itself has a connection with the launcher, some kind of anti-cheat, etc. In the game folder, I found a hidden battlenet folder, this is the reason for deleting the game.

**Comment by moraroy** [comment]
@LSA-username I see... what's interesting is I have battlent downloaded and installed in the same way, but I have overwatch2 instead of diablo.... overwatch asks me to update and I am able to update the launcher. I'm not sure why this wouldn't be the same...but it seems like it's just as you say the games on battlenet are tied to the launcher.

**Comment by LSA-username** [comment]
> @LSA-username I see... what's interesting is I have battlent downloaded and installed in the same way, but I have overwatch2 instead of diablo.... overwatch asks me to update and I am able to update the launcher. I'm not sure why this wouldn't be the same...but it seems like it's just as you say the games on battlenet are tied to the launcher.

well, let's see what happens next, but now we need to continue killing mobs :)

**Comment by tosj87** [comment]
Quick resume. The best to reinstall it is to delete it first (launcher and game) and after that use the newest version to install everything again. Am I correct??

**Comment by LSA-username** [comment]
> Quick resume. The best to reinstall it is to delete it first (launcher and game) and after that use the newest version to install everything again. Am I correct??

Yes, that's right, it worked for me. The full path to delete the game and battlenet folders can be seen in the NotSteamLauncher.

**Comment by LSA-username** [comment]
I think installation errors (launching the old version of the launcher instead of the new one) occur for those who installed the battlenet earlier in a different way. as already mentioned here - if the battlenet does not ask you to enter a password and account during installation, if there is no language selection window, then you could not delete all the old folders and files, it's worth trying again. For me, for example, there were several places where there was a battlenet.

**Comment by M15t** [comment]
@LSA-username At least I can start D4. Got popup error, just ignore and close it lol. I guess we should wait Blizzard update their setup file then reinstall the launcher. Backup your D4 directory to a safe place btw.

**Comment by LSA-username** [comment]
> @LSA-username At least I can start D4. Got popup error, just ignore and close it lol. I guess we should wait Blizzard update their setup file then reinstall the launcher. Backup your D4 directory to a safe place btw.

D4 does not keep saves on the device, I have already deleted everything and installed it again many times, also on another device, and the account does not lose the game progress, as in D immortal

**Comment by LSA-username** [comment]
> @LSA-username so it isn’t solved yet? That’s a pitty. Then wait hopefully a new update soon. Thing the script is perfect for everything. But Battle.net is just little bit anoying now.

for me it's true. So far, this battlenet launcher is also working, but I'm afraid that in the future they will say: "we added a lot of pink to our game for real bucks and you just can't use the old launcher"

**Comment by Dergell** [comment]
I don't know why, but I just let the launcher update and it actually finished without a problem... after almost 1.5 hours! I guess the update is not broken but just takes ages.

Also, if you change the install location for games in the launcher, you can delete and reinstall without auto deleting the games.

**Comment by M15t** [comment]
> > @LSA-username At least I can start D4. Got popup error, just ignore and close it lol. I guess we should wait Blizzard update their setup file then reinstall the launcher. Backup your D4 directory to a safe place btw.
> 
> D4 does not keep saves on the device, I have already deleted everything and installed it again many times, also on another device, and the account does not lose the game progress, as in D immortal

I mean install D4 to another place then locate after reinstall Battle.net. Sighh, just try again and still the same
