### ISSUE TITLE
How do I add Amazon installed games to Steam Library?

### ISSUE THREAD

**Issue by JonAbrams** [moraroy/NonSteamLaunchers-On-Steam-Deck#6]
After installing a game using Amazon Games' launcher, I can't find it in the filesystem, and Boilr doesn't appear to see the game either.

**Comment by moraroy** [comment]
this script does not have this feature @JonAbrams also, i havnt tested this with Boilr yet

**Comment by JonAbrams** [comment]
All cool, thanks. I found it using kFind in Desktop mode.

**Comment by moraroy** [comment]
@JonAbrams Boilr is now included in the script.
