### ISSUE TITLE
Add Xbox Game Cloud

### ISSUE THREAD

**Issue by gabrielvaz** [moraroy/NonSteamLaunchers-On-Steam-Deck#60]
Could you please add the Xbox Game Cloud as a launcher?

**Comment by moraroy** [comment]
@gabrielvaz in which format? Ĺike through a web browser right? Also what about GeForce now?

**Comment by gabrielvaz** [comment]
Yes. It would be awesome, could be the same thing that Microsoft teaches on this website: https://support.microsoft.com/en-gb/topic/xbox-cloud-gaming-in-microsoft-edge-with-steam-deck-43dd011b-0ce8-4810-8302-965be6d53296 

If you think it makes sense, could be the same for GeForce Now and also for YouTube, Netflix and Amazon Prime.

**Comment by moraroy** [comment]
@gabrielvaz OK I'll add all of these.... tbh I'm not sure how I would go about downloading flatpacks automatically as that would require root and sudo passwords etc. So in order for me to do that you would have to have a browser installed already either edge or chrome

**Comment by moraroy** [comment]
@gabrielvaz Added them in the latest release!
