### ISSUE TITLE
Patching without deleting games?

### ISSUE THREAD

**Issue by KaliphV3** [moraroy/NonSteamLaunchers-On-Steam-Deck#61]
Is there a way to update or patch any launcher since this is being patched constantly for fixes? When I go to try to uninstall the launcher it wants to delete the the launcher plus all the games too, deleting 40 or 80 gb games is very time consuming is there something i'm doing wrong or a work around?

**Comment by moraroy** [comment]
@KaliphV3 the only thing I could do is remove the "check" for having a launcher installed already, I don't know if this will delete your games or not that's why I put a check to by pass if you've already installed it just goes straight to restarting steam... but I can remove the check... this will allow you to reinstall the launcher. What do you think?

**Comment by KaliphV3** [comment]
@moraroy  yes reinstalling a launcher would be amazing or patching or something

also, i'm not sure if the 2.91 fixes the battle.net patcher, as the other thread has indicated that it would not restart and patch the launcher at least for 2.90 for me, i had to redownload diablo 4 for example and any way to not reinstall games would be amazing.

**Comment by moraroy** [comment]
@KaliphV3 OK on the next update I'll remove the check... I'll also remove the automatic installation of battle net, meaning you have to go through the install process your self. I didn't want that tbh I wanted things to be automatic but I guess there is so many updates they change alot of things

**Comment by KaliphV3** [comment]
@moraroy cool, i'll look for the coming new patch, ty

**Comment by moraroy** [comment]
@KaliphV3 just updated let me know if its working

**Comment by KaliphV3** [comment]
probably will have to wait til after work, but will try out soon

**Comment by KaliphV3** [comment]
so downloaded the new 2.94, clicked battle.net checkmark, yes having them all unchecked is better, the OK option might need to be relabeled to Install, seems confusing. I've attempted at least a couple times in desktop mode and gaming mode and when I click the top right for the menu and hit the Restart and Update option, it either gives an error box or seems to time out or doesn't complete.

**Comment by moraroy** [comment]
@KaliphV3 maybe try deleting the folder just like in this article https://us.battle.net/support/en/article/34719p

**Comment by KaliphV3** [comment]
that link goes to page not found

**Comment by moraroy** [comment]
https://us.battle.net/support/en/article/34719 sorry no p

**Comment by KaliphV3** [comment]
@moraroy so under program files (x86) there is a battle.net folder, should i just delete that and then reuse the NSL to install again and see if all goes well then?

**Comment by moraroy** [comment]
@KaliphV3 yes I would try that as long as the games aren't under that folder. Let me know if this works for you!

**Comment by KaliphV3** [comment]
So did all that, but only gives error box, still restarts battle.net, but no update
![20230613_195853](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/53808197/230eea98-8759-4988-b369-6884630943d9)
