### ISSUE TITLE
Categories Broken

### ISSUE THREAD

**Issue by Raiden8816** [moraroy/NonSteamLaunchers-On-Steam-Deck#63]
(reading 'WebStorage')

Tired to install BattleNET last night using NonSteamLaunchers. However it did not create a BattleNET shortcut and has ruined all my rom organization with SRM.

Any help would be appreciated. As their GH redirected me to you guys.

**Comment by moraroy** [comment]
I'm sorry this has happened but there is nothing in the code that creates categories or collections yet. Is there a log file you can show me?
