### ISSUE TITLE
Doesn't seem to be running commands

### ISSUE THREAD

**Issue by ThiccBoi711** [moraroy/NonSteamLaunchers-On-Steam-Deck#64]
I was trying to update battle.net so I clicked start fresh and tried to reinstall it with the latest version of NonSteamLaunchers. When I click execute the console opens with the line nohup: appending output to 'nohup.out' and then the window with the launchers pop up. No matter what launcher I pick they don't work. I'm on 2.94 Any ideas?

**Comment by moraroy** [comment]
@ThiccBoi711 are you using the .desktop file?

**Comment by ThiccBoi711** [comment]
> @ThiccBoi711 are you using the .desktop file?

Yeah, that's the file I've been running

**Comment by ThiccBoi711** [comment]
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11730453/NonSteamLaunchers-install.log)
Here's the log file don't know if it helps or not @moraroy

**Comment by moraroy** [comment]
@thiccBoi711 the first line in the error log chmod: changing permissions of '/bin/bash': Read-only file system where are you running the .desktop file?

**Comment by ThiccBoi711** [comment]
@moraroy I originally downloaded the zip folder it to my downloads folder and extracted and ran it there. I just tried downloading the link to my desktop and it doesn't have the nohup.out line in the console but it ether gets stuck or says it worked even though it didn't.

**Comment by moraroy** [comment]
@ThiccBoi711 use the .desktop file dont use the zip

**Comment by Lyghfe** [comment]
The .desktop finally showed something other than "nohup: appending output to 'nohup.out'" but it still doesn't do anything in terms of downloading or whatever. Been sitting here looking at it for a few minutes now but nothing. 
Tried launching it from my download folder and the desktop, also both while steam was running and while steam was stopped and still nothing. Stuck at "Detecting, Updating and Installing GE-Proton." Folder gets created, the tar.gz file gets created but thats it. Restarting Steam Deck multiple times also did nothing.

**Comment by moraroy** [comment]
@Lyghfe can you provide the log file?

**Comment by Lyghfe** [comment]
Sure thing.  
I also forgot to mention: I got the same first error line in my logs as ThiccBoi711 did and already tried moving the file to documents, music, pictures and home folder but also to no avail. Log is from the last start in Downloads.
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11739680/NonSteamLaunchers-install.log)

**Comment by wojcham** [comment]
Hi @moraroy I used the .desktop but unfortunately I've got same error. It freeze on detecting, updating ge-proton and nothing change even after few minutes.

**Comment by ShenmueBoy** [comment]
IS there any updates to this? I am having the same issue. This use to run flawlessly. Running the .desktop file from desktop on Steam Deck
