### ISSUE TITLE
[Festure] Direct Battle.Net game start

### ISSUE THREAD

**Issue by DandeMC** [moraroy/NonSteamLaunchers-On-Steam-Deck#66]
Hello,

is there the possibility to start batte.net games directly as at https://github.com/dafzor/bnetlauncher? Directly from the steam game mode

**Comment by moraroy** [comment]
@DandeMC idk... the only difference is just the shortcut launch options right? It's still using the launcher

**Comment by DandeMC** [comment]
Yes, I think so. Is it possible for you?

**Comment by moraroy** [comment]
@briggleman @DandeMC @LiamDawe @KaeTuuN so i tested this for battle.net and it was just as you guys have said in order for the correct "games" to launch. it doesnt display any error messages but the update symbol wont go away but it isnt an issue, here is what the shortcut should look like this goes for seperate app ids or if you kept them in one. i used both the new executive launch command and the legacy one.  heres an example of my Overwatch 2

Target:
"/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/Battle.net/Battle.net.exe" --exec="launch Pro"

Start in:
"/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files (x86)/Battle.net/"


Launch Options:
STEAM_COMPAT_DATA_PATH="/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/" %command% "battlenet://Pro"




i learned this form here: https://steamcommunity.com/sharedfiles/filedetails/?id=1113049716

**Comment by briggleman** [comment]
@moraroy you are doing the lords work. thanks for the update and happy coding.

**Comment by DandeMC** [comment]
For Diablo 4 it doesn't worked. I don't know why. It opened only the battle.net launcher

**Comment by moraroy** [comment]
@DandeMC sorry I re read my post, this launches the correct Launcher for the games themselves, doing it this way the big play button comes back if that makes sense, I'll do more testing to see what I can do about the actual games. I hear that you need the launcher though to launch them?

**Comment by DandeMC** [comment]
yes i need the battle.net launcher to start the game. I think that's the case with every battle.net game. i would like to start diablo 4 directly without having to press the play button
