### ISSUE TITLE
Reclaiming Size/Calculating Size Beta

### ISSUE THREAD

**Issue by D4EnjoyerSD** [moraroy/NonSteamLaunchers-On-Steam-Deck#67]
Anyone have experienced this issue yet?

I have downloaded and installed NSL for the past few weeks now but I started to experience this issue 2 days ago.

Back then when I launch bnet from the library everything works smooth but now I've noticed that it takes a while before you can hit the Play button to launch a game on Bnet launcher. Status that it shows at that time was Queued then after a few minutes it goes > Reclaiming Space... Then Play button would light Green and you can start to play. 

I thought Queued indicated that there are other applications being update by the launcher but there is no other game installed other than Diablo 4. After checking further I noticed that the Beta option of the launcher seems to be downloading something. (picture attached).

Seems like its trying to download something which was probably the reason for Queue. I have never selected any option with this Beta Menu which makes me confused.

Things I've attempted to do:
-Ran desktop script and chose Fresh start to wipe everything.
-Also tried to ran desktop script and specifically choose Bnet to be uninstalled
-Reimaged Steam deck
-After reimaging, and re-installatin of NSL and Bnet launcher. I am now unable to install the Diablo 4 as it is stuck now on calcuating its size. My bet on this is because of the Beta Software trying to download something and putting everything else on queue.

![354476535_945375870128944_8741125497936594874_n](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/136633046/3775d679-889c-4042-b991-74c3daf78abb)

**Comment by Wargzax** [comment]
It's battle.net problem not related to Non-steam launchers.  Launcher just doesn't update itself and tries to redownload update every time you launch it. You will experience same problem if you install battle.net via Lutris,  directly via proton  and even on windows.
