### ISSUE TITLE
Game Pass Issues

### ISSUE THREAD

**Issue by ItsJohnnyGaming** [moraroy/NonSteamLaunchers-On-Steam-Deck#68]
The Xbox Game pass launcher doesn’t launch, even on proton experimental.

**Comment by moraroy** [comment]
@ItsJohnnyGaming well..... don't use proton brother because Microsoft Edge is a Linux program that you need to have downloaded and installed from the discover store... proton will not work. Leave the force comparability blank and make sure you have edge installed

**Comment by moraroy** [comment]
@ItsJohnnyGaming I've updated the .sh file were able to get game pass working make sure you rerun the script?
