### ISSUE TITLE
Ubisoft service not available

### ISSUE THREAD

**Issue by DandeMC** [moraroy/NonSteamLaunchers-On-Steam-Deck#71]
When I start ubisoft connect it says that the ubisoft service is not available. At google I find that the most problem is that the client is outdated. How I can update the client?

**Comment by moraroy** [comment]
@DandeMC I may have to update the url of ubisoft ....did they change the url from what I have?

**Comment by DandeMC** [comment]
I don't understand. Why should I change a url and how should I know that?

**Comment by moraroy** [comment]
@DandeMC no brother, I'm saying I have to change it.. not you haha

**Comment by DandeMC** [comment]
Aaah okay. I don't know if the url has been changed
