### ISSUE TITLE
Add Tubi, TuneIn Radio, and iHeart Radio, please?

### ISSUE THREAD

**Issue by nanashi89** [moraroy/NonSteamLaunchers-On-Steam-Deck#72]
https://tubitv.com/
https://www.iheart.com/
https://tunein.com/

Any chance you can add these sites, please?

Thanks!

**Comment by moraroy** [comment]
@nanashi89 how is the experience on there with the steam deck? Tbh while it's technically possible to add every website known to man on as a shortcut, I'm not sure if adding certain ones would be worth it. What do you think? @nanashi89

**Comment by nanashi89** [comment]
Just those 3.

And I'm still saving for a Steam Deck. Less than $100 to go.

**Comment by moraroy** [comment]
@nanashi89 hey so I've been thinking of redoing some code and decided to add a new feature just for you. I'm going to add a new button called "Create" and what it does is allow you to input any website you want. So for example when you input the websites you can do multiple like this: Myspace.com, Limewire.com, Aol.com  haha so once you press ok then the script will create a shortcut for you for any website you want!

**Comment by nanashi89** [comment]
Great idea! I found a sweet Spotify clone recently called "Squidify." It's like Spotify, except focuses mainly on game and anime music. Now instead of adding that to my request, you've made things MUCH easier.

Thanks!

PS: Just ordered the Deck today.

**Comment by moraroy** [comment]
@nanashi89 I added in the new Shortcut Creator with v2.97!
