### ISSUE TITLE
Launcher does not works with Proton Experimental Compatibility mode

### ISSUE THREAD

**Issue by mpredolim** [moraroy/NonSteamLaunchers-On-Steam-Deck#74]
Trying to use launchers as EA/Epic/Amazon/Ubisoft all of them doesn´t opens when using Proton Experimental Compatibility mode. I tried other ones as GE-Proton 8.4/8.3 and 7.0.0 and none works.

**Comment by moraroy** [comment]
@mpredolim were you able to troubleshoot this? Are you sure compatability is forced? Also...do you have the default proton 7.0 runtime in your steam library installed? Steam won't run anything If you don't have that...

**Comment by mpredolim** [comment]
Hi.

I have found the issue. When you install more than one launcher, I have
this weird issue. In the other hand, if you install launchers separately it
works fine.

Regards,

Maurício Predolim
+55 11 9 94974290

Em sex, 23 de jun de 2023 20:49, Roy ***@***.***> escreveu:

**Comment by moraroy** [comment]
@mpredolim interesting..OK can you send me the log file?

**Comment by mpredolim** [comment]
Sure but only tomorrow because I'm away from my Steam Deck today.

Maurício Predolim
+55 11 9 94974290

Em sex, 23 de jun de 2023 21:14, Roy ***@***.***> escreveu:
