### ISSUE TITLE
BattleNet launchers not appearing in Steam Library

### ISSUE THREAD

**Issue by Smonkeh** [moraroy/NonSteamLaunchers-On-Steam-Deck#76]
The BattleNet launcher doesn’t appear in my Steam Library after I reached the Jedi message and hit “Okay”. Steam restarts but the launcher is not there. 

Any advise or fix for this?

**Comment by moraroy** [comment]
@Smonkeh i just updated to 2.96, i suggest using that one..i fixed the vdf library not being called in the 2.95 which is exactly why you werent able to add them to library, please try this version out and get back to me to make sure its working properly. i would use the start fresh button before you try 2.96 "start fresh"

**Comment by Smonkeh** [comment]
Thanks for the quick reply. I’ll try again and update you soon.

**Comment by Smonkeh** [comment]
Hi Roy, I have confirmed that the new 2.96 works. Thank you so much!

**Comment by moraroy** [comment]
@Smonkeh no worries brother!! I'm glad it works
