### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Strugglechen1337** [moraroy/NonSteamLaunchers-On-Steam-Deck#77]
Hi great work. 😀 
Is it possible to add ps+ streaming service ?

**Comment by moraroy** [comment]
@Strugglechen1337 would this be through the browser or flatpak or from a github project?

**Comment by Strugglechen1337** [comment]
Oh there is not flatpak, only a exe to install with proton

**Comment by Strugglechen1337** [comment]
https://www.playstation.com/de-de/support/subscriptions/ps-plus-pc/#app


Is a German link but this is the app

**Comment by moraroy** [comment]
@Strugglechen1337 yes I'll add it, does this stream games like GeForce now?

**Comment by Strugglechen1337** [comment]
Yes or like Xbox cloud it's the same way only from Sony PlayStation

**Comment by moraroy** [comment]
@Strugglechen1337 I just tested the install, and it will work... I can't find a good controller layout for it though, the only one that seemed to work well was "Web Browser" and the ps plus also seems to detect game controllers.. so you may want to try and find a good community layout that will work, that way I can implement it in the code to do it automatically.

**Comment by Strugglechen1337** [comment]
Sure let me test it I will post my results 😀

**Comment by moraroy** [comment]
@Strugglechen1337 send me the the username and or even their ID if you can get it, that's how I know how to match the launcher in the config file, also just FYI, I have the launcher in my steam shortcut as Playstation Plus instead of PS Plus

**Comment by Strugglechen1337** [comment]
Which id or username ?
How can I download your new version to test ? 😀

**Comment by moraroy** [comment]
@Strugglechen1337 I'll be able to add to the script tomorrow lol

**Comment by Strugglechen1337** [comment]
Okay cool keep me updatet ! :) thanks for the fast support

**Comment by moraroy** [comment]
@Strugglechen1337 I added it to the latest release!

**Comment by Strugglechen1337** [comment]
Super I will try it und update you !
