### ISSUE TITLE
Cannot install battle.net: "proton" file/dir does not exist

### ISSUE THREAD

**Issue by dearthymcstain** [moraroy/NonSteamLaunchers-On-Steam-Deck#78]
The script correctly finds the proton directory:

https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/blob/main/NonSteamLaunchers.sh#L1319

And then to pass a non-existent "proton" file/directory when trying to install battle.net:

https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/blob/main/NonSteamLaunchers.sh#L1778

```
2023-06-30 10:43:23 (567 KB/s) - ‘/home/deck/Downloads/NonSteamLaunchersInstallation/Battle.net-Setup.exe’ saved [4838352/4838352]

+ echo 'Running BATTLE file using Proton with the /passive option'
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-4/proton run /home/deck/
Downloads/NonSteamLaunchersInstallation/Battle.net-Setup.exe
/home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh: line 164: /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-4/proton: No such file or directory
```

Looking into my filesystem, it appears that the "proton" file/directory that is expected is not present

```
(deck@steamdeck GE-Proton8-4)$ pwd
/home/deck/.steam/root/compatibilitytools.d/GE-Proton8-4
(deck@steamdeck GE-Proton8-4)$ ls
files   LICENSE
```

**Comment by dearthymcstain** [comment]
Perhaps it should call files/bin/wine64 ... ?

**Comment by dearthymcstain** [comment]
I tried hacking the script to sub out "proton" for "files/bin/wine64" and this is the result:

```
2023-06-30 13:14:50 (471 KB/s) - ‘/home/deck/Downloads/NonSteamLaunchersInstallation/Battle.net-Setup.exe’ saved [4838352/4838352]

+ echo 'Running BATTLE file using Proton with the /passive option'
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-4/files/bin/wine64 run /home/deck/Downloads/NonSteamLaunchersInstallation/Battle.net-Setup.exe
wine: using kernel write watches (experimental).
wineserver: using server-side synchronization.
wineserver: invalid format for casemap table /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton8-4/files/bin/../share/wine/nls/l_intl.nls
wine client error:0: recvmsg: Connection reset by peer
```

**Comment by moraroy** [comment]
@dearthymcstain thank you for in depth logs.. how have you installed proton? Through the script or through Proton upqt?

**Comment by dearthymcstain** [comment]
Proton was installed through the desktop script

**Comment by dearthymcstain** [comment]
Also, I only tried to install battle.net. I haven't tried any other installers

**Comment by moraroy** [comment]
@dearthymcstain delete proton ge 8-4 and have it down load it again, see if that fixes it. You should have that proton file in there.. it comes with it. It may have been corrupted somehow. If that doesn't work try installing it via proton upqt...if that still doesn't work let me know.

**Comment by dearthymcstain** [comment]
I had hoped to use NonSteamLaunchers to fix the battle.net failing to relaunch issue. However, today, I found this reddit post (https://www.reddit.com/r/SteamDeck/comments/14hbqs8/diablo_iv_install_method_thats_working_for_me_as/) that seems to be working for me, so I don't think I'll need NonSteamLaunchers at the moment. I'll close this issue for now. Thank you for your hard work and attention.
