### ISSUE TITLE
Individual games in library?

### ISSUE THREAD

**Issue by petruut** [moraroy/NonSteamLaunchers-On-Steam-Deck#80]
How can I add individual games to the steam library? (E.g. have a direct link to GOG’s project Zomboid - not just convenience, but also to be able to set up control schemes per games)

**Comment by moraroy** [comment]
@petruut press the "Find Games" button

**Comment by petruut** [comment]
It’s not able to find my gog galaxy game

**Comment by moraroy** [comment]
@petruut go into the BoilR settings, from there scroll down to "Mini Galaxy" and make sure it's checked, in the path box copy and paste where your GOG Galaxy Games are and then click save. Mini Galaxy will now be able to find your gog games. Go back to the main Boilr window now. And you should be able to now import your games correctly. Be sure to restart steam once imported.
