### ISSUE TITLE
Xbox Game Pass doesn't run

### ISSUE THREAD

**Issue by SoftieIsVibing** [moraroy/NonSteamLaunchers-On-Steam-Deck#81]
The installation goes completely fine and other launchers like Ubisoft plus work as intended as well
but for some reason Xbox game pass just doesnt open :(

**Comment by moraroy** [comment]
@SoftieIsVibing you need Microsoft edge installed from the discover store installed. Chrome you need installed from the discover store only for Amazon luna

**Comment by SoftieIsVibing** [comment]
Oh right i see, so is the gamepass launcher cloud gaming only?

**Comment by moraroy** [comment]
@SoftieIsVibing yeah Xbox game pass, GeForce now and Amazon Luna are all cloud based websites that support game streaming.

**Comment by SoftieIsVibing** [comment]
ah right okay, thank you so much for your help
