### ISSUE TITLE
YouTube doesn’t open

### ISSUE THREAD

**Issue by Chilly167** [moraroy/NonSteamLaunchers-On-Steam-Deck#83]
Tried every proton version literally, have chrome and edge and Mozilla installed with edge being preferred. Just closes after a few seconds after being pressed

**Comment by moraroy** [comment]
@Chilly167 don't use proton brother leave it blank...that's why it's not opening.

**Comment by Chilly167** [comment]
> @Chilly167 don't use proton brother leave it blank...that's why it's not opening.

That fixed the issue! 

But now I have to log into the app everytime, also the controls in the non desktop mode are the worst

**Comment by moraroy** [comment]
@Chilly167 what are the controls set to?

**Comment by Chilly167** [comment]
> @Chilly167 what are the controls set to?

Unsure currently, do you have a layout I can follow? 

Also is there a fix for the login

**Comment by moraroy** [comment]
@Chilly167 brother the controls should just be your default steamdeck... edge already detects this and uses it correctly...I'm not sure why you would be having issues unless the controls have changed... also there is no fix for logging in again and again unless you put "remember me" when you sign in

**Comment by Chilly167** [comment]
> @Chilly167 brother the controls should just be your default steamdeck... edge already detects this and uses it correctly...I'm not sure why you would be having issues unless the controls have changed... also there is no fix for logging in again and again unless you put "remember me" when you sign in



All control schemes are default, remember me I've tried before with no luck, maybe on the switch to desktop I can do something on the browser side. 

Also is there any fix for the blizzard update?
