### ISSUE TITLE
Epic game Achievements

### ISSUE THREAD

**Issue by getbiks** [moraroy/NonSteamLaunchers-On-Steam-Deck#84]
Is the achievements supported by this? I am running games from inside Epic launcher from Gaming Mode. I don't see any achievement popup yet. Is this something which is going to come in future or anyway I can get achievements?
Also is cloud save supported for compatible games?

**Comment by moraroy** [comment]
@getbiks I have no control over this. I don't make the launchers. The only problem I see or can think of is..... use BoilR to find and create a steam shortcut for your games. This will in turn allow you to run your games with epic "in the background" like a normal PC windows computer. As you play your games, depending on the game, see if achievements are supported or not as well as Crossway. Remeber I have zero control over these things as  not the creator of epic games. These things need to be checked on a game to game basis.
