### ISSUE TITLE
EA app won't work after first launch

### ISSUE THREAD

**Issue by EzrealC** [moraroy/NonSteamLaunchers-On-Steam-Deck#85]
The first startup after the installation, everything is normal, but after shutting it down and restarting, it will show a "Background Service crashed. Error code: EC:104". Other launchers like Epic Games is working fine.

Already tried:
1. Fresh start, doesn't work
2. Change compatability tools to GE 8-4, Proton Experimental, doesn't work

**Comment by EzrealC** [comment]
I don’t really know what happened here, but since I turned off proxy settings of Steam OS, EA app works smoothly

**Comment by suavid** [comment]
Same is happening to me :( but I don't have any proxy settings to remove, any clue what was the issue?? Thanks

**Comment by EzrealC** [comment]
> Same is happening to me :( but I don't have any proxy settings to remove, any clue what was the issue?? Thanks

This [video](https://www.youtube.com/watch?v=HwDtgXraxvs) may help
