### ISSUE TITLE
Xbox game pass, won't start up.

### ISSUE THREAD

**Issue by Owendbyme1980** [moraroy/NonSteamLaunchers-On-Steam-Deck#86]
Just received my new Steam deck to day.

Xbox Game Pass wont start up.

After installing everything, it is only the Xbox game pass, that won't start op when I push the start button.

And I have followed the tutorial.

The steam logo comes up, and then force close.  ??

Br. Kim

**Comment by zero80472** [comment]
Make Sure You have Microsoft Edge installed thi happened to me (i did a first run inside desktop mode then signed in first )

**Comment by Owendbyme1980** [comment]
Thanks for the suggestion, but it still doesn't work.

I tried to start it in desktop mode, with Microsoft Edge installt.

Its trying to start but after 5 sec. It just shows the green start button again.

Never got to sign in.

I have done all the steps + experimental settings.

???

Br. Kim.

**Comment by moraroy** [comment]
@Owendbyme1980 brother, is force compatability on? It's not supposed to be, if you installed chrome or edge in the discovery store it's a flatpak and Linux based meaning, forcing experimental proton will make the program not run. Make sure it's unchecked.

**Comment by moraroy** [comment]
@Owendbyme1980 brother, is force compatability on? It's not supposed to be, if you installed chrome or edge in the discovery store it's a flatpak and Linux based meaning, forcing experimental proton will make the program not run. Make sure it's unchecked.

**Comment by Owendbyme1980** [comment]
Thanks 😁

Now works like a charm.
