### ISSUE TITLE
Only Xbox Game Pass is showing up in Library

### ISSUE THREAD

**Issue by ethanash99** [moraroy/NonSteamLaunchers-On-Steam-Deck#87]
Used the most recent 2.96. Didn't realize the incompatibility with Decky Loader. I ran it once and only Game Pass shows up. I deleted decky loader and redid it, but nothing else is loading still.  I have deleted and ran different versions but nothing is working for me. I tried moving it all to the SD storage too but still nothing.
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11992279/NonSteamLaunchers-install.log)

**Comment by ethanash99** [comment]
Game pass also just will not launch at all

**Comment by moraroy** [comment]
@ethanash99 ill be updating soon, but what do you mean "didn't realize the incompatibility with decky loader"?

**Comment by ethanash99** [comment]
I just meant that at the time of trying to use the launcher download, I wasn't aware of the fact that it wouldn't work properly with decky loader installed. I had seen some comments when trying to figure out the issue on my own that mentioned that the two weren't entirely compatible and that you couldn't have decky loader installed while trying to use this to install the launchers.

**Comment by moraroy** [comment]
@ethanash99 that's news to me, and also doesn't really make sense why it wouldn't work. I have decky loader installed and it works fine.

**Comment by moraroy** [comment]
@moraroy that's really strange I'll look into it thanks for letting me know.
