### ISSUE TITLE
Launcher issue nohup: appending output

### ISSUE THREAD

**Issue by Sokobling** [moraroy/NonSteamLaunchers-On-Steam-Deck#88]
@moraroy 
Thanks for this great app for non steam deck launchers. I successfully installed a couple of launchers in the past but when trying to install a new one (uplay) or any other, I get the bellow pop up

Nohup: appending output to 'nohup.out'

It still proceeds and shows that it has installed the launcher however it doesn't. Thanks in advance for any advice on this

**Comment by ethanash99** [comment]
I also had this pop up too but I saw no mention of it in previous issues so I wasn't sure if it had anything to do with mine. I had the same problem

**Comment by moraroy** [comment]
@ethanash99 @Sokobling the no up is from where the script restarts steam. I haven't been able to reproduce this error on my end. My best guess would be to figure out a better way to restart steam then what I'm currently doing. I was doing it this way initially to allow the script to run in game mode. But that hasn't really been a thing that has been working too well for some time.

**Comment by Chilly167** [comment]
> @ethanash99 @Sokobling the no up is from where the script restarts steam. I haven't been able to reproduce this error on my end. My best guess would be to figure out a better way to restart steam then what I'm currently doing. I was doing it this way initially to allow the script to run in game mode. But that hasn't really been a thing that has been working too well for some time.

I too had this issue when in desktop mode
