### ISSUE TITLE
New to this, no launcher selection popup

### ISSUE THREAD

**Issue by NoyBoy53n5ei** [moraroy/NonSteamLaunchers-On-Steam-Deck#89]
Sorry kind of new at this, I installed and extracted, when i go tononsteamlaunchers.desktop it just opens up coding and no popup to add different launchers. Any advice?

**Comment by moraroy** [comment]
@NoyBoy53n5ei just use the .desktop file

**Comment by NoyBoy53n5ei** [comment]
![20230714_092447](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/122756542/1178fd3f-3b7c-4e9d-bd52-89598a221644)

I am clicking on the .desktop file, but that is the one showing me code. Attached an image to show. ive got rid of files and redone the steps to see but nothing changes

**Comment by callit** [comment]
You may need to move the .desktop file to the actual desktop and run it from there.
