### ISSUE TITLE
I only have Netflix, Hulu, YouTube, and Game pass installed, on uninstall none of the links are removed.

### ISSUE THREAD

**Issue by kdliu86** [moraroy/NonSteamLaunchers-On-Steam-Deck#94]
As topic.  On next install there are 2 links per entry.  The installed links are not populated in the GUI.

**Comment by moraroy** [comment]
@kdliu86 the "Uninstall" button doesnt remove any entries in steam i haven't added that functionality yet. Remove the links that you dont want then run the script. The script wont add "Duplicate" entries if that makes sense.
