### ISSUE TITLE
Gog 

### ISSUE THREAD

**Issue by Vaskomyr** [moraroy/NonSteamLaunchers-On-Steam-Deck#95]
Fails download a few seconds after starting. Example- started to download cyberpunk but states error server issue. Is this a common issue? Using proton experimental if that helps. Just assume its user error, was hoping it was just a click install and run.

**Comment by moraroy** [comment]
@Vaskomyr so what you're saying is you can't download the game cyberpunk? But Gog itself was able to install just fine?

**Comment by Vaskomyr** [comment]
Yeah, exactly. However a couple restarts and I'm working fine now. So again probably just user error on my part, but thanks for the reply.

**Comment by Vaskomyr** [comment]
Thanks for replying issue is fixed.
