### ISSUE TITLE
[Enhancement Request] Make it possible for several URL from same base URL to be added

### ISSUE THREAD

**Issue by yongbi85** [moraroy/NonSteamLaunchers-On-Steam-Deck#98]
Hello,

I was trying to add direct link from xbox game pass (URL with launch in it and pointing directly to a given game), however if you pass this information in the custom URL box at the beginning all separated by a comma, only the first one will be picked up.
I'm guessing for the URL list, it picks up only the first one with the same base url (here xbox.com) and will disregard all the others if they are starting by the same base URL

Input :
xbox.com/fr-FR/play/games/forza-horizon-5-%C3%A9dition-standard/9NKX70BBCDRN, xbox.com/fr-FR/play/games/grand-theft-auto-v-xbox-series-x%7Cs/9NXMBTB02ZSF

Output :
xbox.com/fr-FR/play/games/forza-horizon-5-%C3%A9dition-standard/9NKX70BBCDRN

**Comment by moraroy** [comment]
@yongbi85 ive updated the .sh file to  fix this issue the code now allows multiple base urls like you have pointed out..also the names are a little better .... so heres an example:  xbox.com/fr-FR/play/games/forza-horizon-5-%C3%A9dition-standard/9NKX70BBCDRN will now be "Forza Horizon 5 " in the steam shortcut. and xbox.com/fr-FR/play/games/grand-theft-auto-v-xbox-series-x%7Cs/9NXMBTB02ZSF will now be "Grand Theft Auto V Xbox Series X"

**Comment by yongbi85** [comment]
Thanks a lot, gonna have a fun day today with some bulk adding shortcut!!

**Comment by yongbi85** [comment]
Thanks again, i tested it out, it works for some URL, not for all, i'm guessing there is a character limitation, do you know how many is the limit ? (yeah I tryed to set shortcut for 50 games at once xD)
