### ISSUE TITLE
[Bug] Launching the script several times result in duplicate entries

### ISSUE THREAD

**Issue by yongbi85** [moraroy/NonSteamLaunchers-On-Steam-Deck#99]
Hello,

I launched the script several times to add my custom URL shortcut and every time i do so, it will duplicate the existing entries of "normal" program (EA App, Ubisoft Connect, Playsation Plus, ...) that I had installed.
So i have to delete those duplicate entries manually afterwards every time
What i did is launch the program, enter my custom URL, don't select anything and click OK.
Screenshots before and after attached

![Before](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/10360961/ca011b52-3c35-4a9e-a806-d763f5742f89)

![After](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/10360961/2c535ec3-f1a4-44c4-a0e4-53e4d2c49e83)

**Comment by moraroy** [comment]
@yongbi85 yeah im looking into it this one may take a little longer to fix.. but it may be how im restarting steam... ive tested this on mine and couldn't replicate the issue...only very rarely does mine do what youre showing me ill keep looking to fix this.

**Comment by OlivierFortier** [comment]
I just wanted to say the same thing happens to me

**Comment by moraroy** [comment]
@yongbi85 @OlivierFortier theres been quite a few updates to the .sh file let me know if the duplicates issue is still present so far on mine i havnt been able to duplicate it yet, but let me know if its still going on, i added some print strings to help diagnose the problem

**Comment by CozMedic** [comment]
@moraroy, Is there a way to properly add duplicates intentionally? Right now I'm trying to add Steam shortcuts that launch Ubisoft Connect games directly using the `uplay://launch/GAMEID/0` argument.
